### ISSUE TITLE
multiline add function to be available after steps creation in steps database

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#100]
![image](https://user-images.githubusercontent.com/325722/83057334-14377880-a057-11ea-95b3-09bbebe32712.png)
![image](https://user-images.githubusercontent.com/325722/83057342-17326900-a057-11ea-9db7-48f9f21add85.png)

**Comment by koushikmohan1996** [comment]
@poliarush Currently the UI will show if step count is less than 5, Do you want me to show it permanently?

**Comment by poliarush** [comment]
it's new functionality. Let's move it for Arion.
