### ISSUE TITLE
Add a possibility to import tests from Xray (thru API)

### ISSUE THREAD

**Issue by JasonelGrey** [testomatio/app#1000]
**Is your feature request related to a problem? Please describe.**
There are several options available to import tests from popular Test Management Systems, such as TestRail, QTest etc., but unfortunately, Xray is not one of them. This could be a quite useful feature for new customers who want to migrate to Testomat.

**Comment by TetianaKhomenko** [comment]
@DavertMik Need option to import Xray tests in Gherkin format.

**Comment by poliarush** [comment]
@DavertMik we need to make migration script by xray API 
- for server https://docs.getxray.app/display/XRAY/REST+API
- for cloud https://docs.getxray.app/display/XRAYCLOUD/REST+API

**Comment by poliarush** [comment]
@DavertMik 
https://app.crisp.chat/website/4192ab4e-8b76-4b7e-a8c4-ea66dea249e7/inbox/session_247e0042-8301-4ce9-9ac1-6dab21470700/

**Comment by poliarush** [comment]
@JasonelGrey are you ready to assist us so we can create a migration script?

**Comment by poliarush** [comment]
@DavertMik created a channel to discuss migration 
https://testomatio.slack.com/archives/C078T09MP1C/p1718883787796349

**Comment by poliarush** [comment]
@JasonelGrey are you present in testomat.io slack? 
https://join.slack.com/t/testomatio/shared_invite/zt-1ac24wnao-EICi76nXmHbW3GQH4d22uA

**Comment by JasonelGrey** [comment]
@poliarush I am now 👍

**Comment by poliarush** [comment]
@JasonelGrey we will create a private slack group to discuss XRay migration script
https://testomatio.slack.com/archives/C0791JD48M9/p1718903570852009

**Comment by TetianaKhomenko** [comment]
Implemented https://github.com/testomatio/migrate-xray
