### ISSUE TITLE
Cannot create a new Jira subtask ticket for a failed test

### ISSUE THREAD

**Issue by JasonelGrey** [testomatio/app#1002]
**Describe the bug**
It seems that it's not possible at the moment to create a new subtask from the failed test in the test run. The appropriate "Subtask" option is there, but there is no field to specify the parent ticket.

**Pre-requirements**
- The project is integrated with Jira
- At least one test run with the failed test

**To Reproduce**
1. Open test run with the failed test
2. Hover the mouse over the failed test and click on the "create new issue" icon
3. Select profile from the dropdown
4. Choose a "Subtask" ticket type

**Expected behavior**
Additional field allowing the specification of the parent ticket appears

**Actual result**
No new field appears. Validation message appears after clicking on the "Create Jira issue" button

**Screenshots**
![image](https://github.com/testomatio/app/assets/121395677/162bf661-033a-481b-85d6-966ad7cd7441)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Application: [production]

**Comment by littlefrontender** [comment]
backend issue

**Comment by trumenov** [comment]
![image](https://github.com/testomatio/app/assets/58574669/a1ba734a-65d6-4ec7-96c6-bdf80db94b4b)

**Comment by trumenov** [comment]
![image](https://github.com/testomatio/app/assets/58574669/17162fbe-fbd9-482c-a62b-44a80b41a5d2)

**Comment by TetianaKhomenko** [comment]
@trumenov I'm getting an error when trying to create a subtask

![Image](https://github.com/user-attachments/assets/27159f26-b6c2-45a2-987c-62756eeeb60e)

**Comment by trumenov** [comment]
I have tested with fresh jiraDataCenter - this bug i can not reproduce, but good reproduce with jiraCloud here:
https://testomatio-beta.atlassian.net/browse/CLAB-10

So i think Valentin will fix this problem more fast

**Comment by TetianaKhomenko** [comment]
Hi @JasonelGrey! Thanks for reporting the issue. It was fixed. The fix will be published in the next release.

**Comment by JasonelGrey** [comment]
happy days 🎉 
Glad I was able to help 🙂

**Comment by maxkryvoshyya** [comment]
url: https://docs.testomat.io/integration/jira/#failed-test
