### ISSUE TITLE
Label assignment - no visual state

### ISSUE THREAD

**Issue by tikolakin** [testomatio/app#1004]
**Describe the bug**
When a user assigns a label - they don't know if it assigned

**To Reproduce**
Open test case
Open label form
click on label
**Actual**
nothing changes, I don't know whether label is assigned

https://github.com/testomatio/app/assets/5860505/6fd17dab-6c5e-4edc-860d-fcdc7174af4c

**Expected behavior**
Clear and concise UI representation of a label being currently assigned or not

**Env**
 - Browser chrome latest

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin! Thanks for reporting the issue. The fix will be published in the upcoming release.
