### ISSUE TITLE
Test case count is not reflecting against folder after copying

### ISSUE THREAD

**Issue by prajapatimurli** [testomatio/app#1010]
**Describe the bug**
I created a copy of folder after copying the outer folder showing the count whereas after expanding Inner folder showing 0. If manually I added any new testcase then correct count shows.

**To Reproduce**
1. Go to 'Tests'
2. Create new Folder
3. Click on more option and create copy of that Folder
4. Now Expand the newly created folder 
5. Check the test case total count and count against each folder

**Expected behavior**
Total test cases count should match with inner folder (test case) count

**Screenshots**
![Count_issue](https://github.com/testomatio/app/assets/168162255/55e593a6-89da-4f76-9fcc-f14c09732f61)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser -Chrome
 - Browser Version  - 124.0.6367.208

**Comment by littlefrontender** [comment]
backend issue

**Comment by TetianaKhomenko** [comment]
Hi @prajapatimurli! Thanks for reporting the issue. The fix will be published in the upcoming release.
