### ISSUE TITLE
Add link on original run when triggered relaunch on CI

### ISSUE THREAD

**Issue by po-solid** [testomatio/app#1013]
**Describe the solution you'd like**
Currently, when triggering the relaunch of automated tests on the CI via the POST ci/run endpoint, the payload includes the current Run ID (Original Run). However, this value is not available in the new run (Relaunch Run) or in the triggered CI job.

My idea is to save the original Run ID in the relaunch run and make it available through the API endpoint GET runs/{runId}. Optionally, this value should be sent to the CI job (e.g., Jenkins, GitLab, etc.). This solution should simplify the CI rerun implementation and allow connections between runs to be displayed in the UI.

**Additional context**
[root discussion](https://testomatio.slack.com/archives/C061S6XEGH3/p1716803714047229)

**Comment by poliarush** [comment]
@po-solid please create a correct link to discussion

**Comment by TetianaKhomenko** [comment]
Hi @po-solid! The feature was implemented in 0.5.36 version.
