### ISSUE TITLE
archived projects are back active after some time

### ISSUE THREAD

**Issue by RohalskyiOleksii** [testomatio/app#1014]
**To Reproduce**
1. Go to 'project settings'
2. Click on 'administration'
3. press "archive"
4. check that its archived and re-check after some time couple weeks-month

**Expected behavior**
project still archived after some time

**Desktop:**
 - OS: win10
 - Browser chrome
 - Application: production

**Comment by RohalskyiOleksii** [comment]
bug occured again in less then month

**Comment by TetianaKhomenko** [comment]
@TetianaKhomenko project to check https://beta.testomat.io/projects/0571-crash/

**Comment by TetianaKhomenko** [comment]
@Fro0z1k  The issue reproduced on testing env,  https://beta.testomat.io/projects/0571-crash/

**Comment by TetianaKhomenko** [comment]
projects to re-check https://beta.testomat.io/projects/to-be-detached (owner), https://beta.testomat.io/projects/imp-2 (manager)

**Comment by RohalskyiOleksii** [comment]
reproduced again in prod.

**Comment by TetianaKhomenko** [comment]
Hi @RohalskyiOleksii! The issue should be fixed. Please re-open the ticket if the issue reoccurs
