### ISSUE TITLE
Не відпрацьовує фіча з вибором environment при запуску тест рану 

### ISSUE THREAD

**Issue by yanafurmanenko** [testomatio/app#1017]
**STR**
1. Створити тест план
2. Запустити тест ран на створений тест план та обрати в environment iOS та Andriod 

**Actual result** 
Відсутня можливість паралельно проходити тест кейси для iOS та Android 
<img width="1190" alt="Снимок экрана 2024-05-31 в 12 16 05" src="https://github.com/testomatio/app/assets/171326036/d744700e-b419-49f0-b538-f6fe9f7b65b5">
<img width="1356" alt="Снимок экрана 2024-05-31 в 12 16 33" src="https://github.com/testomatio/app/assets/171326036/d25d970a-7a76-4f6a-a5d5-805f38846c8f">

**Expected result** 
При виборі різного environment можна паралельно проходити ран для обраних environment

**Comment by poliarush** [comment]
@yanafurmanenko did you pressed + button?

![2024-06-04_18 57 56@2x](https://github.com/testomatio/app/assets/325722/9cd8b00a-eabb-4d03-be7b-4d0ba1f7754c)

could you please define:

 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Browser Version [e.g. 22]

Could you also, please write a short video

**Comment by yanafurmanenko** [comment]
Показала наглядно на відео, наче все правильно по флоу роблю

Від OS, Browser, Browser Version не залежить - тестували на всіх доступних

**Comment by TetianaKhomenko** [comment]
@yanafurmanenko нажаль в тікеті немає вашого відео. Спробуйте флоу показаний на відео прикріплене в цьому коментарі.

https://github.com/testomatio/app/assets/77803888/4e4901ce-f283-4473-b67d-579782e3a3fe

**Comment by yanafurmanenko** [comment]
так, все працює, виявляється трошки не так робила, дякую)
