### ISSUE TITLE
Render error as code (not markdown)

### ISSUE THREAD

**Issue by tikolakin** [testomatio/app#1018]
**Is your feature request related to a problem? Please describe.**
Always render error with "code" style (not markdown)

**Describe the solution you'd like**
Do not render error like this
![image](https://github.com/testomatio/app/assets/5860505/7c2bc7fc-636a-4776-a057-d071f17a83e5)
Render error like this (you already do it on "Complete Log" view)
![image](https://github.com/testomatio/app/assets/5860505/3fb4ae59-be5b-4c51-9598-5c6b973cacc6)

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin! The fix is live now. Could you please take a look and let us know what you think? ;)

**Comment by tikolakin** [comment]
I think you completely redo it
Thank you, looks so much better
