### ISSUE TITLE
Invited Users with Read-Only access received 403 error in the console and infinite spinner in the UI

### ISSUE THREAD

**Issue by ludmilanesvitiy** [testomatio/app#1020]
**Describe the bug**
Invited Users with Read-Only access received 403 error in the console and infinite spinner in the UI

**To Reproduce**
1. Invite a new Read-only user to the system (Professional Plan)
2. Open an Invitation and accept it
3. Try to open a project
4. Observe the result - in the console 403 error and in the UI only infinite spinner

**Expected behavior**
User should see a Project

**Screenshots**
![Screenshot 2024-05-31 at 14 22 02](https://github.com/testomatio/app/assets/18209841/c5168975-70ca-4ddb-bc14-3a08df3bfbf1)
![Screenshot 2024-05-31 at 14 18 12 (1)](https://github.com/testomatio/app/assets/18209841/6823699a-0ef4-4bb5-bc33-31d4b4bed2bd)

**Desktop (please complete the following information):**
 - OS: any
 - Browser all
 - Application: prod

**Additional context**
![Screenshot 2024-05-31 at 14 22 02](https://github.com/testomatio/app/assets/18209841/8eb75d6d-709f-4608-9df2-7c643c412822)

**Comment by TetianaKhomenko** [comment]
Hi @ludmilanesvitiy! The issue should be fixed. Please reopen the ticket if the issue reoccurs
