### ISSUE TITLE
I can't edit the test case title

### ISSUE THREAD

**Issue by taran-7** [testomatio/app#1021]
**Describe the bug**

**To Reproduce**
1. Open a test case
2. Double click on test title
3. Remove the part of title 
4. Insert new text
5. Click on "Save" button

**Actual Result**
The title hasn't changed

**Expected behavior**
The title will change

**Video:**
https://jam.dev/c/924f1772-4a4d-4ee2-9bd3-8b9c577f3eab

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser Google Chrome 
 - Browser Version 125.0.6422.142 (Official Build) (x86_64)
 - Application: production

**Comment by TetianaKhomenko** [comment]
Hi @taran-7! The issue should be fixed. Please re-open the ticket if the issue still persists
