### ISSUE TITLE
The description area is empty when edit tests from the Run

### ISSUE THREAD

**Issue by lad99vk** [testomatio/app#1022]
**To Reproduce**
1. Go to 'Run' tub
2. Create a new Run
3. Click on the edit test button from RunЭ

**Expected behavior**
Previously saved description is displayed

**Screenshots**

https://github.com/testomatio/app/assets/172023536/1b2bcbce-c5ba-4945-8bd9-c3a75e8bba96

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Browser Version Version 125.0.6422.114 (Official Build) (64-bit)
 - Application: production

**Comment by TetianaKhomenko** [comment]
Hi @vkarchmit! Thanks for reporting the issue. The fix should be live now. Please re-open the ticket if the problem persists for you.
