### ISSUE TITLE
TQL for Runs

### ISSUE THREAD

**Issue by bt-jagababu** [testomatio/app#1024]
**Summary**
Implement Chaining multiple field filters to allow users to filter records by various criteria simultaneously. Currently, the system only permits one field filter at a time, necessitating manual selection for detailed filtering. Attached video for your reference

https://github.com/testomatio/app/assets/150358630/32457f12-cad4-4bb6-920d-0e67add3896a

This feature will enhance usability by enabling users to apply multiple filters at once, such as Team, Category, and Status.

**Description**
To streamline the process of filtering records and improve user experience, it is proposed to introduce the capability to apply multiple field filters concurrently. This enhancement will allow users to efficiently narrow down records based on multiple criteria, significantly reducing the time and effort required for manual selection.

**Comment by TetianaKhomenko** [comment]
Hi @bt-jagababu! The feature was implemented and will be published in the upcoming release.

![Image](https://github.com/user-attachments/assets/4d995f13-1f79-48ae-8ba3-d3ecba56dc06)

**Comment by bt-jagababu** [comment]
@TetianaKhomenko  The usecase of this ticket is to implement the filter with the Operator AND whereas it was implemented with OR condition. Below is the ask

> This feature will enhance usability by enabling users to apply multiple filters at once, such as Team, Category, **and** Status.

Can you please revisit on the same?

**Comment by TetianaKhomenko** [comment]
Need to discuss with dev team. @DavertMik

**Comment by poliarush** [comment]
@trumenov need to make TQL for Runs

**Comment by DavertMik** [comment]
TQL for runs operators:


* `created_at, finished_at, updated_at`
* `duration, passed_count,  failed_count skipped_count`
* `label` (or `labels`)
* `tag` (or `tags`)
* `jira`
* `plan`: `plan == '{PlanID}'` or `plan % 'Plan 1'`

To check for testruns inclusion:

* `has_test` - `has_test == 'TestID'` or `has_test % 'Test Title'`
* `has_suite` - `has_suite == 'SuiteID'` or `has_suite % `Suite Title``
* `has_message` - `has_message == 'start of message'`
* `has_assigned_to` - username
* `has_retries` - `has_retries > 0`
* `has_test_duration` - `has_test_duration > 100`
```

**Comment by DavertMik** [comment]
Query Language Component should be updated

![image](https://github.com/user-attachments/assets/0153ae9e-0c43-41b6-9ad8-a4a5a55b918f)

**Comment by maxkryvoshyya** [comment]
url: https://docs.testomat.io/getting-started/managing-runs/#filter-runs-by-tql
