### ISSUE TITLE
Failure Evidence Artifacts such as video and trace files are not uploaded in Testomat.io

### ISSUE THREAD

**Issue by bt-jagababu** [testomatio/app#1025]
Recently, the functionality for uploading failure evidence artifacts has not been working properly. This issue has been observed over the last few days. Specifically, most of the failed tests only include screenshots, and none of the tests have all three artifacts (Screenshots, Playwright Trace, Video) as expected. 

This problem is causing engineers to manually retrieve artifacts from CI jobs, which is time-consuming and inefficient.  

Main issue is deflect from not using Testomat.io.

Debug info:

`FAIL  | 0 passed, 1 failed, 5 skipped   // 39s
  @testomatio/reporter:adapter:codeceptjs waiting for all tests to be reported +4s
[TESTOMATIO] Attachments: 🎞️  Uploading 1 video/-s ...
  @testomatio/reporter:file-uploader S3 config {
  S3_ENDPOINT: 'https://s3.us-east-005.backblazeb2.com/',
  S3_REGION: 'us-east-005',
  S3_BUCKET: 'betler-test-artifacts',
  S3_ACCESS_KEY_ID: '***',
  S3_SECRET_ACCESS_KEY: '***',
  S3_SESSION_TOKEN: undefined,
  TESTOMATIO_DISABLE_ARTIFACTS: undefined,
  TESTOMATIO_PRIVATE_ARTIFACTS: '1',
  S3_FORCE_PATH_STYLE: undefined
} +4s
  @testomatio/reporter:file-uploader Started upload /Users/jagadeesanbabu/git/betler.infra.e2e-test/codeceptBDD/tests/src/report/videos/fb3ada68-bdf3-48f4-a69b-c0998ea844ee_Verify_Brazil_pix_deposit_is_successful_and_GA_events_are_triggered_for_the_safecharge_@br_@Tc8f993c1.failed.webm to  betler-test-artifacts +0ms
[TESTOMATIO] Attachments: 📁 Uploading 1 trace/-s ...
  @testomatio/reporter:file-uploader S3 config {
  S3_ENDPOINT: 'https://s3.us-east-005.backblazeb2.com/',
  S3_REGION: 'us-east-005',
  S3_BUCKET: 'betler-test-artifacts',
  S3_ACCESS_KEY_ID: '***',
  S3_SECRET_ACCESS_KEY: '***',
  S3_SESSION_TOKEN: undefined,
  TESTOMATIO_DISABLE_ARTIFACTS: undefined,
  TESTOMATIO_PRIVATE_ARTIFACTS: '1',
  S3_FORCE_PATH_STYLE: undefined
} +0ms
  @testomatio/reporter:file-uploader Started upload /Users/jagadeesanbabu/git/betler.infra.e2e-test/codeceptBDD/tests/src/report/trace/ed646c75-2f06-4c53-9569-0db961236717_Verify_Brazil_pix_deposit_is_successful_and_GA_events_are_triggered_for_the_safecharge_@br_@Tc8f993c1.failed.zip to  betler-test-artifacts +0ms
  @testomatio/reporter:client Updating run status... +39s
  @testomatio/reporter:pipe:testomatio 📨 Batch upload 5 tests +4s
  @testomatio/reporter:pipe:testomatio Finishing run... +0ms
  @testomatio/reporter:pipe:testomatio Finishing run... +0ms
  @testomatio/reporter:file-uploader File:  /Users/jagadeesanbabu/git/betler.infra.e2e-test/codeceptBDD/tests/src/report/videos/fb3ada68-bdf3-48f4-a69b-c0998ea844ee_Verify_Brazil_pix_deposit_is_successful_and_GA_events_are_triggered_for_the_safecharge_@br_@Tc8f993c1.failed.webm  exists +3ms
  @testomatio/reporter:file-uploader File:  /Users/jagadeesanbabu/git/betler.infra.e2e-test/codeceptBDD/tests/src/report/trace/ed646c75-2f06-4c53-9569-0db961236717_Verify_Brazil_pix_deposit_is_successful_and_GA_events_are_triggered_for_the_safecharge_@br_@Tc8f993c1.failed.zip  exists +0ms
[TESTOMATIO] 📊 Report Saved. Report URL: https://app.testomat.io/projects/accounts-tribe-e2e-tests/runs/03fe8599/report
  @testomatio/reporter:pipe:testomatio Run finished +718ms
  @testomatio/reporter:client TOTAL artifacts 1 +718ms
[TESTOMATIO] 🗄️ 1 artifacts privately uploaded to S3 bucket
  @testomatio/reporter:file-uploader Succesfully uploaded /Users/jagadeesanbabu/git/betler.infra.e2e-test/codeceptBDD/tests/src/report/trace/ed646c75-2f06-4c53-9569-0db961236717_Verify_Brazil_pix_deposit_is_successful_and_GA_events_are_triggered_for_the_safecharge_@br_@Tc8f993c1.failed.zip => betler-test-artifacts/b7d3ec53-3faa-413d-987b-307bde80db9b/46eb7cdb-4034-4aaa-97ba-3ab6b23912fb-ed646c75-2f06-4c53-9569-0db961236717_Verify_Brazil_pix_deposit_is_successful_and_GA_events_are_triggered_for_the_safecharge_@br_@Tc8f993c1.failed.zip | URL: https://betler-test-artifacts.s3.us-east-005.backblazeb2.com/b7d3ec53-3faa-413d-987b-307bde80db9b/46eb7cdb-4034-4aaa-97ba-3ab6b23912fb-ed646c75-2f06-4c53-9569-0db961236717_Verify_Brazil_pix_deposit_is_successful_and_GA_events_are_triggered_for_the_safecharge_%40br_%40Tc8f993c1.failed.zip +1s
  @testomatio/reporter:file-uploader Succesfully uploaded /Users/jagadeesanbabu/git/betler.infra.e2e-test/codeceptBDD/tests/src/report/videos/fb3ada68-bdf3-48f4-a69b-c0998ea844ee_Verify_Brazil_pix_deposit_is_successful_and_GA_events_are_triggered_for_the_safecharge_@br_@Tc8f993c1.failed.webm => betler-test-artifacts/b7d3ec53-3faa-413d-987b-307bde80db9b/f2eceb91-6d6e-46bf-9cf9-daff35a03b9e-fb3ada68-bdf3-48f4-a69b-c0998ea844ee_Verify_Brazil_pix_deposit_is_successful_and_GA_events_are_triggered_for_the_safecharge_@br_@Tc8f993c1.failed.webm | URL: https://betler-test-artifacts.s3.us-east-005.backblazeb2.com/b7d3ec53-3faa-413d-987b-307bde80db9b/f2eceb91-6d6e-46bf-9cf9-daff35a03b9e-fb3ada68-bdf3-48f4-a69b-c0998ea844ee_Verify_Brazil_pix_deposit_is_successful_and_GA_events_are_triggered_for_the_safecharge_%40br_%40Tc8f993c1.failed.webm +118ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Process finished with exit code 1`

**Comment by TetianaKhomenko** [comment]
Closing the ticket as fixed
