### ISSUE TITLE
Test result history per folder (job)

### ISSUE THREAD

**Issue by tikolakin** [testomatio/app#1027]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to see a history of a test case for a given job.
I will put it in the prospect of the jenkins approach.

Given I have a folder name Staging regression (Jenkins job) and test runs (jenkins builds) in the folder
When I open a test case from the test run of a folder
And navigate to the Runs tab (test result history)
I want to be able to see history filtered only by a given folder - Staging regression (job)
And I do not want to see test case history of test runs from folders other than Staging regression 

**Additional context**
Viewing entire test case history is still useful - but it's accessible from the test case page.

**Comment by poliarush** [comment]
@littlefrontender do we need to have backend here?

**Comment by littlefrontender** [comment]
@poliarush yes, I need separate request for filter by folder

**Comment by TetianaKhomenko** [comment]
I think we discussed this on the meeting with the user. Adding screenshots for reference:

![CleanShot 2024-06-20 at 12 26 55@2x](https://github.com/testomatio/app/assets/77803888/2c97f9af-8efb-4901-b4a0-5728ca7a8d1b)

**Comment by DavertMik** [comment]
We should implement filters for Runs, that would be enough for the first implementation

**Comment by TetianaKhomenko** [comment]
@trumenov please help here, filters don't return reults

https://github.com/user-attachments/assets/2392d7f2-f390-4241-aa83-f655c20e280b

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin! The feature was implemented. It will be published in the upcoming release. Also attaching a demo video

https://github.com/user-attachments/assets/6ff278bc-131c-4f8a-a2db-ca57c82cbac8

**Comment by poliarush** [comment]
@trumenov can you add filter by parent RunGroup where Test Run is located?

**Comment by trumenov** [comment]
> can you add filter by parent RunGroup where Test Run is located?

It is too hard for me - Valentin will make it in few times faster.

**Comment by littlefrontender** [comment]
@poliarush @trumenov I will do it

**Comment by poliarush** [comment]
https://github.com/user-attachments/assets/99d13124-7b54-4a92-a557-bd56a24f41ff

**Comment by TetianaKhomenko** [comment]
The feature was implemented and will be published in the upcoming release.

**Comment by maxkryvoshyya** [comment]
URL: https://docs.testomat.io/getting-started/managing-runs/#reports
