### ISSUE TITLE
Support Playwright test.step in reports

### ISSUE THREAD

**Issue by alexander-goncharuk** [testomatio/app#1028]
**Describe the solution you'd like**
When uploading a Playwright test run repot to testomat.io, we would like to be able to:

1. See all the tests included in the run
2. Expand each test to see the steps ([test.step in Playwright API](https://playwright.dev/docs/api/class-test#test-step)) of each test

It's similar to what you get in Playwright HTML reporter or when running in --ui mode. 

When I go to Test => Automated in my testomat.io dashboard or explore test run report in a List view, I get close to what we need, but the missing part is simple sub-list of steps.

**Describe alternatives you've considered**
[Step in Testomat functions](https://docs.testomat.io/reference/reporter/functions/#step). 
But ideally would prefer to not adjust tests code for concrete reporter needs.

**Comment by DavertMik** [comment]
@AZANIR please do the following

* propose steps format which is simple and universal and supports nested steps
* add this format definition to `types.d.ts`
* check how Playwright passes steps and how it formats them

We can also use Playwright steps to write description to tests

**Comment by AZANIR** [comment]
**Step Format Proposal**
The proposed format will include the following elements:

**_title_**: The name of the step.
**_body_**: The function that performs the step, returning a **Promise**.
**_options_** (optional): Additional options such as **_box_**.
We will define the structure to support nested steps by allowing the **_body_** to call other steps.


```
// types.d.ts

type StepOptions = {
  box?: boolean;
};

type StepFunction = () => Promise<any>;

interface Step {
  title: string;
  body: StepFunction;
  options?: StepOptions;
}

type Steps = Step[];
```


**Step Declaration**: Use test.step('Title', async () => { ... }) to declare steps.
**Nested Steps**: Nest steps by calling test.step within another test.step.
**Step Formatting**: Titles and body functions are used to describe and implement steps, which are then shown in the test reports.
**Options**: Customize step behavior using options like box.

**Comment by poliarush** [comment]
related to https://github.com/testomatio/app/issues/1036#issuecomment-2222839603

![image](https://github.com/user-attachments/assets/a53ecd0f-4f6e-4a6f-952a-2a34c2f13459)
