### ISSUE TITLE
Page navigation going to the first page - Jira plugin

### ISSUE THREAD

**Issue by leandroefron** [testomatio/app#1029]
**Is your feature request related to a problem? Please describe.**
- Navigate tests in Jira plugin to page 4 (or any page different than the first one). 
- I click on any view test icon. 
- Go back to the tests list.
- I am redirected to the first page when I was on page 4.
So I need to remember on what page I was to continue navigating from the same point.

**Describe the solution you'd like**
When I go back to tests list, I would like to be on the same page I was before I clicked on the view test icon.

https://github.com/testomatio/app/assets/8061144/1fb13147-17a1-47a1-b575-7dde2be40eae

**Comment by poliarush** [comment]
@littlefrontender do you need any backend here?

**Comment by littlefrontender** [comment]
@poliarush no, I can do it myself

**Comment by TetianaKhomenko** [comment]
Hi @leandroefron! Thanks for reporting the issue! The fix will be published in the upcoming release.
