### ISSUE TITLE
JIRA connection failed. [object,Object] error is given

### ISSUE THREAD

**Issue by Duncan-atwork** [testomatio/app#1030]
**Describe the bug**
Not sure when this started but was not able to connect to JIRA tickets from testomat.  I created a new API key to test it out and I’m getting these errors when I Test Connection (see attached)

**To Reproduce**
1. Go to Settings -> JIRA Integration
2. Click on existing connection
3. In JIRA create a new token and enter that new value into Testomat
4. Click Test Connection.  See error

**Expected behavior**
Should connect with brand new credentials but if it doesn't something helpful about error

**Screenshots**
JIRA integration error in Testomat.jpg
![JIRA integration error in Testomat](https://github.com/testomatio/app/assets/147850360/d6de2f1f-bce7-4791-a9c1-54f3315f526b)

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.5.2
 - Browser Chrome
 - Browser Version 125
 - Application: production 

Additional Info:
This was working with connections but for awhile but at some point it stopped where links in JIRA stopped working.  That's when I put new credentials in to test it out.  this is using JIRA cloud so possible they changed but I wasn't aware of when it happened.

**Comment by poliarush** [comment]
@Duncan-atwork please re-check it, it should be fixed.
