### ISSUE TITLE
Improve automated tests duplication and copy

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#1032]
**Describe the bug**

Users copy/duplicate **automated tests** for quick creation of new tests. But they don't need original test's imported code and automated badge.

**Expected behavior**
When we copy the automated test it should:
1. have "manual" state, because there is not imported code from the source code yet
2. no code description shown in the copy (don't show Code tab)

**Screenshots**

![CleanShot 2024-06-19 at 13 04 45@2x](https://github.com/testomatio/app/assets/77803888/c6426738-d398-4ec4-bb4f-09ceee3a355c)

**Comment by poliarush** [comment]
related to https://github.com/testomatio/app/issues/1032

**Comment by TetianaKhomenko** [comment]
implemented
