### ISSUE TITLE
Display steps as tree

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#1036]
**Is your feature request related to a problem? Please describe.**

Users may have different test implementations and **tests nesting**. 
Such logs take much time to read and analyze them. So users want to have the ability to hide nested steps to see only high-level information first and then expand to see more logs or nested steps.

**Describe the solution you'd like**

1. Introduce the ability to automatically hide nested steps in the Test Result view by prefix (@DavertMik please provide more details on this). Those hidden steps should have the ability to expand as well.
2. Ability to configure prefix

**Additional context**

Needed in Test result detail view:

![CleanShot 2024-06-20 at 08 07 02@2x](https://github.com/testomatio/app/assets/77803888/844fe062-3235-4d5f-93dc-4b16410215ac)

Needed in Test result Complete log view:

![CleanShot 2024-06-20 at 08 07 56@2x](https://github.com/testomatio/app/assets/77803888/a160c5d6-327e-4550-9c88-552ca18ae932)

Run Report Test Result detail view and Complete log:

![CleanShot 2024-06-20 at 08 27 38@2x](https://github.com/testomatio/app/assets/77803888/7a556dc1-fdca-4700-970c-d9e3dfb9dfac)

**Comment by TetianaKhomenko** [comment]
It would be convenient when by clicking on `>` you could expand/collapse the step

![image](https://github.com/testomatio/app/assets/77803888/55216dcf-baf0-49b4-a793-eaecfb870ba3)

**Comment by littlefrontender** [comment]
@TetianaKhomenko hard to do

**Comment by LolikTest** [comment]
We want to have possibility to expand \ hide Steps
By Default only 1st level should be visible, all inner steps should be hidden.
By clicking on Step it should Expand 
![image (58)](https://github.com/testomatio/app/assets/12410819/dec8cecc-a945-49cb-9fbe-e485e2e91a62)

**Comment by TetianaKhomenko** [comment]
@DavertMik as far as I remember we plan to introduce some of your changes in the next release, am I right?

**Comment by TetianaKhomenko** [comment]
implemented

**Comment by TetianaKhomenko** [comment]
@YanaBaranova0909 please check if we have this described in our documentation.
