### ISSUE TITLE
Parse logs and show URL in run results logs 

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#1037]
**Is your feature request related to a problem? Please describe.**

Users may pass URLs in logs and we want to make those URLs accessible from the test result view.

**Additional context**

![CleanShot 2024-06-20 at 08 30 24@2x](https://github.com/testomatio/app/assets/77803888/3ab66285-62c6-4f60-9679-8047391bedc7)

**Comment by TetianaKhomenko** [comment]
implemented

![image](https://github.com/testomatio/app/assets/77803888/9fec4204-e031-49fc-98b3-977fa68e75f5)

**Comment by TetianaKhomenko** [comment]
@maxkryvoshyya https://docs.testomat.io/getting-started/running-automated-tests/#how-to-enable-playwright-trace-viewer

related to https://github.com/testomatio/app/issues/1037

**Comment by maxkryvoshyya** [comment]
URL: https://docs.testomat.io/getting-started/running-automated-tests/#stack-traces
