### ISSUE TITLE
Broken counters

### ISSUE THREAD

**Issue by tikolakin** [testomatio/app#1038]
**Describe the bug**
Counters do not make sense
Test counter doesn't match anywhere with actual test count
Actual test count: 42
The actual test count displayed on the top filter: 46
The actual test count displayed on the right: 30 or 18

**To Reproduce**
Use filters on test list view

https://github.com/testomatio/app/assets/5860505/164e61aa-09d9-45a0-b8fb-6444b6e6ae82

**Comment by poliarush** [comment]
@littlefrontender is this backedend issue?

**Comment by littlefrontender** [comment]
@poliarush yes

**Comment by TetianaKhomenko** [comment]
@Fro0z1k The issue is related to tests shown in search results after filtering. As I understand `tests found` counter shows number of tests shown on the page (due to pagination), which misleads users. Users expects to see the sum of all tests, not number per page.

**Comment by DavertMik** [comment]
@TetianaKhomenko is that search or counters issue?
30+18=48 so I assume counters were correct

**Comment by tikolakin** [comment]
@DavertMik @TetianaKhomenko 
Please notice on the video how counter value 30 becomes 18 when user uses a list of test (scrolling, or expanding/collapsing folders) - it just doesn't make sense 
Expected behaviour: counter shows the total number of test that match current filter 
NOTE: total number != currently visible on the page

**Comment by DavertMik** [comment]
@tikolakin I agree, just trying to figure out the application section where the fix should be applied

**Comment by tikolakin** [comment]
It shouldn't be a complicated fix
at `https://app.testomat.io/api/PROJECT/rungroups?show_archived=false` you already have total number of the items in the query 
```
    "meta": {
        "total_pages": 16,
        "per_page": 50,
        "num": 768,
        "page": 1
    }
```
at the `https://app.testomat.io/api/PROJECT/suites/search?filter=true&priority[]=critical&labels[]=dashboard&page=1`
you get wrong `num`
```
    "meta": {
        "num": 30,
        "total_pages": 3,
        "strict_search": true
    }
```
Clearly, pagging of the list if tests isn't quite correct
    
   Please fix it. It was very painful to explain to the team why number of tests is like it

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin! The issue has already been fixed. The fix will be published in the next release. 

![2024-08-23 11 48 00](https://github.com/user-attachments/assets/68d239f8-096f-46a5-a02a-c18efcfbf0a1)

**Comment by tikolakin** [comment]
Thanks, confirmed it works good now on our end
