### ISSUE TITLE
Project Analytics default range = 4 weeks

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#1041]
**Is your feature request related to a problem? Please describe.**

Users may have 500+ items in project analytics widgets.
For now, we show data for all period by default which slows down the app and makes data inaccessible at all.

**Describe the solution you'd like**
Introduce default range = 4 weeks for Project Analytics
OR/ AND
Give users the possibility to setup default range for Project Analytics

**Additional context**

![CleanShot 2024-06-20 at 10 45 12@2x](https://github.com/testomatio/app/assets/77803888/6f39f33f-b94f-48b4-8784-62340278102f)

**Comment by TetianaKhomenko** [comment]
implemented

**Comment by maxkryvoshyya** [comment]
URL: https://docs.testomat.io/usage/analytics/#analytics-range
