### ISSUE TITLE
Improve Run Group charts for many runs

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#1042]
**Is your feature request related to a problem? Please describe.**

Users may have 500+ runs within the group. 
For now, Run group chart is not readable for such an amount of data.
Related to https://github.com/testomatio/app/issues/1039

**Describe the solution you'd like**

1. introduce options to switch between Run group chart screens (50 per screen)
2. show 50 runs results per chart page

**Additional context**

![CleanShot 2024-06-20 at 10 51 29@2x](https://github.com/testomatio/app/assets/77803888/2da03bd8-53eb-4f9a-a6a6-b3a9b08dc00e)

**Comment by tikolakin** [comment]
@TetianaKhomenko just to make sure
The chart should render currently displayed test runs and be aligned with the pagger
Test runs list should have a pagger with 50 items on each page

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin ! The feature was implemented. It will be published in the upcoming release.

![Image](https://github.com/user-attachments/assets/b3c56e88-af3a-4c5f-ab8e-ef42655423b1)

**Comment by TetianaKhomenko** [comment]
@maxkryvoshyya https://docs.testomat.io/getting-started/managing-runs/#rungroups

**Comment by maxkryvoshyya** [comment]
URL: https://docs.testomat.io/getting-started/managing-runs/#rungroup-chart
