### ISSUE TITLE
Show testomat project in which there are associated tests - Jira plugin

### ISSUE THREAD

**Issue by leandroefron** [testomatio/app#1044]
**Is your feature request related to a problem? Please describe.**
Scenario: 
Some jira tickets are related to a Testomat project and others to a diff Testomat project, so when I move between them, current session is always getting last testomat project I worked on.

Steps:
- Open ticket 1 who has linked tests on testomat project A.
- Open ticket 2 who has linked tests on testomat project B.
- Plugin displays testomat project A.
- Change project to B to see linked tests.
- Open ticket 1.
- Plugin displays testomat project B.

**Describe the solution you'd like**
I would like for each jira ticket to show the Testomat project in which there are associated tests
Attach video.

**Comment by TetianaKhomenko** [comment]
Hi @leandroefron! Thanks for reporting. This behavior will be improved in the upcoming release.

**Comment by poliarush** [comment]
@leandroefron is this expected?

https://github.com/user-attachments/assets/1e7fb148-a5a2-4a54-93d6-e4656fd8b91a

**Comment by leandroefron** [comment]
Hi @poliarush I can`t watch the video. Is it ok?
