### ISSUE TITLE
Numbering should auto correct for following steps while creating test case if new step(s) added.

### ISSUE THREAD

**Issue by prajapatimurli** [testomatio/app#1046]
**Describe the bug**
Whenever user added new steps in between of existing test case, He/she needs to manually update numbering.

**To Reproduce**
1. Login to the Testomatio with valid credential
2. Click on Tests(Located at left menu item)
3. Edit any existing test case
4. Add a new step in between existing step
5. Check the newly added step numbering

**Expected behavior**
It should auto correct numbering of following steps if new step added 

**Screenshots**
![image](https://github.com/testomatio/app/assets/168162255/4cfd1d30-6126-4e27-ae52-541c90d67a94)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Browser Version 126.0.6478.114
 - Application: Beta

**Comment by TetianaKhomenko** [comment]
Hi @prajapatimurli! The issue was fixed. The fix will be added to the upcoming release. Thanks for reporting the issue.


![Image](https://github.com/testomatio/app/assets/77803888/1f17c21f-c1f8-4597-82e4-58b3860e38c1)
