### ISSUE TITLE
Issue with run_at TQL var

### ISSUE THREAD

**Issue by bt-jagababu** [testomatio/app#1047]
**Describe the bug**
Custom charts are not working with run_at

Please see the video here 
https://testomatio.slack.com/archives/C06KM0NA47J/p1718638694154819?thread_ts=1718638650.908389&cid=C06KM0NA47J

![2024-06-20_23 20 11@2x](https://github.com/testomatio/app/assets/325722/ac598993-578b-4c02-bf7a-eedf014bf6fd)

**Comment by TetianaKhomenko** [comment]
related to https://github.com/testomatio/testomatio/issues/4302

**Comment by DavertMik** [comment]
After migration on prod should be executed

```
bundle exec rails testomatio:data_migrate:v0535_update_run_at_for_tests
```

**Comment by TetianaKhomenko** [comment]
Hi @bt-jagababu! Thanks for reporting the issue. It has been fixed. The fix will be published in the upcoming release.

![Image](https://github.com/testomatio/app/assets/77803888/9a744ab8-f649-49e1-a521-63c9900e2d96)
