### ISSUE TITLE
Empty folders are created by check-tests if the tests inside it have been moved

### ISSUE THREAD

**Issue by cjol** [testomatio/app#1049]
**Describe the bug**
After running check-tests, it seems that folders matching the source-code structure are always created. If tests have been moved to a different directory in testomat.io, then these folders are empty and unnecessary.

**To Reproduce**
1. Run `check-tests Mocha \"**/*{.,_}{test,spec,cy}.ts\" --typescript --sync --update-ids` with a deeply-nested directory structure (some of these params may be unnecessary; I haven't checked every combination)
2. In testomat.io, move all tests to a new top-level directory, created in testomat.
3. Re-run `check-tests Mocha \"**/*{.,_}{test,spec,cy}.ts\" --typescript --sync --update-ids`

**Expected behavior**
Nothing should change on testomat, because nothing has changed in the source code. In fact, the tests are correctly matched by ID, so they are not re-created, but the original folder structure is created (and they are empty). These folders are cluttering the UI, so they should not be created.

**Screenshots**
<img width="597" alt="image" src="https://github.com/testomatio/app/assets/1517675/f268a537-504a-47ff-b914-cd8faecd00a6">
Desktop (please complete the following information):

OS: macOS 14.5
Browser Chrome
check-tests: ^0.8.24

**Additional Context**
This is important to us because we use folders extensively in our source code, but within Testomat it's quite annoying and slow to navigate in the web-app, so we want to "flatten" the folder structure in Testomat.

**Comment by DavertMik** [comment]
Please use `--no-empty` option for that

```
npx check-tests ... --no-empty
```
