### ISSUE TITLE
Trash Bin showing multiple  versions when user switches tabs from Test to Suites

### ISSUE THREAD

**Issue by prajapatimurli** [testomatio/app#1050]
**Describe the bug**
Trash Bin showing multiple  versions when user switches tabs from Test to Suites

**To Reproduce**
1. Login with valid credential to Testomatio
2. Click on Test menu item(left side menus)
3. Navigate to More options(Right top corner)
4. Click on Trash in
5. Observe the Version count
6. Switch to Tests to Suite 
7. Overserve the Version Count 

**Expected behavior**
Suite should display correct version

**Screenshots**

https://github.com/testomatio/app/assets/168162255/1238ef3e-878f-4b88-bcb1-3b18c2dabbda

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Browser Version 126.0.6478.115

**Comment by TetianaKhomenko** [comment]
related to https://github.com/testomatio/testomatio/issues/4310

**Comment by TetianaKhomenko** [comment]
Hi @prajapatimurli!  The bug was fixed and the fix will be published in the upcoming release. Thanks for reporting the issue
