### ISSUE TITLE
Running tests overwrites test code from importer

### ISSUE THREAD

**Issue by cjol** [testomatio/app#1051]
**Describe the bug**
The test reporter and test importer import code differently (the reporter doesn't seem to handle TypeScript code well, which I can create a separate ticket for if you like). This wouldn't be a problem except that the reporter overwrites the code which was previously (correctly) imported by the importer.

**To Reproduce**
1. Import a new Typescript test (I used `check-tests Mocha \"**/*{.,_}{test,spec,cy}.ts\" --typescript --sync --update-ids`)
2. Observe that the test code is correctly imported:     
    <img width="772" alt="image" src="https://github.com/testomatio/app/assets/1517675/5b9db21f-3864-4fbe-b0ff-6f421404982b">
3. Run the test in question and report the results (I used `mocha --parallel --jobs 5 -R ./node_modules/@testomatio/reporter/lib/adapter/mocha.js`). Note that TESTOMATIO_CREATE is not set, so I am not requesting that the test be imported in any way. 
4. Observe that the test code has been replaced (this is now showing compiled output, not the original source code)
    <img width="771" alt="image" src="https://github.com/testomatio/app/assets/1517675/aea784e3-82c1-4f07-a202-4230469f5489">

**Expected behavior**
The test source code should not be modified when the test is executed. Or if it is, it should use the same method as used by the test importer so that it's at least consistent.

**Additional Context**
This seems to bypass the test versioning system. After the initial import, the test version is "V2", and the diff against LIVE looks like this:
<img width="815" alt="image" src="https://github.com/testomatio/app/assets/1517675/a4d7cbff-8737-4537-9859-aba172b5db99">
After running the test, the source code changes as above but the test version is still "V2", but now the diff against LIVE looks like this:
<img width="812" alt="image" src="https://github.com/testomatio/app/assets/1517675/aab0c81d-e95f-4bd4-8266-606a6285a220">

The diff against "Current" is unchanged, and still looks like this: 
<img width="810" alt="image" src="https://github.com/testomatio/app/assets/1517675/ffdad6a2-ae72-4a39-84c6-8a1bc8dac040">

**Comment by DavertMik** [comment]
@AZANIR we need to discuss this one

**Comment by DavertMik** [comment]
@AZANIR look through adapters, we take the code from the running function but we can add an option to remove it

For instance, this is mocha framework:

![Image](https://github.com/user-attachments/assets/7d4989a8-5086-4681-bc14-0d095bcddd1d)


Please change introduce new env variable `TESTOMATIO_UPDATE_CODE` so it would be:

```js
if (process.env.TESTOMATIO_UPDATE_CODE)) code = test.body.toString(),
```

**Comment by DavertMik** [comment]
@AZANIR up

**Comment by olexandr13** [comment]
https://github.com/testomatio/reporter/pull/436
