### ISSUE TITLE
Logger doesn't work for parallel test runs

### ISSUE THREAD

**Issue by cjol** [testomatio/app#1053]
**Describe the bug**
When tests are executed in parallel, the logging section disappears completely. 

**To Reproduce**
1. Clone the [mocha example repo](https://github.com/testomatio/examples/tree/master/mocha-ts-multi-reporters)
2. Run the example tests in parallel with `npm run tests -- --parallel  --jobs=2`
3. Click on the report URL, and observe that the report for "logs should be added to the testomatio report" has no logs attached 
<img width="814" alt="image" src="https://github.com/testomatio/app/assets/1517675/64ba58a9-84cf-466b-b823-f66a270976bf">

**Expected behavior**
Logs should be displayed on the test run (as they are if the parallelism is disabled)

**Additional context**
I assume that the test log capture is based on timing which might make it too difficult to capture logs and associate the correct test. If that's the case, and running tests in parallel is not supported, then the documentation should be updated to reflect this.

**Comment by poliarush** [comment]
@cjol did you checked? 

https://docs.testomat.io/getting-started/running-automated-tests/#reporting-parallel-tests

**Comment by cjol** [comment]
Thanks for the link, I did not see that at first. However it seems to describe a different problem "you might end with multiple reports per each executed process". 

Just in case, I have tried "Strategy 2" as described in that document, but that makes no difference to the outcome.

```sh
TESTOMATIO_SHARED_RUN=1 TESTOMATIO_TITLE="UniqTitleForThisBuild" npm test -- --parallel --jobs=5
```
<img width="1632" alt="image" src="https://github.com/testomatio/app/assets/1517675/cff21089-bf54-49b2-af95-d3098ac0da85">

**Comment by olexandr13** [comment]
@cjol please tell which logs do you expect?
I assume you have some logs in your terminal on testrun but they are not uploaded to Testomat? Share screenshot.

**Comment by cjol** [comment]
Hi, the reproduction in the issue I reported is from your own test suite.

https://github.com/testomatio/examples/blob/master/mocha-ts-multi-reporters/spec/logger.spec.ts#L5-L7

**Comment by olexandr13** [comment]
@cjol
the reason is that some time ago we disabled automatic console logs sending to testomat. to enable, set `TESTOMATIO_INTERCEPT_CONSOLE_LOGS=1`

![Image](https://github.com/user-attachments/assets/35f6135e-f5a1-4a91-aa69-e72b95cc9f1f)
