### ISSUE TITLE
Re-assign tests in bulk

### ISSUE THREAD

**Issue by TheZZ13** [testomatio/app#1054]
**Is your feature request related to a problem? Please describe.**
Is there any easier way to assign a person to a testrun after the run has been created, other than clicking the name of the existing person assigned and then assigning to another? It's tedious because I have to select one test and then re-assign vs doing a multi select and changing the assigned person.
![Screenshot 2024-06-10 at 1 06 26 PM](https://github.com/testomatio/app/assets/36581640/01d35685-2a76-4533-8470-e0fdafc8911b)

**Describe the solution you'd like**
I would like to be able to bulk select tests and then re-assign them to another user. This is similar to bulk delete of tests from a testrun.

**Describe alternatives you've considered**
Currently you have to select one test at at time and then re-assign each test. 

**Additional context**
I brought this topic up in the Slack thread here: https://testomatio.slack.com/archives/C04PM8N3KGA/p1718046454389189

**Comment by TetianaKhomenko** [comment]
Hi @TheZZ13! Thanks for the feature request! We implemented this feature, it will be published in the upcoming release.

![Image](https://github.com/user-attachments/assets/53aee7ff-745a-4fb6-a92d-ebae13214306)
