### ISSUE TITLE
Add Test Result Title (Automated Test Name) to Test Result Header

### ISSUE THREAD

**Issue by LolikTest** [testomatio/app#1055]
**Is your feature request related to a problem? Please describe.**
There is no Test Title in Test Results Detailed View
You can only see Manual Test Case Name after whole Automated Test Log

**Describe the solution you'd like**
Add Automated Test Name to Header of Test Result Detailed View

**Example:**
![image (56)](https://github.com/testomatio/app/assets/12410819/9d05450e-ed15-434a-bb55-a7d9f43f648c)
![image (57)](https://github.com/testomatio/app/assets/12410819/4d4f0b59-43e6-4332-81a0-b618cfffafdd)

**Comment by TetianaKhomenko** [comment]
related to https://github.com/testomatio/app/issues/1036

**Comment by TetianaKhomenko** [comment]
Hi @AlexLAA! The feature was implemented. It will be published in Testomat version 0.5.35

![Image](https://github.com/user-attachments/assets/1a9d3fed-d70c-43fc-b312-bea46a469698)
