### ISSUE TITLE
[tags] when creating a test there is no drop-down list of tags

### ISSUE THREAD

**Issue by VDemyanova** [testomatio/app#1056]
**Describe the bug**
There is no drop-down list of tags when creating a test in the sidebar of the suite view.

**To Reproduce**
1. Go to 'https://app.testomat.io/projects/firm-web/suite/[id]'
2. Set @ in the test creation field

**Expected behavior**
A dropdown list appears with all tags after entering the @ symbol

**Screenshots**

https://github.com/testomatio/app/assets/173828606/2ac09234-b20e-4576-b26a-5442944f08b0

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Browser Version 125.0.6422.77
 - Application: production 

**Additional context**
I want a dropdown list of tags to appear everywhere after entering the @ symbol

**Comment by TetianaKhomenko** [comment]
Hi @VDemyanova! Thanks for your suggestion. The fix ill be published in the upcoming release.



https://github.com/user-attachments/assets/8cc1cc04-b90c-46dd-bf9c-3b7a8977e75d

**Comment by maxkryvoshyya** [comment]
https://docs.testomat.io/getting-started/test-design/

**Comment by maxkryvoshyya** [comment]
URL: https://docs.testomat.io/getting-started/test-design/#how-to-add-a-labeltag-to-a-test
