### ISSUE TITLE
Clickable test ID in the test

### ISSUE THREAD

**Issue by VDemyanova** [testomatio/app#1057]
**Is your feature request related to a problem? Please describe.**
Hello! For manual tests, we use links to other tests in preconditions. Now we can only insert a link.

**Describe the solution you'd like**
We want to insert the ID of another test into the test. This ID becomes a link to the test. When you hover over the link, a preview of the test opens. Clicking on the links opens the test in a new window.

**Describe alternatives you've considered**
An alternative is a clickable link when inserting the test ID.

**Comment by poliarush** [comment]
@littlefrontender 

we need a behaviour where user insert ID of test or test suite, and link will be automatically identified and generated a link to open test or test suite. Also the link should open in current window. Please give me a shout if you need any clarification

**Comment by poliarush** [comment]
![2024-06-26_09 40 03@2x](https://github.com/testomatio/app/assets/325722/194a25a2-7d31-4022-a963-426c01a5edbf)

**Comment by TetianaKhomenko** [comment]
Hi @VDemyanova! Thanks for the feature request. The feature was implemented and will be published in the next release. Attaching a short demo video below.

https://github.com/user-attachments/assets/86821af7-19c1-4c09-929c-6f3f310b6bee

**Comment by maxkryvoshyya** [comment]
url: https://docs.testomat.io/getting-started/test-design/#cross-linking-tests-suites-and-folders
