### ISSUE TITLE
Showing incorrect timestamp at title as per IST, after running the test case (timezone)

### ISSUE THREAD

**Issue by prajapatimurli** [testomatio/app#1058]
**Describe the bug**
Showing incorrect timestamp at title as per IST, after running the test case. It should display time as per local timezone

**To Reproduce**
1. Login to the Testomatio with valid user credential
2. Design some test case 
3. Create Plan(from side bar) and test case to execute 
4. Navigate to more option and click on Launch button
5. Execute test case and finished it.
6. Notice the **AUTO GENERTED title**(Refer Screenshots)

**Expected behavior**
It should display correct time as per IST

**Screenshots**
![time_issue2](https://github.com/testomatio/app/assets/168162255/fa9cdb13-fc9b-4e08-a47e-582cd75b51ae)
![time_issue1](https://github.com/testomatio/app/assets/168162255/a1476921-15d4-4439-8bd3-c44d36afdf9b)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Browser Version 126.0.6478.127

**Comment by poliarush** [comment]
please set your local time here and retry

![2024-06-28_12 08 56@2x](https://github.com/testomatio/app/assets/325722/0ccc4ed1-f08a-4fee-b401-2e98c240d262)

**Comment by prajapatimurli** [comment]
> please set your local time here and retry
> 
> ![2024-06-28_12 08 56@2x](https://private-user-images.githubusercontent.com/325722/344125240-0ccc4ed1-f08a-4fee-b401-2e98c240d262.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NzE5NjQsIm5iZiI6MTcxOTU3MTY2NCwicGF0aCI6Ii8zMjU3MjIvMzQ0MTI1MjQwLTBjY2M0ZWQxLWYwOGEtNGZlZS1iNDAxLTJlOThjMjQwZDI2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOFQxMDQ3NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzc4NzMzOTQ0MjI0ZWU5N2ZmYzM1ZmZiY2UwNzFmNDJhMTM1MTgwOGEwMTU2OGQzNGZlZDZlYWYwOGQ0ZGZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XbJ3wLruKs8J8pTPDEUxgWxxNdBoQRDf_T79BhXSf3I)

@poliarush It was already set 
![image](https://github.com/testomatio/app/assets/168162255/e1acaa93-29ad-4eaa-8e76-2c0f816d8d86)

**Comment by TetianaKhomenko** [comment]
can be related to https://github.com/testomatio/app/issues/998

**Comment by TetianaKhomenko** [comment]
Add timezone to project settings

**Comment by prajapatimurli** [comment]
> Add timezone to project settings

@TetianaKhomenko  Will you please share reference for Project. I am unable to find it for specific project.

**Comment by TetianaKhomenko** [comment]
@prajapatimurli  Sorry, it's a note for the developer. The feature is on planning stage now

**Comment by TetianaKhomenko** [comment]
Hi @prajapatimurli! We will add the Timezone setting to Project > Settings > Project > Administration > Timezone. You will need to set a timezone so new runs will have the right time. The feature will be published in the next release. 

![Image](https://github.com/user-attachments/assets/ca2081c4-e09d-4de8-8c98-bc151070e35c)

**Comment by maxkryvoshyya** [comment]
url: https://docs.testomat.io/getting-started/project/
