### ISSUE TITLE
Infinite preloader when changing priority

### ISSUE THREAD

**Issue by VDemyanova** [testomatio/app#1060]
**Describe the bug**
Infinite preloader when changing priority

**To Reproduce**
1. Go to page with tests
2. Click on 'Multi-select' button
3. Select several tests
4. Click on 'Priority' in the bottom panel
5. Select priority
6. Click on 'Apply'

**Expected behavior**
The priority of the selected tests has changed.

**Screenshots**
<img width="1352" alt="Снимок экрана 2024-06-28 в 16 06 19" src="https://github.com/testomatio/app/assets/173828606/58b3166d-5c81-4449-8952-b7827927e02e">

**Desktop (please complete the following information):**
- OS: iOS
- Browser chrome
- Browser Version 125.0.6422.77
- Application: production

**Comment by VDemyanova** [comment]
<img width="1352" alt="Снимок экрана 2024-06-28 в 16 15 25" src="https://github.com/testomatio/app/assets/173828606/c8fa1f9a-dd7c-449d-82a8-7acfb5c8ae29">

**Comment by TetianaKhomenko** [comment]
Hi @VDemyanova! It's a temporary issue. Please try using the feature in 30 mins. Thanks for reporting

**Comment by VDemyanova** [comment]
Bulk priority editing doesn't work 👎

**Comment by VDemyanova** [comment]
@TetianaKhomenko 
<img width="1352" alt="Снимок экрана 2024-06-28 в 17 11 20" src="https://github.com/testomatio/app/assets/173828606/7c619837-07ca-4c7c-8d44-600c50d76e88">

**Comment by TetianaKhomenko** [comment]
Hi @VDemyanova ! It's a temporary issue caused by some spamming requests ;)  Please wait a little
