### ISSUE TITLE
`not` in the label value breaks search query

### ISSUE THREAD

**Issue by tikolakin** [testomatio/app#1062]
**To Reproduce**
<img width="573" alt="image" src="https://github.com/testomatio/app/assets/5860505/118a5f4c-9e11-4f41-9881-b8e7f1e94a5a">

<img width="717" alt="image" src="https://github.com/testomatio/app/assets/5860505/40b82854-aba3-447c-8023-4dcf7db76e28">

<img width="801" alt="image" src="https://github.com/testomatio/app/assets/5860505/17ad3cbc-6937-4d08-9e05-3f70d6b3bb8e">

<img width="985" alt="image" src="https://github.com/testomatio/app/assets/5860505/ca717ee2-a0d8-4e5b-84f4-3a7c7ead693d">

**Expected behavior**
`not` in the label value must not affect search query syntax

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin! Thanks for reporting the issue! It has been fixed. The fix will be published in the upcoming release.

**Comment by tikolakin** [comment]
verified on my end

**Comment by TetianaKhomenko** [comment]
@tikolakin thanks for the feedback
