### ISSUE TITLE
Search is not giving expected result at Report

### ISSUE THREAD

**Issue by prajapatimurli** [testomatio/app#1063]
**Describe the bug**
A report search is not giving expected result once user type data and cleared it. 

**To Reproduce**
1. Go to Runs(Side bar)
2. Click on any run title (Plan)
3. Click on 'Report'
4. Type dummy(random text) e.g. zzzzzzzz
5. A proper Result will display e.g. **No tests matched**
6. Clear search content and type valid text 
7. A proper Result will display
8. Now, Clear search text and again type e.g. zzzzzzzz
9. Error - Showing some result which is incorrect as per searched text
10. Clear and again type valid text 
11. Error - Showing result but not fully matching with searched result as shown after step 7

**Expected behavior**
1. Search should display **"No tests matched"** on re-searching. (Dummy content)
2. A matching result should display on Re-searching (Valid content)

**Screenshots**
![image](https://github.com/testomatio/app/assets/168162255/e0906434-7906-4abd-b98e-2a04fb03b74c)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Browser Version 126.0.6478.127

**Comment by trumenov** [comment]
[Runs - Testomat.io.webm](https://github.com/user-attachments/assets/2b1d7da4-9ca0-428a-bbd9-845ab90766a1)

**Comment by trumenov** [comment]
![image](https://github.com/user-attachments/assets/ada8353d-c2a4-4fb8-a2a3-e80d6ece2e51)

**Comment by TetianaKhomenko** [comment]
Hi @prajapatimurli! Thanks for reporting the issue. The fix will be published in the upcoming release.
