### ISSUE TITLE
A parse error shows up if a test is duplicated

### ISSUE THREAD

**Issue by auroraDigio** [testomatio/app#1064]
**Describe the bug**
A parse error shows up every time a test is duplicated, the project is classic so no BDD language applies.

**To Reproduce**
1. Go to SUITE eg 'https://app.testomat.io/projects/symposium/suite/1d2aeaa7'
2. Click on test eg 'https://app.testomat.io/projects/symposium/test/394de325'
3. Click on Duplicated (right upper corner of the screen)
![image](https://github.com/testomatio/app/assets/174609602/4c07aaf0-fa82-4499-8030-f0a24be6a0ba)

**Expected behavior**
the test is duplicated successfully

**Screenshots**
If applicable, add screenshots or video to help explain your problem.

https://github.com/testomatio/app/assets/174609602/ab943ed9-619a-43ab-a4a6-a35b10ed51c4

**Desktop (please complete the following information):**
 - Browser Version [e.g. 22]
 - Application: [production or beta] 

**Additional context**

**Comment by TetianaKhomenko** [comment]
Hi @auroraDigio! Thank you for reporting the issue. The fix is live now. 
Please feel free to re-open the ticket if the issue re-occurs.
