### ISSUE TITLE
Automated test-cases doubled, after automated part of mixed run finished

### ISSUE THREAD

**Issue by dnlstpnv** [testomatio/app#1067]
**Describtion**
Automated test-cases are doubled In mixed after automated part finished using: 

`TESTOMATIO=${tstm_access_key} TESTOMATIO_RUN=${runId} npx start-test-run --finish`

**To Reproduce**
1. Go to 'Runs' page
2. Click on '...'
3. Click on 'Mixed run' with automated and manual cases
4. Pass all needed data for run
5. Click on Launch
6. Wait till job end
7. Finish launch using cli command from description

**Expected behavior**
Mixed run contain only automated tests with status passed/skipped/failed and manual cases without any doubles.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: safari 
 - Browser Version 19618.2.12.11.6
 - Application: production

**Additional context**
Test plan: 
 - cases: 41
 - automated 39
 - manual 2

**Screenshots**
<img width="901" alt="Screenshot 2024-07-09 at 2 12 30 PM" src="https://github.com/testomatio/app/assets/57957484/fe5ca0a1-8d50-4f19-baf0-ae7afbb7cbec">
<img width="899" alt="Screenshot 2024-07-09 at 3 00 28 PM" src="https://github.com/testomatio/app/assets/57957484/c7566db4-48e9-4cd4-9ca5-eac004ac6ac1">
<img width="899" alt="Screenshot 2024-07-09 at 3 01 11 PM" src="https://github.com/testomatio/app/assets/57957484/e32d6397-b646-4a88-9f50-3f3f29dd42c3">

**Comment by DavertMik** [comment]
Fixed on production

**Comment by TetianaKhomenko** [comment]
The issue was fixed with Testomatio reporter version 1.4.6
@dnlstpnv please check it
