### ISSUE TITLE
Fix Azure AD Auth with AuthContextClassRef Error

### ISSUE THREAD

**Issue by bheemvennapureddy** [testomatio/app#1072]
[Error - AADSTS75011 Authentication method by which the user authenticated with the service doesn't match requested authentication method AuthnContextClassRef. - Azure | Microsoft Learn](https://learn.microsoft.com/en-us/troubleshoot/azure/entra/entra-id/app-integration/error-code-aadsts75011-auth-method-mismatch)

**Comment by TetianaKhomenko** [comment]
Hi @bheemvennapureddy! The issue should be fixed now. Please check on your side and let us know if it was fixed for you.

**Comment by bheemvennapureddy** [comment]
What changes do we need to make on our side ?

**Comment by TetianaKhomenko** [comment]
@bheemvennapureddy Leave authn context blank and try different auth types

**Comment by TetianaKhomenko** [comment]
closing as done
