### ISSUE TITLE
Automation test coverage shows 100% on analytics page regardless 

### ISSUE THREAD

**Issue by selma-spread** [testomatio/app#1073]
**Describe the bug**
When analysing 2 projects automation test coverage percentage doesnt recalculate

**To Reproduce**
1. Have two projects with one having more manual test cases and the other proportional automated test cases
2.   go to analytics page
3. compare the analytics of both projects

**Expected behavior**
Automation test coverage should recalculate  percentage based on number of automated tests covered however it shows 100%
**Screenshots**
![Screenshot 2024-07-15 at 15 37 52](https://github.com/user-attachments/assets/74c8a05f-3ec1-4d99-b521-bce6d5273661)

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser chrome
 - Browser Version [e.g. 22]
 - Application: [production or beta]

**Comment by trumenov** [comment]
Fields 'Automation Coverage' and 'Manual / Automated' is not the same. 
In 'Manual / Automated' you can see manual and automated tests counters.
In 'Automation Coverage' you can see percents of tests with 'automatable_label' - settings for this label you can find in the settimgs modal here:
![image](https://github.com/user-attachments/assets/53b458d5-857b-46f2-b576-9b161d886d91)

So if you will add label "Automatable" to any of your tests you will see staticstics in this column.
We already have discussion for renaming the 'Automation Coverage' naming, but it is still in progress.

**Comment by DavertMik** [comment]
Behavrios should be:

```
Manual vs Automated + label:Automatable
```

So if no Automatable label it will be

```
manual vs automated
```

if no automated tests but tests with automatable label:

```
manual vs label:automatable 
```
(current behavior)

**Comment by TetianaKhomenko** [comment]
Hi @selma-spread! The fix is live now. You can check it on your data
