### ISSUE TITLE
Drag and drop folders does not work

### ISSUE THREAD

**Issue by VDemyanova** [testomatio/app#1074]
**Describe the bug**
It is important to me that my folders are in the correct order. But I noticed that the sorting is constantly getting confused and I cannot return it to how it was.

**Preconditions**
Folders with many suites and tests.

**To Reproduce**
1. Go to the Tests page
2. Drag and drop folder in root section
3. The first time the folder is in the right place, the second time the hierarchy gets confused.

**Expected behavior**
Folders are sorted in the order I set.

**Screenshots**
If applicable, add screenshots or video to help explain your problem.

https://github.com/user-attachments/assets/2abc0f80-e5fe-47ec-b557-c732e4ed788f

**Desktop (please complete the following information):**
- OS: iOS
- Browser chrome
- Browser Version 125.0.6422.77
- Application: production

**Comment by TetianaKhomenko** [comment]
@littlefrontender the issue is also present for tests

https://github.com/user-attachments/assets/b0df9722-64a5-41fa-be81-8748a1fd1831

**Comment by TetianaKhomenko** [comment]
@littlefrontender the issue is still present 

https://github.com/user-attachments/assets/4dc629dd-3633-4a4e-a87f-43d673d03a4d

**Comment by TetianaKhomenko** [comment]
Hi @VDemyanova! The issue has been fixed. Please check it on your side
