### ISSUE TITLE
Tooltip does not display for main navigation menu items 

### ISSUE THREAD

**Issue by bklyuka** [testomatio/app#1075]
**Describe the bug**
Tooltip does not display the main navigation menu items 

**Pre-conditions**
1. Make sure you are logged in
2. Make sure you're on the project page

**To Reproduce**
1. Hover the mouse over any item in the main navigation menu

**Expected behavior**
Observe that the tooltip appears

**Actual**
Observe that nothing happens

**Video**

https://github.com/user-attachments/assets/daf5a4ce-0f92-4899-a1bc-bfee0e17753f

**Desktop (please complete the following information):**
 - Win 11 ro
 - Chrome Version 126.0.6478.127 (Official Build) (64-bit)

**Comment by TetianaKhomenko** [comment]
Hi @bklyuka! Thanks for reporting the issue! It should be fixed.
