### ISSUE TITLE
This site can’t be reached when hit on change my password

### ISSUE THREAD

**Issue by bklyuka** [testomatio/app#1076]
**Describe the bug**
This site can’t be reached when hit on change my password

**Pre-Condition:**
1. Make sure that you already have an account created
2. Make sure that you are on /users/sign_in page

**To Reproduce**
1. Click on Forgot your password?
2. Set your email and click on Restore
3. Go to your email box and click on Change my password

**Expected behavior**
Im not sure about expected behavior but something like set your new password and confirm it form should be opened when user is able to modify the password

**Actual**
Nothin is happened, the loading page is still displayed the following
![image](https://github.com/user-attachments/assets/444c1a3a-e7a9-428d-937c-8f47d9b18d6c)

**Comment by TetianaKhomenko** [comment]
Hi @bklyuka! Thanks for reporting the issue. The issue should be fixed in the upcoming release.
