### ISSUE TITLE
Error when enabling living docs

### ISSUE THREAD

**Issue by VDemyanova** [testomatio/app#1080]
**Describe the bug**
Error when enabling living docs

**To Reproduce**
1. Go to Settings -> Project
2. Click on check-box "Share Living Docs"

**Expected behavior**
Living docs is enable

**Screenshots**
If applicable, add screenshots or video to help explain your problem.
<img width="1352" alt="Снимок экрана 2024-07-22 в 13 08 37" src="https://github.com/user-attachments/assets/790924b7-14f3-4580-9288-ffa1911ca47f">

**Desktop (please complete the following information):**
- OS: iOS
- Browser chrome
- Browser Version 125.0.6422.77
- Application: production

**Additional context**

**Comment by TetianaKhomenko** [comment]
The issue is also present for Enable Public Report setting

**Comment by TetianaKhomenko** [comment]
Hi @VDemyanova! Thanks for reporting. The fix is live now.
