### ISSUE TITLE
uploading tests can take several minutes (and longer)

### ISSUE THREAD

**Issue by aitestautomation** [testomatio/app#1082]
**Describe the bug**
uploading tests results in JUnit.xml formats can take several minutes (and longer)
this is ONLY 1 test that takes 5s, and the upload has already taken 15 mins and has not finished yet
as it is, testomat.io in CI/CD cycle serves me only as an integrator under KPIs, not as an online knowledge source

releasing uploads again and again results in single uploads hanging around, even though newer ones have already finished

**To Reproduce**
upload JUnit.xml style 

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/b0773bca-d77a-4800-b0c1-fcb902abceab)

**Desktop (please complete the following information):**
upload via Windows and Linux
1 test or more (1 test take some times 20min, 5k take few minutes or more)

**Additional context**

**Comment by DavertMik** [comment]
Sorry, if you face a performance downgrade. We are optimizing our internal systems.

**Comment by TetianaKhomenko** [comment]
Hi @aitestautomation! Could you please re-check on your side? Thanks

**Comment by poliarush** [comment]
@aitestautomation please re-check it and re-open if it's not fixed for you.
