### ISSUE TITLE
Issue uploading multiple images using clipboard sequentially

### ISSUE THREAD

**Issue by itz4blitz** [testomatio/app#1083]
**Describe the bug**
When attempting to upload images from the clipboard using Testomat, the upload sometimes fails. Specifically, after successfully uploading the first two images, the third image does not upload and disappears after initially appearing to upload.

**To Reproduce**
1. Capture screenshots of your test scenario.
2. Copy the screenshots to the clipboard.
3. Open Testomat and attempt to paste the images from the clipboard.
4. Observe that the first two images upload successfully, but the third image fails to upload.

**Expected behavior**
All images copied to the clipboard should upload successfully to Testomat without disappearing.

**Desktop (please complete the following information):**
- OS: macOS
- Browser: Chrome
- Browser Version: 22
- Application: Production

**Additional context**
The issue occurs when I try to paste images from my clipboard into Testomat. Initially, the image appears to upload, but then it disappears. The first two images upload fine, but the issue occurs with the third image.

There are no errors in the browser's dev console. The clipboard is not empty and contains the image. A video demonstrating the issue has been provided.

**Comment by poliarush** [comment]
https://testomatio.slack.com/archives/C071TB8L80H/p1721825007308199

**Comment by littlefrontender** [comment]
i think it is backend issue. 

I have a suggestion. I tried to upload identical images and the server did not return them to me. If there is validation of such files on the backend, I suggest to return the error: ‘Such file already exists’, or remove this validation.

@DavertMik What do you think?

**Comment by DavertMik** [comment]
Agreed. I check for the same files, I think I implemented this when added diagrams

**Comment by DavertMik** [comment]
@littlefrontender added error as suggested



![Image](https://github.com/user-attachments/assets/6f4284bc-601f-4503-b3e4-5a253cb5c56b)

If it is annoying I can remove it

**Comment by TetianaKhomenko** [comment]
> [@littlefrontender](https://github.com/littlefrontender) added error as suggested
> 
> ![Image](https://github.com/user-attachments/assets/6f4284bc-601f-4503-b3e4-5a253cb5c56b)
> 
> If it is annoying I can remove it

@littlefrontender  need to improve the error message text

![Image](https://github.com/user-attachments/assets/88b0f33e-5ce8-4d61-ac65-891b427b1310)

**Comment by TetianaKhomenko** [comment]
Hi @itz4blitz! Thanks for reporting the issue! The issue has been fixed. The fix will be published in the upcoming release.
