### ISSUE TITLE
Bulk test creation error

### ISSUE THREAD

**Issue by VDemyanova** [testomatio/app#1084]
**Describe the bug**
I can't create tests in bulk.

**To Reproduce**
1. Go to 'test'
2. Create new suite
3. Create bulk tests

**Expected behavior**
tests created

**Screenshots**
<img width="1352" alt="Снимок экрана 2024-07-26 в 12 10 05" src="https://github.com/user-attachments/assets/fa0baf41-855c-4bfa-826d-f733206962d1">

**Desktop (please complete the following information):**
- OS: iOS
- Browser chrome
- Browser Version 125.0.6422.77
- Application: production

**Comment by VDemyanova** [comment]
When creating one test, the same error.
<img width="1352" alt="Снимок экрана 2024-07-26 в 12 20 29" src="https://github.com/user-attachments/assets/910e9340-53cf-412b-9602-2646addaccb8">

**Comment by TetianaKhomenko** [comment]
Hi @VDemyanova! The issue should be fixed now. Could you please check on your side
