### ISSUE TITLE
In Jira, the test cases previewed as a markup language text in preview mode

### ISSUE THREAD

**Issue by ali-transmedia** [testomatio/app#1085]
**Describe the bug**
In Jira, the test cases previewed as a markup language text in preview mode

**To Reproduce**
1. Go to 'https://app.testomat.io/'
2. Create and link a test case to Jira
3. View the test case from Jira

**Expected behavior**
Test cases should be previewed as a plain text
**Screenshots**
![prob](https://github.com/user-attachments/assets/fdd5ead3-3693-4ad3-ad05-4f71a1a4b905)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Browser Version: Version 126.0.6478.183 (Official Build) (arm64)
 - Application: production

**Additional context**

**Comment by TetianaKhomenko** [comment]
Hi @ali-transmedia! Thanks for the suggestion. The improvement will be published in the next release. 

![Image](https://github.com/user-attachments/assets/50a83be0-2c54-4244-9040-267fbb748fc6)
