### ISSUE TITLE
Add ability to Copy Markdown Link of test case

### ISSUE THREAD

**Issue by chura90** [testomatio/app#1089]
**Acceptance criteria**
* add a Markdown Link to the Copy Setting of the test case
* the link should be in the following format: 
[@Tc5cc25fb](https://app.testomat.io/projects/immediate/test/c5cc25fb-assignment-management-api-returns-pending-collisions-for-the-specified-user/ "Assignment Management API Returns PENDING Collisions For the Specified User @core @small")

This will allow us to copy the link of the test case in the appropriate format to link to the GitLab ticket

[test case Link format.odt](https://github.com/user-attachments/files/16425086/test.case.Link.format.odt)

<img width="1413" alt="Screenshot 2024-07-30 at 11 54 53" src="https://github.com/user-attachments/assets/61c6930f-bc69-470f-9c5b-f4531be11640">

**Comment by poliarush** [comment]
@chura90 could you please add more details about markdown format you're looking for 
is it something about this?
```
[Assignment management api](https://app.testomat.io/projects/immediate/test/c5cc25fb-assignment-management-api-returns-pending-collisions-for-the-specified-user/)
```

**Comment by chura90** [comment]
the test case Link format.odt file has been added as attachment so you can download it and check the appropriate link format

**Comment by TetianaKhomenko** [comment]
Hi @chura90! Thanks for the feature request. The feature was implemented and will be published in the next release. 

Here is an example of the link  `[@T11dace54](https://beta.testomat.io/projects/timelines-07-2024/test/11dace54-quisque-arcu-libero-rutrum/ "quisque arcu libero rutrum")`

![image](https://github.com/user-attachments/assets/d881adc5-1ff4-41f1-9841-23c38bc18332)

**Comment by chura90** [comment]
Thanks!
