### ISSUE TITLE
Improve the UX(look) of the attached files in the description field, now the file dimensions are 400*400

### ISSUE THREAD

**Issue by rustamLA** [testomatio/app#1091]
**Describe the bug**
The attached HTML file(for example) looks enormous in the preview mode of the test case

**To Reproduce**
1. Open your newly created test case in edit mode and add the HTML file to your steps or preconditions;
2. Save and check out the look of this file in the preview/view mode;

**Expected behavior**
It would be nice to display the same file/icon size as on the attachment tab
![image](https://github.com/user-attachments/assets/6e9be6e1-146d-435d-9ed9-b6d32907fdf6)
<img width="352" alt="image" src="https://github.com/user-attachments/assets/8504d86d-2fe8-4d35-9ab8-04b5cde8dcf8">

**AR:**
![image](https://github.com/user-attachments/assets/57298145-d61c-46fe-9868-049138381a42)
<img width="431" alt="image" src="https://github.com/user-attachments/assets/f5583b94-e69e-4bd6-82f1-f50c05d75e45">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome and others 
 - Browser Version: any version
 - Application: production

**Comment by TetianaKhomenko** [comment]
Hi @rustamLA! Thanks for reporting the issue. We made icons smaller, this should improve UX. This improvement will be published in the upcoming release. 

![Image](https://github.com/user-attachments/assets/0327b351-fe03-4058-a5df-a862b6903d37)
