### ISSUE TITLE
Add resize for images with ability to open in new tab after clicking on it

### ISSUE THREAD

**Issue by VitalikZ** [testomatio/app#1099]
Sometimes we need to add full screen image and it's not convenient if it's displayed with full image so user can go case by case and open image when user want to open it. This feature exist in gitlab docs. Please add it to your project.

**Comment by poliarush** [comment]
@VitalikZ give some gitlab examples
also please give some testomat.io screenshot of page you're talking about

**Comment by poliarush** [comment]
@VitalikZ 
in fact you already have control to open screenshots in fullscreen or sized by width or height

![2024-08-14_11 27 42@2x](https://github.com/user-attachments/assets/d9ab2df6-9d38-4d45-87d3-ffa7e2e70996)

![2024-08-14_11 28 39@2x](https://github.com/user-attachments/assets/020fd49d-4de5-4a47-8201-046cd2fe38b8)

**Comment by poliarush** [comment]
@VitalikZ or are you talking about image usage in description?

![2024-08-14_11 29 43@2x](https://github.com/user-attachments/assets/54a5f82a-b4da-4d7f-a78f-517e36dfcaf3)

**Comment by poliarush** [comment]
@littlefrontender it's about sizing image within markdown used in description

**Comment by DavertMik** [comment]
This can be done on backend side

**Comment by poliarush** [comment]
@DavertMik @littlefrontender 

no, i think we should improve behaviour in preview mode, to set displaying size and expanding/collapsing images,
from markdown perspective everything will be the same but in preview mode, you can set some user-configuration setting for image

**Comment by VitalikZ** [comment]
@poliarush yes, in the description
**Actual result:**
<img width="1118" alt="Screen shot 2024-08-15 at 13 16 48" src="https://github.com/user-attachments/assets/97797468-c1c2-47ff-836e-d7a03912f220">
<img width="1116" alt="Screen shot 2024-08-15 at 13 16 55" src="https://github.com/user-attachments/assets/1cb4868d-0fe0-4044-93e0-1d704e6aa3ef">
<img width="1133" alt="Screen shot 2024-08-15 at 13 17 01" src="https://github.com/user-attachments/assets/8687948f-4771-4f54-9605-9f7085560b4c">


**Expected result:**
<img width="1118" alt="Screen shot 2024-08-15 at 13 19 27" src="https://github.com/user-attachments/assets/6771124f-892b-4039-b767-a84eb968ba1d">
<img width="1070" alt="Screen shot 2024-08-15 at 13 19 36" src="https://github.com/user-attachments/assets/840edcca-1137-4dc2-9631-8e21e2dd65cd">

Example on the gitlab:

We can edit exactly in the description field
<img width="963" alt="Screen shot 2024-08-15 at 13 23 20" src="https://github.com/user-attachments/assets/f024eef4-8c05-4084-8b09-ab691fcb9ca7">

**Comment by TetianaKhomenko** [comment]
Hi @VitalikZ! The feature is implemented, you can see a short demo below. It will be published in the upcoming release 

https://github.com/user-attachments/assets/37e5f8a7-36b3-4e59-80a3-b1f9ea67527d

**Comment by iaza18** [comment]
https://docs.testomat.io/project/tests/#how-to-resize-attached-images-in-a-test-case
