### ISSUE TITLE
Showing Deleted user against each test cases in place of created user

### ISSUE THREAD

**Issue by prajapatimurli** [testomatio/app#1103]
**Describe the bug**
Showing Deleted user against each test cases in place of created user

**To Reproduce**
1. Make a Copy of Project
2. Copy some test cases in newly copied project from copied project
3. Click on Tests
4. Click on any test case and note the Created by section(see screenshot)

**Expected behavior**
It should display user name who created respective test cases

**Screenshots**
![Deleted_user](https://github.com/user-attachments/assets/d2a53cd9-a498-4cd5-baf1-bbdcf2f80434)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Browser Version 128.0.6613.36

**Comment by poliarush** [comment]
@littlefrontender is this backend?

**Comment by littlefrontender** [comment]
@poliarush yes, backend issue

**Comment by TetianaKhomenko** [comment]
Hi @prajapatimurli! Could you please check if user who created original test is a member of new copied project?

**Comment by TetianaKhomenko** [comment]
Hi @prajapatimurli! We renamed Deleted user to Unknown user. This fix will be published in the upcoming release.

 ![Image](https://github.com/user-attachments/assets/35ce9973-cf15-4bdd-9d81-9703a444cca0)
