### ISSUE TITLE
The total number of tests shown in the Groups Report, and combined report is not correct

### ISSUE THREAD

**Issue by SusanaAlves** [testomatio/app#1106]
Steps to reproduce: 

1. Have some manual runs previously run.
2. Create a group for a given release and add those existing runs. 
3. On Groups, click on the folder with your release. You will see that the number of tests passed is 0 instead of the sum of all the tests ran and passed. 
![Screenshot 2024-08-26 at 15 47 39](https://github.com/user-attachments/assets/1bb6d921-90ec-4ee1-a8fe-4c84d9c0fe71)
4. Click on the Combined Report button. The totals show 0. 
![Screenshot 2024-08-26 at 15 49 04](https://github.com/user-attachments/assets/e719b53d-9054-4929-92e6-d0eb34626cb3)

**Comment by SusanaAlves** [comment]
Hello, any update on this?

**Comment by TetianaKhomenko** [comment]
Hi @SusanaAlves! The fix should be live now. Could you please check it on your side?

**Comment by SusanaAlves** [comment]
Fixed here: 
![Screenshot 2024-09-12 at 12 51 16](https://github.com/user-attachments/assets/27e7c5a5-3dee-4227-a11c-6e4dbdc0cc51)

Not fixed in the combined report. The totals are still 0.
![Screenshot 2024-09-12 at 12 52 08](https://github.com/user-attachments/assets/17eceeef-c6df-43fd-9034-4c8c152ea384)

**Comment by SusanaAlves** [comment]
@TetianaKhomenko, the combined report has not been fixed. The totals are showing 0.

**Comment by TetianaKhomenko** [comment]
@SusanaAlves it's hard to understand the problem with small pieces of screen. You can share the whole screen screenshot here or in our Slack private channel

**Comment by SusanaAlves** [comment]
@TetianaKhomenko, here is a full screenshot: 
![Screenshot 2024-09-12 at 15 37 18](https://github.com/user-attachments/assets/4d952955-0960-4c1e-b1ca-fe0adafd4932)

Can you see that all the totals are 0 instead of showing the correct number of test cases in each status?

**Comment by TetianaKhomenko** [comment]
@SusanaAlves could you please show this run 

![CleanShot 2024-09-12 at 20 06 18@2x](https://github.com/user-attachments/assets/440b96e0-ecb1-4247-9723-7bb917c9dd96)

Overall I have the results. I assume it can be because test statuses are not shown for the second run.

Here is my example:

![CleanShot 2024-09-12 at 20 04 31@2x](https://github.com/user-attachments/assets/17b879d9-c1e3-4a2b-8504-ac989f3aa352)

**Comment by SusanaAlves** [comment]
I have these data: 
<img width="1405" alt="Screenshot 2024-09-13 at 13 31 46" src="https://github.com/user-attachments/assets/036f4eec-175f-4ab8-aa1e-ab227663bdc1">

<img width="1333" alt="Screenshot 2024-09-13 at 13 32 26" src="https://github.com/user-attachments/assets/8b9fc058-f347-4354-a482-d49834602972">

When I click on Combined report I can't see the totals being updated, even if I change the main Run: 
<img width="1412" alt="Screenshot 2024-09-13 at 13 33 13" src="https://github.com/user-attachments/assets/9f78934e-4201-4cc5-b773-56f4e8295463">

<img width="1419" alt="Screenshot 2024-09-13 at 13 34 17" src="https://github.com/user-attachments/assets/4fe5f17c-8165-4887-a59c-56dab4aece4a">

**Comment by littlefrontender** [comment]
@SusanaAlves Do you use branches? Or may be tests have different versions?

Please share screenshots both of runs on Report page
![Image](https://github.com/user-attachments/assets/a1ca3e86-5458-4893-b2b6-6ea19b149331)

**Comment by littlefrontender** [comment]
@SusanaAlves Your runs have different tests, none of them match, that's why the counters show 0.

**Comment by SusanaAlves** [comment]
@littlefrontender, that's true. The tests are different, but I thought a combined report would show all the totals. 
If I create a Group to group all the runs performed for a given release, it's very likely that the several runs will have different test cases, as we are testing new features and new tests were created. 
I thought that with the Combined report, I could see all the totals. Is that not possible, then? So, does the combined report just work if we have runs with the same tests?

**Comment by TetianaKhomenko** [comment]
Hi @SusanaAlves! Thanks for your explanation. Originally when Combined Report was designed it was meant to compare test results, but not combine. So please feel free to create a feature request on your suggestion.
