### ISSUE TITLE
Cannot archive terminated test run

### ISSUE THREAD

**Issue by tikolakin** [testomatio/app#1107]
**Describe the bug**
<img width="592" alt="image" src="https://github.com/user-attachments/assets/98ef0bb4-1141-49be-9c69-9471fa4d1ee5">

**Expected behavior**
User should be able to archive test run with any resolution

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin! Thanks for pointing this out. The improvement is live now

https://github.com/user-attachments/assets/8ac2d4ee-4134-4a63-9c06-896136095868
