### ISSUE TITLE
Terminated test run doesn't show counters

### ISSUE THREAD

**Issue by tikolakin** [testomatio/app#1108]
**Describe the bug**
<img width="1117" alt="image" src="https://github.com/user-attachments/assets/ea379e99-664e-4ac5-a3c0-0d7669bf367a">

**Expected behavior**
Counters are shown for any test run that has test results

**Additional context**
Counters are also not shown on the test runs list view

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin! The fix should be live now. Could you please check on your side?

**Comment by tikolakin** [comment]
Appreciate this fix. Looks good on our end

**Comment by tikolakin** [comment]
<img width="1270" alt="Screenshot 2024-09-12 at 12 48 14" src="https://github.com/user-attachments/assets/a0996818-71bb-488c-8a9b-2330f335135c">
63 in test run and 0 in total.
Does the fix affect historic runs?

**Comment by Fro0z1k** [comment]
Hello @tikolakin!
So, looks like fixed. Could you please recheck?

**Comment by poliarush** [comment]
@Fro0z1k is this on prod already?

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin! Thanks for reporting the issue. The fix is live now.

![CleanShot 2024-10-08 at 07 48 40@2x](https://github.com/user-attachments/assets/2e741886-c1e4-4b02-8423-5f704bf6a3a8)
