### ISSUE TITLE
Getting 422 on jira issue link

### ISSUE THREAD

**Issue by Gennadiii** [testomatio/app#1114]
**Preconditions**
Test case is not linked
**Describe the bug**
I'm sending POST to jira/issues to create a link. Case becomes linked but also I'm getting an error that it's already linked

**To Reproduce**
1. Create new test case
2. Send link query from public api
3. "error": "Jira issue already connected for Test 

**Expected behavior**
Case is linked with no errors

**Comment by TetianaKhomenko** [comment]
Hi @Gennadiii! The issue was fixed. Please reopen the ticket if the issue still persists.
