### ISSUE TITLE
While changing from Cucumber to another Project Framework in settings, the dropdown menu closes automatically

### ISSUE THREAD

**Issue by sashatigay** [testomatio/app#112]
While trying to change Project Framework to Cucumber and then to another Framework, the dropdown menu closes immediately. 

![Screen Recording ](https://user-images.githubusercontent.com/57132710/83523360-bd182480-a4ea-11ea-8eea-e2a892ee8690.gif)

**Comment by TetianaKhomenko** [comment]
fixed
