### ISSUE TITLE
TQL is difficult to write to extract test cases for 100 user stories 

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#1125]
**Description**

Users need to search multiple values for one search variable. It's not convenient for now, here is example:

`jira == 'LMP-100' or jira == 'LMP-104' or jira == 'LMP-144' or jira == 'LMP-214' or jira == 'LMP-219' or jira == 'LMP-220' or jira == 'LMP-257' or jira == 'LMP-214' or jira == 'LMP-290' or jira == 'LMP-520' or jira == 'LMP-307' or jira == 'LMP-309' or jira == 'LMP-510' or jira == 'LMP-511' or jira == 'LMP-523' or jira == 'LMP-545' or jira == 'LMP-546' or jira == 'LMP-539' or jira == 'LMP-55'`

**Expected**

`jira == ('LMP-100', 'LMP-104', 'LMP-144', 'LMP-214', 'LMP-219', 'LMP-220', 'LMP-257', 'LMP-214', 'LMP-290', 'LMP-520', 'LMP-307', 'LMP-309', 'LMP-510', 'LMP-511', 'LMP-523', 'LMP-545', 'LMP-546', 'LMP-539', 'LMP-55')`

or 

`jira in ['LMP-100', 'LMP-104', 'LMP-144', 'LMP-214', 'LMP-219', 'LMP-220', 'LMP-257', 'LMP-214', 'LMP-290', 'LMP-520', 'LMP-307', 'LMP-309', 'LMP-510', 'LMP-511', 'LMP-523', 'LMP-545', 'LMP-546', 'LMP-539', 'LMP-55']`

**Comment by TetianaKhomenko** [comment]
Implemented and published. 

![CleanShot 2024-09-25 at 09 42 22@2x](https://github.com/user-attachments/assets/c7b81007-f443-48b9-91a6-af60d9eba49a)

**Comment by maxkryvoshyya** [comment]
url: https://docs.testomat.io/usage/query-language/#multiple-values
