### ISSUE TITLE
Currently when re-launching a test run the updated time is incorrect.

### ISSUE THREAD

**Issue by vhd-lewis** [testomatio/app#1132]
**Describe the bug**
Currently when relaunching a test run the updated time is way long than it should be. My guess is it's working out the time from when the run was first started to when the run was then finished. 

**To Reproduce**

**Expected behavior**
When relaunching a run I would expect the run time to reflect as the original + the new launch total. Not the entire time between the relaunch also.

**Screenshots**

![image](https://github.com/user-attachments/assets/703e1218-2ce4-4538-8366-d2f2bdf3cba7)
![image](https://github.com/user-attachments/assets/4e2ec7bd-4485-4408-bea5-82c9e704e758)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser chrome

**Comment by poliarush** [comment]
@littlefrontender is this backend?

**Comment by vhd-lewis** [comment]
@Fro0z1k @littlefrontender Is there an estimated completion date for this?

**Comment by poliarush** [comment]
@vhd-lewis we will try to look at it in current release.

**Comment by vhd-lewis** [comment]
@poliarush Do you have an rough estimate when your planning the current release?

**Comment by poliarush** [comment]
nope we don't put exact esitmates here as we have common backlog and it will be processed once we're ready to pick up such priority tickets. however, we will try to fix it in next 1-2 weeks.

**Comment by trumenov** [comment]
launched_at, duration_tracked, add in table Execution time with Launched_at...Finished_at

**Comment by DavertMik** [comment]
![image](https://github.com/user-attachments/assets/15934f9b-e5bc-44db-ac11-25b8db52aaa4)
![image](https://github.com/user-attachments/assets/7c43a3dd-8c0c-420a-a1b7-67dfbb3a35ad)

**Comment by vhd-lewis** [comment]
Any update on this at all? Just as it's been 3 weeks.

**Comment by TetianaKhomenko** [comment]
Hi @vhd-lewis! Thanks for reporting the issue. The fix will be published in the upcoming release.
