### ISSUE TITLE
Breadcrumbs for RunGroups

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#1133]
**Is your feature request related to a problem? Please describe.**

Users have nested structure on the Runs page when organizing their Runs. 
Better navigation is needed.

**Describe the solution you'd like**

Add breadcrumbs for Run Groups

![CleanShot 2024-09-26 at 14 17 05@2x](https://github.com/user-attachments/assets/f537da22-6328-4d93-847a-ffc0ee678f8c)

**Comment by TetianaKhomenko** [comment]
@tikolakin please feel free to add any details.

**Comment by littlefrontender** [comment]
I have implemented breadcrumbs for Runs, but for Rungroups i need backend changes

**Comment by TetianaKhomenko** [comment]
need to improve this

https://github.com/user-attachments/assets/167bcf88-4062-4f9b-9a51-ca3db1bddf9b

**Comment by TetianaKhomenko** [comment]
implemented
