### ISSUE TITLE
Windows7-Edit Suite-Doesn't work button [Esc] Close

### ISSUE THREAD

**Issue by AvramenkoDmitry** [testomatio/app#114]
1. Open website https://app.testomat.io/
2.Choose Demo Project
3.Press on gamburger menu
4.Selcet Tests
5.In new page move right where says +New Suite and click it
6.In new tabs click Save
7.Select new page under todomvc-tests
8.In new tabs click Edit
9.Click button [Esc] close

EXPECTED RESULT- I can close Edit suite if i change my mind about it 

ACTUAL RESULT-I cannot close because button doesnt work,forstly i need save Suite even if i didn't change anything

![Screenshot_14](https://user-images.githubusercontent.com/66326439/83552166-016aeb00-a512-11ea-9f62-092ca772def6.png)

**Comment by TetianaKhomenko** [comment]
This issue appears occasionally on other pages with this type of Close button. Such type of window gets stuck and becomes able to close only after refresh.
