### ISSUE TITLE
info popup block the option to select different priority

### ISSUE THREAD

**Issue by kobishokron** [testomatio/app#1140]
**Describe the bug**
when trying to to select priority inside the test case windows, there is a popup (info popup) that block the option to select different priority 

**To Reproduce**
1. Go to any test case
2. Click on priority button 
3. try to click on the "normal" / "critical" etc.

**Expected behavior**
to be able select priority without  any problem

**Screenshots**
If applicable, add screenshots or video to help explain your problem.
![image](https://github.com/user-attachments/assets/cc06d33d-bc0b-4e1e-9120-75ee7d519cd2)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Browser Version:  129.0.6668.89
 - Application: production  

**Additional context**

https://github.com/user-attachments/assets/16585652-8ee4-4466-ae7f-b1107da63f50

**Comment by TetianaKhomenko** [comment]
Hi @kobishokron! Thanks for reporting the issue. The fix will be published in the upcoming release.
