### ISSUE TITLE
After autotests synchronization some test cases are missing the 'Description' tab

### ISSUE THREAD

**Issue by mykolakhy** [testomatio/app#1141]
**Describe the bug**
After performing the test cases synchronization with automated tests, some TCs are missing the 'Description' tab with preconditions and steps.

**To Reproduce**
1. Create manual test case
2. Sync it with automated test
3. Check 'Description' tab of test case in Testomat
4. The tab is missing

**Expected behavior**
After sync with automated tests, the 'Description' tab should not disappear

**Screenshots**
![Xnip2024-10-16_14-34-32](https://github.com/user-attachments/assets/4b2be11b-97a6-4e17-95bf-8256808f530f)

**Desktop (please complete the following information):**
 - OS: macOS 15.0.1 (24A348)
 - Browser Firefox 
 - Browser Version 131.0 (aarch64)
 - Application: production

**Additional context**
This bug happened with some of our test cases, we don't have clear and exact steps to reproduce it, as It was not discovered immediately.

**Comment by DavertMik** [comment]
I did some change to fix this

**Comment by TetianaKhomenko** [comment]
The issue was checked and verified as fixed. 
Fix will be published in the upcoming release.
