### ISSUE TITLE
shortcut.com integration

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#1143]
shortcut.com
- link test cases and test suites to shortcut ticket
- create defects from testomat.io to shortcut

**Comment by TetianaKhomenko** [comment]
update: 

- add the ability to create both stories and tasks (for task user have to enter story id)
- link shortcut project by `workflow id`

**Comment by Fro0z1k** [comment]
### Step 1: Sign In to Shortcut
Go to Shortcut and sign in with your account credentials.
If you don’t have an account, you’ll need to sign up for one.


### Step 2: Get Your API Token
After signing in, click on your profile picture in the lower-left corner.
Select Settings from the dropdown menu.
Scroll to the API Tokens section.
Click Generate New API Token if you don’t have one, or copy an existing token. This token is required for API requests to retrieve workflow information.

<img width="1311" alt="Screenshot 2024-11-14 at 09 04 14" src="https://github.com/user-attachments/assets/7a527ea3-377a-417d-9cdc-841d099c25d0">
<img width="876" alt="Screenshot 2024-11-14 at 09 06 45" src="https://github.com/user-attachments/assets/f89db3f7-855f-4d93-a87b-5a370bc55ed8">


### Step 3: Find workflow name
Now, you can use your API token to access the workflows in Shortcut.

<img width="1536" alt="Screenshot 2024-11-14 at 15 17 03" src="https://github.com/user-attachments/assets/4053b378-df34-4326-97fb-e310a1be6138">


<img width="696" alt="Screenshot 2024-11-14 at 11 58 42" src="https://github.com/user-attachments/assets/8c88c114-b866-4c0c-bb95-16c2edee2b5e">

<img width="736" alt="Screenshot 2024-11-14 at 11 58 52" src="https://github.com/user-attachments/assets/9a487df0-728a-4b40-a271-dc8cd8b93797">

**Comment by Fro0z1k** [comment]
Handling incorrect workflows names
<img width="713" alt="Screenshot 2024-11-14 at 15 11 33" src="https://github.com/user-attachments/assets/0e5f287c-cd57-4012-9b03-be96ec147083">
<img width="569" alt="Screenshot 2024-11-14 at 15 11 47" src="https://github.com/user-attachments/assets/61ba3bc3-21b5-44b4-ae9f-4c6816a4cdc6">

**Comment by maxkryvoshyya** [comment]
url: https://docs.testomat.io/integrations/issues-management/shortcut/
