### ISSUE TITLE
Add tooltip to the label if they have long text

### ISSUE THREAD

**Issue by 666f78** [testomatio/app#1145]
**Is your feature request related to a problem? Please describe.**
Long text are not showing on label

**Describe the solution you'd like**
After hovering showing tooltip

**Describe alternatives you've considered**
nope

**Additional context**
![image](https://github.com/user-attachments/assets/1e7b5566-cd3d-4ff7-8a7f-4d29638c6883)
![image](https://github.com/user-attachments/assets/e35c2212-7b36-493b-9e18-09d30d62431a)
![image](https://github.com/user-attachments/assets/2f3daa50-f346-4090-83e6-5aaf44622bbb)

**Comment by TetianaKhomenko** [comment]
Hi @666f78! Thanks for the feature request. This improvement will be published in the upcoming release.

![Image](https://github.com/user-attachments/assets/fbd742e6-8e20-4dc6-b579-6b42825c3e08)
