### ISSUE TITLE
No issue is created in jira from the /projects/nebula-web/runs page

### ISSUE THREAD

**Issue by karpinskayakarina** [testomatio/app#1155]
No issue is created in jira from the /projects/nebula-web/runs page

There are no errors in the network, only in the console "Uncaught TypeError: Cannot read properties of undefined (reading 'body')"

**Steps to reproduce:**
1. Go to https://app.testomat.io/projects/nebula-web/runs
2. Find a run that contains a failed test
3. Go to the report of the failed test
5. Go to the "Create New Issue" popup
6. Fill in all the required fields
7. Click on the Create Issue button

**Current result:**
1. A task is not created in jira
2. An error in the console
3. You can reproduce only from the page https://app.testomat.io/projects/nebula-web/runs

**Expected result:**
The ticket should be created successfully in jira

<img width="1283" alt="Знімок екрана 2024-10-30 о 16 44 52" src="https://github.com/user-attachments/assets/738239a3-de05-41ae-bfa7-7668dd186a28">

**Comment by littlefrontender** [comment]
CNR. @karpinskayakarina Please add Support User.

Project > Settings > Users> Extra menu > Invite support user
![Image](https://github.com/user-attachments/assets/b0e94d6f-52f7-4d75-9253-0f71f5b0d0e0)

**Comment by DavertMik** [comment]
Sorry, we can't reproduce without knowing more details on this
