### ISSUE TITLE
Runs TQL var for Custom Statuses

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#1157]
**Is your feature request related to a problem? Please describe.**

Need to introduce Runs TQL var for Custom Status

![image](https://github.com/user-attachments/assets/95984355-edc1-479d-9114-2be6f6ffa127)

**Comment by TetianaKhomenko** [comment]
implemented

**Comment by TetianaKhomenko** [comment]
please add ` has_custom_status` to https://docs.testomat.io/usage/query-language/#runs-variables

![CleanShot 2024-11-05 at 08 36 16@2x](https://github.com/user-attachments/assets/5ac0dedb-691f-4054-adb8-4ba44b441c3b)

**Comment by iaza18** [comment]
PR https://github.com/testomatio/docs/pull/232

**Comment by iaza18** [comment]
https://docs.testomat.io/advanced/tql/#runs-variables
