### ISSUE TITLE
Folder not created for manual tests

### ISSUE THREAD

**Issue by jkalandarov** [testomatio/app#1162]
**Describe the bug**
A folder for manual tests is not created

**To Reproduce**
1. Go to Tests
2. Click on + and select `Folder` option
3. Write a folder name in the `New Folder` sidebar
4. Click the `Save` button in the `New Folder` sidebar

**Expected behavior**
A new folder should be created under the `Manual` tab.

**Screenshots**

[d30acf73-55b0-42eb-8c78-a2816983217c.webm](https://github.com/user-attachments/assets/9111dcc0-5753-4aa0-99db-589f78a85186)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Browser Version: 130.0.6723.117
 - Application: production

**Comment by littlefrontender** [comment]
@jkalandarov @poliarush  I don't think this is a bug. You create an empty folder with no tests in it yet. The folder is created. When you click the “Manual” tab you filter by manual tests. However, there are no suites or tests in the folder yet.

https://github.com/user-attachments/assets/9fdbfccb-0097-4e68-bc4f-2ccdedef291b

**Comment by poliarush** [comment]
agreed, @jkalandarov please remove a "manual" filter and folder will be there, please create a few tests to see it under "manual" filter

**Comment by jkalandarov** [comment]
Removed manual filtered. The folder was among the features. As a user, I expected folders to be on top followed by features. Therefore, I could not find it initially. It'd be improved UX if you fixed that. Another thing: it is possible to have multiple folders with the same name which is not expected by a user.
