### ISSUE TITLE
Manual run: Make adjustable case description block

### ISSUE THREAD

**Issue by yvavilov** [testomatio/app#1167]
**Is your feature request related to a problem? Please describe.**
A lot of empty and unused space on the screen with case description within manual run.

**Describe the solution you'd like**
Make this block adjustable by dragging.

**Describe alternatives you've considered**
Make id adaptable to screen size.

**Additional context**
![image](https://github.com/user-attachments/assets/51ad1f19-b5f8-4aea-a579-b40fde018521)

**Comment by tikolakin** [comment]
I don't agree it´s a low priority for users. It's the main screen for testers
I feel like recently UX on testomatio is deprioritezed comparing to early days

**Comment by TetianaKhomenko** [comment]
@littlefrontender please add saving splitter position

**Comment by TetianaKhomenko** [comment]
Hi @yvavilov and @tikolakin! The feature is live now.

https://github.com/user-attachments/assets/5b8681d6-717c-4e25-b493-d833a7c1da58

**Comment by liudmylastepanets** [comment]
Kindly review my PR https://github.com/testomatio/docs/pull/231
