### ISSUE TITLE
Infinite loader on open run group

### ISSUE THREAD

**Issue by PetroOv** [testomatio/app#1173]
**Describe the bug**
When a run group contains a large number of runs (in my case, ~20k), Testomat cannot open the details. The request to GET api/{projectId}/rungroups/{runGroupId} lacks pagination, which leads to an infinite loader and performance issues.

**To Reproduce**
1. Go to runs page
2. Click on run group with 20k runs
3. Wait...

**Expected behavior**
Run group details loaded

**Desktop (please complete the following information):**
 - any env

**Comment by TetianaKhomenko** [comment]
Testomat version 0.5.34 self hosted

**Comment by TetianaKhomenko** [comment]
fixed be app version upgrade
