### ISSUE TITLE
Add option to Assign strategy to Mixed runs

### ISSUE THREAD

**Issue by OleksiiKho** [testomatio/app#1175]
AC
- Add option to choose Assign strategy to Mixed runs

Additional AC:
- Add option to assign people on creation of Mixed run (currently assign button available only when you open Mixed run to edit)

Overal expectation, Mixed run should have same Assign options as Manual run.

Thank you.

![Screenshot 2024-12-04 at 3 30 54 PM](https://github.com/user-attachments/assets/4e4603e5-5b4d-4e38-8c34-04ee9201f6de)
![Screenshot 2024-12-04 at 3 31 04 PM](https://github.com/user-attachments/assets/7e662ef9-bac3-4e66-b92f-75fc0c6c9e48)
![Screenshot 2024-12-04 at 3 31 18 PM](https://github.com/user-attachments/assets/2a575b03-42e7-48f6-a972-fb96c4bc5498)

**Comment by TetianaKhomenko** [comment]
Hi @OleksiiKho! Thanks for the request. We've added an option to assign users for mixed-run 

![Image](https://github.com/user-attachments/assets/8275b66f-0926-4d08-a37c-a51926e51274)
