### ISSUE TITLE
Bulk edit on 42 suits with 142 tests leads to Mysql2::Error: Deadlock

### ISSUE THREAD

**Issue by OleksiiKho** [testomatio/app#1176]
**Describe the bug**
Bulk edit on 42 suits with 142 tests leads to Mysql2::Error: Deadlock

Note: Can't reproduce if do same action in portions, edit 30% at one time.

**To Reproduce**
1. Go to 'Test' / Manual
2. Click on 'Multi Select'
3. Select all tests (42 suits in our case)
4. Add label via bulk edit

**Actual behavior**
Error is displayed:
"Mysql2::Error: Deadlock found when trying to get lock; try restarting transaction"
Operation not successful, labels not assigned.
POST https://app.testomat.io/api/doxy-me-og-v2-project/labels/automatable-aa5e7/link 400 (Bad Request)

**Expected behavior**
Label assigned to all selected tests and suits

**Desktop (please complete the following information):**
 - OS: [MacOS 15.1.1]
 - Browser [Chrome]
 - Browser Version [131]
 - Application: [production probably, don't see beta labels] 
![Screenshot 2024-12-04 at 3 44 46 PM](https://github.com/user-attachments/assets/8e4afbb9-d93b-41de-bb91-ad761a0e7aed)

**Comment by DavertMik** [comment]
Fixed on production

**Comment by TetianaKhomenko** [comment]
Hi @OleksiiKho! Thanks for reporting the issue. It was fixed. Please re-open the ticket if it occurs again.
