### ISSUE TITLE
upload is hanging on 50% when upload 35 mb gif image

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#118]
![image](https://user-images.githubusercontent.com/325722/83570558-8bbd4a00-a526-11ea-9f14-ea3fffe23090.png)

**Comment by koushikmohan1996** [comment]
![image](https://user-images.githubusercontent.com/24666922/85272098-578bd800-b499-11ea-80ad-800578dc409d.png)
Getting this error in beta but works in local.

@DavertMik May be we have to increase the size limi

**Comment by poliarush** [comment]
I think we should limit to 5 MB per attachment per test case

**Comment by poliarush** [comment]
@DavertMik please confirm

**Comment by koushikmohan1996** [comment]
@poliarush You canot upload larger files hereafter

**Comment by poliarush** [comment]
what is current limit?

**Comment by koushikmohan1996** [comment]
Its 5mb per file

**Comment by poliarush** [comment]
ok
