### ISSUE TITLE
Created at/updated at is not displayed for automated (sync) tests

### ISSUE THREAD

**Issue by tikolakin** [testomatio/app#1186]
**Describe the bug**
Created at/updated at is displayed for manual tests (also, it's not consistent, some test have it but others don't)
<img width="1123" alt="image" src="https://github.com/user-attachments/assets/f8ee2a99-4bb7-4a81-8626-2ca223202ce6" />

It's missing on the automated tests that a sync from code to testomatio

**Comment by poliarush** [comment]
@tikolakin please show screenshoot

**Comment by tikolakin** [comment]
Hi @poliarush , I added it

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin! The issue should be fixed now.

![Image](https://github.com/user-attachments/assets/0af12f4a-08bf-476f-b59a-9c21d20d7915)
