### ISSUE TITLE
Currently not able to add new Test Cases to existing test runs

### ISSUE THREAD

**Issue by vhd-lewis** [testomatio/app#1189]
**Is your feature request related to a problem? Please describe.**
Currently not able to add new Test Cases to existing test runs

**Describe the solution you'd like**
The ability to add test cases to existing test runs

**Comment by TetianaKhomenko** [comment]
@vhd-lewis please try the Edit option and let us know if it works for you. Attaching screenshots below.

![CleanShot 2024-12-19 at 06 52 27@2x](https://github.com/user-attachments/assets/3b023b37-8669-424c-a28f-2af30e90df04)

![CleanShot 2024-12-19 at 06 53 11@2x](https://github.com/user-attachments/assets/caac81fb-1aff-4080-a024-bb74beb68869)

**Comment by TetianaKhomenko** [comment]
Also, you can use merge option to merge few runs into one https://docs.testomat.io/project/runs/managing-runs/#merge-runs

**Comment by vhd-lewis** [comment]
@TetianaKhomenko 
Sorry where is the edit option?
![Uploading Screenshot 2024-12-19 at 11.00.22.png…]()

**Comment by TetianaKhomenko** [comment]
@vhd-lewis the image didn't upload, please attach it again

**Comment by vhd-lewis** [comment]
![Screenshot 2024-12-19 at 11 00 22](https://github.com/user-attachments/assets/320a230f-b357-4709-bf30-9308b917d57a)

**Comment by TetianaKhomenko** [comment]
For Runs that have been finished, you can use the Relaunch option and then Edit. Attaching video below

https://github.com/user-attachments/assets/b0cfb05b-f0d7-42a1-aaa7-936badced0b7

**Comment by vhd-lewis** [comment]
Thank you so much for this make sense :)

**Comment by TetianaKhomenko** [comment]
No problem ;) Glad to help
