### ISSUE TITLE
"Remove invitation" button does not prevent user from joining the project

### ISSUE THREAD

**Issue by sashatigay** [testomatio/app#129]
1. Click "Remove" button to the right of the user's name
2. Refresh the page
3. Click "Remove invite" button to the right of the user's name
4 Refresh the page
5. Check the e-mail box of the invited user's account
6. Open an invitation e-mail
7. Click "Open Project" button

    Actual result: the "Remove invitation" button does not prevent user from joining the project via the link in the invitation e-mail and the user can successfully join the project
.
    Expected result: After clicking "Remove invitation", the user can not join the project 

Environment: Win 10, Chrome v 83.0.4103.97, Firefox v 77.0.1

**Comment by koushikmohan1996** [comment]
Released in beta
