### ISSUE TITLE
API key is invalid while importing tests from PC directory

### ISSUE THREAD

**Issue by sashatigay** [testomatio/app#130]
1. Go to "Import project" in settings
2. Select framework and language
3. Copy given command
4. Open cmd
5. Go to the project direcory
6. Run the command copied from settings

    Expected result: the tests are imported to testomat.io
    Actual result: API key is invalid, the tests are not imported

Environment: Win 10
![image](https://user-images.githubusercontent.com/57132710/83771054-8416b600-a68a-11ea-9bda-fa7efeaf1cbb.png)

**Comment by poliarush** [comment]
TESTOMATIO_URL=https://beta.testomat.io/api/load  should be added as environment variable
