### ISSUE TITLE
Allow using the reporter only when running tests in the CI

### ISSUE THREAD

**Issue by andreasciamanna** [testomatio/app#131]
At the moment, to allow sending the tests report to Testomat.io, we need to set the `TESTOMATIO` variable with the key, and add, for Jest, the estimation reporter to the default ones.

I can't expect all the devs to know that they must set this variable when they want to run JEst tests.
And if they don't do that, they will get a nice error.

Instead, I would prefer to send the test reports only when running from the CI, where I can define `TESTOMATIO` as an environment (and secure) variable.

I think this could be achieved if the reporter could be specified (with something like `jest --reporters="testomat"`).

For the time being, I've created an exact copy of `jest.config.js`, with a different name and just the added reporters configuration.

By doing that, I can call `npx jest -c jest.testomat.config.js` from the CI (GitLab CI, where I have `TESTOMATIO` set as an environment variable for the project).

I hope this makes sense :)

Thanks!

**Comment by DavertMik** [comment]
Thanks, @andreasciamanna 
That makes sense - as you are using "js" format of Jest config you can probably enable/disable that config option inside the config file itself, for instance by detecting CI environment variable:

```js
// inside jest.config.js
if (process.env.CI) {
  module.exports.reporters = ['default', ['./node_modules/@testomatio/reporter/lib/adapter/jest.js', { apiKey: process.env.TESTOMATIO }]],
}
```
sorry, not tested, but probably you got the idea.

CI environment variable may be different depending on CI system you use

**Comment by andreasciamanna** [comment]
@DavertMik that makes even more sense! :)

I used to have the Jest configuration inside the package.json, but in order to add the `{ apiKey: process.env.TESTOMATIO }` part, I had to move it to its own JS file.

I didn't think of doing what you're suggesting, which is the most obvious thing :)

I'm considering this as resolved.
