### ISSUE TITLE
Simplify tests synchronization

### ISSUE THREAD

**Issue by andreasciamanna** [testomatio/app#133]
I've testing Testomat with a suite of 250+ tests.

I'm now supposed to edit each test by adding a unique identifier, which is different for each test.

This is a bit cumbersome requirement which I believe could be fixed with some automation.

I suppose the reporter (I'm using Jest) would not be able to automatically edit the file, but maybe a different tool could be written so it can do that when running the tests.

Something similar to what happens when a snapshot fails to test and an option to update them is provided, but this one would update the test themselves.

In any case, in the current state which requires manual edit, I doubt I would ever dare to ask the developers to add these unique IDs in all existing tests or every time a new test is imported :)

Thanks.

**Comment by poliarush** [comment]
In fact, you can import all your tests and execute them, it should be matched by test names.
No extra work should be done. However there may be a case where names are different in testomat.io and source but tests should be matched than ID should be used.

**Comment by DavertMik** [comment]
Yes, just as @poliarush said - if you won't update test, you can leave things as they are. 

But if you update a test, either rename it, or move it, you can append a Test ID into it for proper matching.

Anyway, there is no requirement to add ids manually to all tests. Reporter and tests uploading will work without it

**Comment by andreasciamanna** [comment]
Sound good!

At the moment, looking at the imported tests, I see we could improve some descriptions and names, so I was tempted to change them from the web interface until I saw that warning.

But indeed, if I can change them from the web interface I can also add the missing ID in the code :)

Thanks!
