### ISSUE TITLE
Windows7-Import Tests-Error when importing tests from directory

### ISSUE THREAD

**Issue by AvramenkoDmitry** [testomatio/app#140]
1.Go to "Import Tests" in settings
2.Select framework and language
3.Copy given command
4.Open cmd 
5.Go to the project direcory
6.Run the command copied from settings

Expected result: The tests are imported to testomat.io

Actual result: Data is being reset and the page is not available.

![photo5965368575671775593](https://user-images.githubusercontent.com/66326439/83899284-de824600-a760-11ea-9f93-4b0571475b8d.jpg)

**Comment by poliarush** [comment]
@AvramenkoDmitry please clarify your configuration settings

**Comment by poliarush** [comment]
@DavertMik please take a look, @koushikmohan1996 please check it on windows importing

**Comment by DavertMik** [comment]
According to error the endpoint (URL to which request is sent) is wrong.

Do you import to production or staging?

**Comment by poliarush** [comment]
it should be TESTOMATIO_URL=https://beta.testomat.io/api/load

**Comment by poliarush** [comment]
@AvramenkoDmitry please share command you are executing

**Comment by AvramenkoDmitry** [comment]
[Screen Recording (05.06.2020 23-43-54).zip](https://github.com/testomatio/app/files/4738448/Screen.Recording.05.06.2020.23-43-54.zip)

**Comment by DavertMik** [comment]
@AvramenkoDmitry 
yeah, we didn't have a chance to prepare proper commands for beta server. So for Windows this must be the following:

```
set TESTOMATIO_URL=https://beta.testomat.io/api/load && set TESTOMATIO=xxx && npx ...
```
so just like in your second video, but with && after `set TESTOMATIO_URL=` and before next `set` command

**Comment by poliarush** [comment]
@AvramenkoDmitry please confirm it's working fine on your side

**Comment by poliarush** [comment]
@DavertMik do they need to use `set TESTOMATIO_URL=https://beta.testomat.io/api/load` for execution ?

**Comment by AvramenkoDmitry** [comment]
I could not start with &&, but i can start I started by typing commands line by line.
Like this:
set TESTOMATIO_URL=https://beta.testomat.io/api/load
set TESTOMATIO=r0x.....
npx check-tests@latest CodeceptJS "**/*{.,_}{test,spec}.js"

**Comment by poliarush** [comment]
@koushikmohan1996 please check `&&` is working fine on windows, however, I understand it should be fine, just double-checking
