### ISSUE TITLE
fix tags placement in scenario editor for CoffeeMachine project

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#15]
![image](https://user-images.githubusercontent.com/325722/81820648-2d0d3d80-9531-11ea-8176-546901252779.png)

**Comment by DavertMik** [comment]
@poliarush try to delete all suites and reupload coffeemachine project

**Comment by poliarush** [comment]
is it codeceptjs-cucumber project?

**Comment by koushikmohan1996** [comment]
> is it codeceptjs-cucumber project?

@poliarush Yes
