### ISSUE TITLE
fix description during test import for codeceptjs+cucmber project to understand where feature folder is

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#16]
![image](https://user-images.githubusercontent.com/325722/81822433-6181f900-9533-11ea-9b4a-be59b0700cb5.png)

**Comment by koushikmohan1996** [comment]
@poliarush Can you please provide some more details

**Comment by poliarush** [comment]
Need to write description about -d feature .
features should be folder where feature files are located.
It's not informative and later there is message in CLI no tests found

**Comment by TetianaKhomenko** [comment]
the issue is fixed 

![image](https://user-images.githubusercontent.com/77803888/129528106-425bffdf-f2fa-4ed0-975f-2d6e8f14787e.png)
