### ISSUE TITLE
unclear aim of last record in revision

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#160]
![image](https://user-images.githubusercontent.com/325722/85069893-2b303d00-b1b5-11ea-805b-e194c1e823a8.png)
![image](https://user-images.githubusercontent.com/325722/85069908-31beb480-b1b5-11ea-8f18-bc5f2cadcc86.png)
![image](https://user-images.githubusercontent.com/325722/85069918-371bff00-b1b5-11ea-9cc0-32c9e90ac820.png)

**Comment by poliarush** [comment]
@koushikmohan1996 please check it

**Comment by poliarush** [comment]
please do different actions on editing scenarios 2-3 times, check last history actions it's representing actual changes.

![image](https://user-images.githubusercontent.com/325722/85421198-70b58700-b574-11ea-9ae1-00fc4f1b26cd.png)

![image](https://user-images.githubusercontent.com/325722/85421241-7f9c3980-b574-11ea-888a-635fab582a2f.png)

![image](https://user-images.githubusercontent.com/325722/85421259-84f98400-b574-11ea-9abb-461175f1e6b7.png)

![image](https://user-images.githubusercontent.com/325722/85421280-8b87fb80-b574-11ea-869c-bb836cccf5a3.png)

![image](https://user-images.githubusercontent.com/325722/85421305-92167300-b574-11ea-8363-e1cd52c9a1c3.png)

![image](https://user-images.githubusercontent.com/325722/85421324-98a4ea80-b574-11ea-9a93-c4cb9bd7bea0.png)

![image](https://user-images.githubusercontent.com/325722/85421354-9f336200-b574-11ea-9db1-ba5945d4d42b.png)

![image](https://user-images.githubusercontent.com/325722/85421379-a65a7000-b574-11ea-9e49-6b8b23a591dc.png)

**Comment by TetianaKhomenko** [comment]
fixed
