### ISSUE TITLE
"Synchronize Test by ID" is displayed for already synced test

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#163]
![image](https://user-images.githubusercontent.com/325722/85074901-9b42c100-b1bd-11ea-88f0-dcb437439748.png)
![image](https://user-images.githubusercontent.com/325722/85074915-a3026580-b1bd-11ea-9ffc-f2ae55671c84.png)
![image](https://user-images.githubusercontent.com/325722/85075039-c9280580-b1bd-11ea-8302-b825ccd400ef.png)

![image](https://user-images.githubusercontent.com/325722/85074940-aa297380-b1bd-11ea-8620-2d9663e7a6f1.png)

**Comment by koushikmohan1996** [comment]
Fixed in beta
