### ISSUE TITLE
3 tests are missed during jest project importing

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#165]
1. created purely new project
2. did jest import first time
3. 3 tests were missed

![image](https://user-images.githubusercontent.com/325722/85078610-1491e200-b1c5-11ea-99c2-5c54ef77bfd4.png)

![image](https://user-images.githubusercontent.com/325722/85078661-33907400-b1c5-11ea-810c-b02107516f16.png)

![image](https://user-images.githubusercontent.com/325722/85078670-38edbe80-b1c5-11ea-8833-e610af7f4e89.png)

![image](https://user-images.githubusercontent.com/325722/85078746-65a1d600-b1c5-11ea-98b1-2f03ccb9c7d3.png)

![image](https://user-images.githubusercontent.com/325722/85078645-26738500-b1c5-11ea-9a3e-06c07c119ccc.png)

**Comment by koushikmohan1996** [comment]
@poliarush Updated the project now. You can test it.

**Comment by poliarush** [comment]
yep, it works now
