### ISSUE TITLE
Search doesn't work for numeric tags

### ISSUE THREAD

**Issue by sashatigay** [testomatio/app#167]
**Steps to reproduce the behavior:**
1. Create a suit;
2. Add a numeric tag to the title (a.g. @123);
3. Search for this tag. 

**Actual result**
The test suit is not found:

**Expected result**
The test suit is found

**Screenshots**
![image](https://user-images.githubusercontent.com/57132710/85123805-915aa580-b231-11ea-802c-b469ead7969e.png)
![image](https://user-images.githubusercontent.com/57132710/85123869-a9cac000-b231-11ea-9cdc-edd0f264f600.png)

**Desktop:**
- OS: Win 10
- Browser: Chrome
- Browser Version: 83.0.4103.106
- Application: beta

**Additional context**
Though it can be found if you type "@123"
![image](https://user-images.githubusercontent.com/57132710/85123998-ded71280-b231-11ea-9f54-9fb9d9dec745.png)

**Comment by poliarush** [comment]
@sashatigay search by text is starting from 3 letters so you need to type something more, however, I would I agree we need to show some hint to help the user understand this behavior

**Comment by DavertMik** [comment]
Done!
