### ISSUE TITLE
no given, when, then filters for bdd steps in steps database

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#169]
- create new project codecept,js + bdd
- import tests from examples projects

![image](https://user-images.githubusercontent.com/325722/85212231-112b6180-b351-11ea-8829-9a4aa4049f49.png)

![image](https://user-images.githubusercontent.com/325722/85212237-22746e00-b351-11ea-8d04-5224d2191211.png)

**Comment by koushikmohan1996** [comment]
@poliarush This is fixed and released beta
