### ISSUE TITLE
edit templates doesn't work

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#17]
no action is done during clicking on edit button

![image](https://user-images.githubusercontent.com/325722/81822990-161c1a80-9534-11ea-9fec-10270bb97ead.png)

**Comment by koushikmohan1996** [comment]
Fixed a week before 

![template_edit](https://user-images.githubusercontent.com/24666922/82812767-57f07d80-9eb1-11ea-9ca4-810dad5130c4.gif)
