### ISSUE TITLE
can't execute codecept.js + bdd example project

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#170]
![image](https://user-images.githubusercontent.com/325722/85212337-eee61380-b351-11ea-8720-13a4ea9e0f5a.png)

![image](https://user-images.githubusercontent.com/325722/85212360-2f459180-b352-11ea-949c-09c455ba1ee7.png)

**Comment by koushikmohan1996** [comment]
@poliarush Make sure you installed node packages using `npm i`. Since every users have their project installed we did not mention that step

**Comment by poliarush** [comment]
@DavertMik demo project should be fixed, also there should be message somewhere that some dependency is not loaded please run `npm i`
