### ISSUE TITLE
error on detailed report in test runs tabs for w.io example project

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#171]
- create wdio example project
- run tests
- go to any test
- open test runs tab

![image](https://user-images.githubusercontent.com/325722/85212534-0e7e3b80-b354-11ea-8f98-6a05efb3f496.png)

**Comment by koushikmohan1996** [comment]
@poliarush Its not an error. This is the message of error that occurred while executing the test. We are showing that to user.

**Comment by koushikmohan1996** [comment]
Btw, I think the error occurred because packages are not installed. Try `npm i` and run the test

**Comment by poliarush** [comment]
@DavertMik what resolution is here?

**Comment by TetianaKhomenko** [comment]
@poliarush for now this message is quite understandable. Can we close this ticket?

![CleanShot 2022-05-02 at 17 48 12@2x](https://user-images.githubusercontent.com/77803888/166254858-fb15c689-e68e-451c-8f51-75184ab60ad3.jpg)
