### ISSUE TITLE
newly created step in steps database is not displaying "used in tests"

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#172]
![image](https://user-images.githubusercontent.com/325722/85212620-ecd18400-b354-11ea-9176-c9ee3984b431.png)

![image](https://user-images.githubusercontent.com/325722/85212623-f65aec00-b354-11ea-8e76-7e72f39cbba7.png)

![image](https://user-images.githubusercontent.com/325722/85212630-fe1a9080-b354-11ea-9ce5-1ab2a02111b5.png)

**Comment by poliarush** [comment]
or it's reproduced in bdd flow

![image](https://user-images.githubusercontent.com/325722/85212660-43d75900-b355-11ea-8a63-ec8c7b1d58d1.png)

![image](https://user-images.githubusercontent.com/325722/85212670-50f44800-b355-11ea-884e-a0b522746c4f.png)

**Comment by koushikmohan1996** [comment]
@poliarush Change in `scenario draft` is not considered as usage. since it is not used in code. Do we have to consider them too?

**Comment by DavertMik** [comment]
I fixed this usage. Current workflow:

In BDD project

* until step is loaded from source code it is considered draft
* draft step is not used in test - that's true, you can't really use step without implementing it first
* we display message for draft test about that

In Classical project

* no draft tests at all
