### ISSUE TITLE
Open test file for test view does not work

### ISSUE THREAD

**Issue by koushikmohan1996** [testomatio/app#185]
Should include branch detail in the URL like `tree/master`

<img width="675" alt="Screenshot 2020-08-25 at 11 46 01 AM" src="https://user-images.githubusercontent.com/24666922/91130004-8eb07c80-e6c8-11ea-90e9-723c41711e52.png">

**Comment by DavertMik** [comment]
I added mention of this into documentation and a hint to all fields wherever URL is set
