### ISSUE TITLE
"Error not found" in runs view

### ISSUE THREAD

**Issue by koushikmohan1996** [testomatio/app#188]
<img width="1440" alt="Screenshot 2020-08-25 at 12 02 39 PM" src="https://user-images.githubusercontent.com/24666922/91132774-e819ab00-e6ca-11ea-8f6a-d98ed87705e0.png">

In network  `/users/1` call fails

**Comment by koushikmohan1996** [comment]
More info. the issue occurs if the test is run by someone else or automated tests as there is no API to get user. Fixing this

**Comment by TetianaKhomenko** [comment]
fixed
