### ISSUE TITLE
Settings: framework & language change

### ISSUE THREAD

**Issue by DavertMik** [testomatio/app#19]
Currently we have framework & lang listed under "Project" section
There should be a way to change them there but by default, this feature should be locked.

When framework or lang is changed user should be warned that their templates will be replaced
Whan user changes from gherkin or to gherkin - they should be notified that project goes to BDD structure and this will affect the UI as well as current templates

Also we should remove changing of framework/lang in "Import" once tests are imported. 
User should be taken to Settings/Project instead

**Comment by koushikmohan1996** [comment]
![project_settings](https://user-images.githubusercontent.com/24666922/82438028-0792ad80-9ab6-11ea-8513-d137e677edcb.gif)

**Comment by koushikmohan1996** [comment]
![framework_change](https://user-images.githubusercontent.com/24666922/82438343-87207c80-9ab6-11ea-8c08-8a8704343cad.gif)
