### ISSUE TITLE
Search and filter area UI broke for project with long title

### ISSUE THREAD

**Issue by koushikmohan1996** [testomatio/app#190]
<img width="1374" alt="Screenshot 2020-08-26 at 12 56 05 PM" src="https://user-images.githubusercontent.com/24666922/91273998-aefd3b80-e79b-11ea-952e-205874ddbb8a.png">

**Comment by DavertMik** [comment]
![image](https://user-images.githubusercontent.com/220264/94319085-8e8af180-ff92-11ea-9866-f85615066470.png)

**Comment by DavertMik** [comment]
Fixed
