### ISSUE TITLE
Skipped tests are not reported in Automated Run

### ISSUE THREAD

**Issue by puneet0191** [testomatio/app#192]
**Describe the bug**
Skipped tests are being Ignored on Automated Tests run for Codeceptjs v2.6.5

**To Reproduce**
1. Run Automated tests
2. See Run Report
3. Skipped tests are shown in Green as passed. 

**Expected behavior**
Tests which is skipped should be marked Yellow and Shown Correctly. 

**Screenshots**
![image](https://user-images.githubusercontent.com/3048593/94284144-971e0080-ff6f-11ea-8ba9-edf4adc9006e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS, Linux
 - Browser chrome

**Comment by DavertMik** [comment]
I think this might be issue of CodeceptJS
@koushikmohan1996 could you take a look on it?

**Comment by DavertMik** [comment]
I will try to fix the design. This is not a thing that long tests look that ugly on 2 lines

**Comment by koushikmohan1996** [comment]
@puneet0191 Skipped event is not added in codecept reporter will fix it

**Comment by TetianaKhomenko** [comment]
fixed
