### ISSUE TITLE
Layout for Each Test Run detail is Broken

### ISSUE THREAD

**Issue by puneet0191** [testomatio/app#193]
Looking from chrome Version 85.0.4183.102 (Official Build) (64-bit)

OS: Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/3048593/94284317-d2203400-ff6f-11ea-8cf8-9c3c417e1f7c.png)

**Comment by DavertMik** [comment]
Thanks! I will work on it

**Comment by DavertMik** [comment]
Fixed. I hope this is now ok

![image](https://user-images.githubusercontent.com/220264/94315466-37cde980-ff8b-11ea-8ecd-df8b6d03d8a1.png)
