### ISSUE TITLE
Automated Run View could actually have a manual Refresh Button 

### ISSUE THREAD

**Issue by puneet0191** [testomatio/app#195]
**Is your feature request related to a problem? Please describe.**
The current way it works is, we have to reload the entire page to refresh to see live runs, it would be great if we can actually have a refresh button/icon right in the portal to do it and it brings up current running jobs.

**Comment by DavertMik** [comment]
Instead of Refresh button we should better have auto-update

![statuses-update](https://user-images.githubusercontent.com/220264/94458790-181f0700-01bf-11eb-9662-d1ef3077db91.gif)

**Comment by DavertMik** [comment]
deployed to production
