### ISSUE TITLE
The Side Panel could actually use some tooltips

### ISSUE THREAD

**Issue by puneet0191** [testomatio/app#196]
**Is your feature request related to a problem? Please describe.**
When we login into the portal and open any project, we have this side panel which looks something like this: 

![image](https://user-images.githubusercontent.com/3048593/94331943-5c0ee200-ffee-11ea-97ad-76bdad1130e9.png)

As a First time user, if I hover over any icon, I expect to see a tooltip reading what the icon means, it would be a good user experience to show them what the icon is meant for when they hover.

**Comment by DavertMik** [comment]
Thank you! Just added this

![image](https://user-images.githubusercontent.com/220264/94350368-50ef9c80-0056-11eb-9ef4-de3de10789ec.png)
