### ISSUE TITLE
Expanding the Side Toolbar Panel, trying to move it back to normal way is confusing

### ISSUE THREAD

**Issue by puneet0191** [testomatio/app#197]
**Is your feature request related to a problem? Please describe.**
When we expand the sidebar Panel, it opens up something like this

![image](https://user-images.githubusercontent.com/3048593/94331990-b14af380-ffee-11ea-99b2-e2bbe97ca1cd.png)

Now to move it back, it is actually confusing because if you observe on top we have X button which seems like it will close the side panel altogether, while on the bottom of this panel we have an Arrow pointing < which seems like it is the icon that they can close the expanded panel with, but in reality that icon is < is to go back to Project view, this is really confusing for me. 

We could improve it with Show something like an exit Icon to move back to Projects view and < to close the expanded side panel.

**Comment by DavertMik** [comment]
This is the best what I can do here. We already use "Exit" button for sign out. While left arrow is for "Back".

![image](https://user-images.githubusercontent.com/220264/94350542-d58eea80-0057-11eb-8a34-78fbb5cb141d.png)

**Comment by DavertMik** [comment]
I deployed the last changes. Please tell if the updated design is better

**Comment by puneet0191** [comment]
Thanks a lot!
