### ISSUE TITLE
Option to rename the runs, so we can have custom names with Date/Run Type etc.

### ISSUE THREAD

**Issue by puneet0191** [testomatio/app#198]
**Is your feature request related to a problem? Please describe.**
Could we have an option to rename the Automated Runs, so we could add custom information for our runs and then see them later, currently it seems like this option is not in our control and we can't really differentiate which run was which?

In our case we would like to use PR information, Job Information to be added to these runs, so we can check which PR failed, which job failed how.

**Comment by DavertMik** [comment]
![image](https://user-images.githubusercontent.com/220264/94380167-13b20a00-013d-11eb-897a-d629daa6ed66.png)

Implemented. Should be released soon!

**Comment by DavertMik** [comment]
You can also set run title when executing tests:

https://github.com/testomatio/reporter#naming-report
