### ISSUE TITLE
Show latest statuses of a test

### ISSUE THREAD

**Issue by DavertMik** [testomatio/app#199]
**Is your feature request related to a problem? Please describe.**

To see which tests are currently passing and which are not we need to show statuses of those tests in a list

**Describe the solution you'd like**
We need to stare a cached status of 5 last test runs of each test. And display this status in a list

**Solution**

* Create new field *run_statuses* to Test which must be stored of array (or string with comma split values)
* On each test run run_statuses of a Test must be updated

So a test can be displayed like this:

![image](https://user-images.githubusercontent.com/220264/94607626-d49ec880-02a4-11eb-9a28-146dc953aaa6.png)

**Comment by TetianaKhomenko** [comment]
implemented
