### ISSUE TITLE
Codeception: Setup page wording and docs links are wrong

### ISSUE THREAD

**Issue by cebe** [testomatio/app#200]
**Describe the bug**

When creating a project with codeception integration, the docs page:

![Bildschirmfoto von »2020-10-01 19-56-06«](https://user-images.githubusercontent.com/189796/94845576-2e77cd80-0420-11eb-9193-a0bd32f44d54.png)

has the following issues.

- "Install the **npm** package"  should be "Install the **composer** package"
- " Check documentation for more options. " points to https://github.com/testomatio/reporter while it should point to  https://github.com/testomatio/php-reporter

**Desktop**
 - Application: app.testomat.io

**Comment by DavertMik** [comment]
Thank you! 
Everything else is very NodeJS so some words left there

**Comment by TetianaKhomenko** [comment]
fixed
