### ISSUE TITLE
Error when linking Jira Issue to test

### ISSUE THREAD

**Issue by jmychasiw** [testomatio/app#207]
**Describe the bug**
The function  **Link a Jira issue** to a test will fail with message `undefined method `public_uid' for nil:NilClass`

**To Reproduce**
1. Add Jira link to project
2. Test Jira project is successful
3. Goto test with no Jira ID 
4. Add Issue ID
5. Hit Save
6. See error `undefined method `public_uid' for nil:NilClass`

**Expected behavior**
I expected to see a success message along new Jira linking functionality

**Screenshots**
![image](https://user-images.githubusercontent.com/30160288/105791946-6a451e80-5f4c-11eb-9005-6354827639ae.png)

Additional error when Hitting sync jira issue
![image](https://user-images.githubusercontent.com/30160288/105792077-9c568080-5f4c-11eb-844d-0f25eb2f4fa0.png)

**Desktop (please complete the following information):**
 - OS: [OSX]
 - Browser [chrome]
 - Browser Version [87]
 - Application: [production or beta] 

**Additional context**

**Comment by poliarush** [comment]
did you successfully configure jira project in settings?

**Comment by poliarush** [comment]
@DavertMik please check this out

**Comment by thebaddeveloper** [comment]
Yes. I configured 3 jira projects to one test project.
For each one I can hit the TEST button and it reports successfully.

**Comment by poliarush** [comment]
@jmychasiw it should be fixed in latest release. Please try
