### ISSUE TITLE
Successful import throws error in testomat 

### ISSUE THREAD

**Issue by natkrish** [testomatio/app#210]
**Describe the bug**
I did an import from my existing automated test into testomat, however the import failed for first 3 attempts but passed the last import. 

**To Reproduce**
1. Import any framework test to testomat
2. Make sure you have some conflict so that testomat error is triggered
3. Resolve the conflict and re-import it 
4. See that the last import is successful 

**Expected behavior**
No error message should be thrown after successful import 

**Screenshots**
![image](https://user-images.githubusercontent.com/12541984/107352585-f0707180-6ac3-11eb-8928-7951349a04df.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - Version 88
 - testomat.io production site

**Comment by TetianaKhomenko** [comment]
closing this issue as CNR
