### ISSUE TITLE
Preview screen does not update after deleting all existing data in Bulk Edit

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#214]
**Describe the bug**
After deleting all existing data in Bulk Edit, preview screen (right part of the screen) does not update and contains previous data till adding new data. 

**To Reproduce**

1. Go to https://beta.testomat.io/
2. Open a project
3. Open Tests tab
4. Click on vertical ellipsis button
5. Choose Bulk edit
6. Add some data in the editor
7. Delete all existing data
8. See the right part of the screen contains deleted data

**Expected behavior**
Preview screen also deletes all data after deleting it in the editor

**Screenshots**
![bulk 1](https://user-images.githubusercontent.com/77803888/107689847-06dc2000-6cb2-11eb-8f68-84229c0b2f58.jpg)

**Desktop (please complete the following information):**
OS: Win 10
Browser chrome
Application: beta

**Comment by DavertMik** [comment]
Fixed!
