### ISSUE TITLE
Run Reporter does not update in realtime and does not show failed tests for BDD

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#219]
**Describe the bug**
When running automated tests Run Reporter does not show failed results to a user and does not save any information about them. Looks like it does not see failed results at all.
Also, Run Reporter does not update information in realtime, so when Test Run is finished actual number of tests is not shown to a user.
**Please note that the issue is present for BDD projects**

**To Reproduce**
1. Go to app.testomat.io
2. Create a BDD project
3. Go to Tests tab and import your tests using the given instructions (I used codeceptJS-cucumber)
4. Go to Run tab 
5. Click on Setup Automated and follow given instructions to run these tests
6. Go to Run tab and open the current run to see details in realtime
7. See that number of tests is not updating and failed tests are not shown

**Expected behavior**
Run Reporter updates in realtime and synchronizing with an ongoing automated run and shows all types of tests

**Screenshots**
![bug](https://user-images.githubusercontent.com/77803888/107959970-bb28bf80-6fac-11eb-991f-cb189ab1c6b2.jpg)
![bug 1](https://user-images.githubusercontent.com/77803888/107959984-bd8b1980-6fac-11eb-804c-ad1337522930.jpg)
![bug 2](https://user-images.githubusercontent.com/77803888/107959997-bfed7380-6fac-11eb-8a66-0a6ffb9075d4.jpg)
![bug 3](https://user-images.githubusercontent.com/77803888/107960001-c11ea080-6fac-11eb-9391-2bd50a006a3f.jpg)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser chrome
 - Application: production

**Comment by DavertMik** [comment]
Finally, fixed!

**Comment by TetianaKhomenko** [comment]
Run Reporter does not show failed tests for BDD

**Comment by TetianaKhomenko** [comment]
Additional info: issue with **not showing failed tests** occurs on Testing Framework: Codeceptjs, Language: Gherkin, Project: BDD

**Comment by TetianaKhomenko** [comment]
closing this issue as CNR
