### ISSUE TITLE
Checkboxes outline is missing in Runs tab on Beta

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#229]
**Describe the bug**
Checkboxes in Runs tab are hard to see because there is no contrast outline. Users may not notice them and will not be able to merge TestRuns. They can be seen only when user click on them.

**To Reproduce**
1. Go to https://beta.testomat.io/
2. Open a project with few TestRuns
3. Go to Run Tab
4. See the checkboxes are not noticeable

**Expected behavior**
Checkboxes have contrast outlines and are noticeable easily.

**Screenshots**
![Screenshot_18](https://user-images.githubusercontent.com/77803888/108957731-a7e7b500-767a-11eb-9c68-4c9c91dd273c.jpg)

![Screenshot_19](https://user-images.githubusercontent.com/77803888/108957781-bdf57580-767a-11eb-8bda-f9789c8bd8db.jpg)

**Desktop (please complete the following information):**

- OS: Win10
- Browser chrome
- Application: beta and production

**Comment by DavertMik** [comment]
Fixed
