### ISSUE TITLE
Merging multi-env runs does not contain report and run

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#249]
**Describe the bug**
When a user merges multi-env runs all test runs will disappear. RunReport also will be lost.

**To Reproduce**

1. Go to https://beta.testomat.io/
2. Open a project with suites
3. Open Runs tab
4. Launch multi-env run
5. Merge these runs
6. See all data disappeared

**Expected behavior**
Merged multi-env run contains TestReport and the Merged Run.

**Screenshots**
![444](https://user-images.githubusercontent.com/77803888/111081477-329a3200-850c-11eb-8ca8-d6e2441f4c96.gif)

**Desktop (please complete the following information):**
- OS: Win10
- Browser chrome
- Application: beta

**Comment by TetianaKhomenko** [comment]
The issue is also present for Test Groups

**Comment by DavertMik** [comment]
Fixed!
Rungroup was ignored when merging runs so runs appeared in the main list
