### ISSUE TITLE
After assigning a different user and reassign it to back user can not finish the run

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#250]
**Describe the bug**
After assigning a different user and reassign it to yourself user can not finish the run

**To Reproduce**

1. Steps to reproduce the behavior:
2. Go to https://beta.testomat.io/
3. Open a project with suites
4. Open Runs tab
5. Create a TestRun
6. Assign it to a different user
7. Launch it
8. Close it
9. Open it
10. Reassign it to yourself  
11. Launch this TestRun
12. Finish it
13. See the TestRun cannot be finished

**Expected behavior**
the TestRun can be finished after reassigning.

**Screenshots**
![555](https://user-images.githubusercontent.com/77803888/111081807-c9b3b980-850d-11eb-94be-bd5a0340eac4.gif)

**Desktop (please complete the following information):**

- OS: Win10
- Browser chrome
- Application: beta

**Comment by TetianaKhomenko** [comment]
This issue affects Multi-env Runs also

**Comment by DavertMik** [comment]
Fixed
