### ISSUE TITLE
Tests older than 4 month show as "a few seconds ago"

### ISSUE THREAD

**Issue by cebe** [testomatio/app#251]
**Describe the bug**

See issue in the screenshot:

![2021-03-17_13-50](https://user-images.githubusercontent.com/189796/111762372-3da0e980-88a1-11eb-9905-f28d28a7f6ee.png)

**To Reproduce**

1. Go to "Runs"
2. Have old test runs
4. You should see the issue from the screenshot

**Expected behavior**

correct absolute date or relative date display.

**Comment by DavertMik** [comment]
Should be fixed in new release
