### ISSUE TITLE
Jira screen contains not understandable message when entering wrong credentials

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#252]
**Describe the bug**
When a user enters wrong credentials in Jira in Testomatio App he receives not understandable message

**To Reproduce**
1. Go to Jira
2. Install Testomatio App
3. Open it
4. Enter wrong login or password
5. Click on Submit button
6. See the error

**Expected behavior**
user receives understandable message

**Screenshots**
![Screenshot_26](https://user-images.githubusercontent.com/77803888/112039704-fe96c080-8b4c-11eb-987d-b347f89365db.jpg)

**Comment by DavertMik** [comment]
I think this was fixed in recent release
