### ISSUE TITLE
Deleted test is not removed from feature description in BDD

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#256]
**Describe the bug**
When a user deletes a test from a feature the description does not update. The description contains both deleted and existing tests.

**To Reproduce**
1. Go to https://beta.testomat.io/
2.  Open a BDD project
3. Add a suite
4. Add few tests to the suite and save
5. Delete one test
6. Open the suite
7. See deleted tests is present in the feature description

**Expected behavior**
Feature description updates after deleting a test

**Screenshots**
![wer5](https://user-images.githubusercontent.com/77803888/113340419-8a220580-9334-11eb-9287-0b82d763c165.gif)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser chrome
 - Application: beta

**Comment by DavertMik** [comment]
Fixed
