### ISSUE TITLE
Run Report disappears after being finished in CI 

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#257]
**Describe the bug**
When executing tests in GitHub Actions Testomatio does not save the Report.

**To Reproduce**
1. Open a project linked to GitHub Actions
2. Go to Runs tab and choose Run in CI
3. Setup CI service and Launch 
4. See that Testomatio shows **no Reports**

**Expected behavior**
A Run Report is added to the list of Reports

**Screenshots**

<img width="1435" alt="Screenshot at Apr 11 22-14-17" src="https://user-images.githubusercontent.com/77803888/114318152-615bf600-9b14-11eb-9cd7-dc36d1ce3327.png">
<img width="1391" alt="Screenshot at Apr 11 22-16-37" src="https://user-images.githubusercontent.com/77803888/114318160-69b43100-9b14-11eb-9555-4f44222af3b5.png">
<img width="1418" alt="Screenshot at Apr 11 22-17-25" src="https://user-images.githubusercontent.com/77803888/114318163-6e78e500-9b14-11eb-8e74-a9e50242f126.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Application: beta

**Comment by DavertMik** [comment]
Current CI settings has `TESTOMATIO_RUNGROUP` environment variable set, so all Runs were sent to a specific RunGroup
