### ISSUE TITLE
Test Plans tab does not add tests to already existing Test Plans

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#259]
**Describe the bug**
If a user wants to edit a test plan and add more tests, he will not be able to do this and will receive a not understandable hint.
Also Test Plans contains not adjustable field.

**To Reproduce**
1. Go to https://beta.testomat.io/
2. Open a project
3. Go to Test Plans tab
4. Create a Test Plan
5. Edit it 
6. Try to add more tests
7. See the error

**Expected behavior**
User is able to edit test Plan and add more tests in Test Plans tab

**Screenshots**
![wer6](https://user-images.githubusercontent.com/77803888/114590589-a0fc1c80-9c91-11eb-9e7f-970c5db5b13a.gif)
![Screenshot_37](https://user-images.githubusercontent.com/77803888/114590861-efa9b680-9c91-11eb-91cb-91d7fb741379.jpg)

**Desktop (please complete the following information):**
OS: Win10
Browser chrome
Application: beta

**Comment by TetianaKhomenko** [comment]
Also Test Plans tab contains doubled Delete button
![photo_2021-04-13_19-58-44](https://user-images.githubusercontent.com/77803888/114591533-aa39b900-9c92-11eb-9d86-30634e3211a8.jpg)

**Comment by DavertMik** [comment]
Fixed the first issue from this list

**Comment by TetianaKhomenko** [comment]
The first issue from this list is verified as fixed 👍
Reopening for further improvements 💪
