### ISSUE TITLE
Occasionally avatar and name of the assigned users disappears from Runs tab

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#262]
**To Reproduce**
1. Go to https://beta.testomat.io/
2. Open project with multiple users and assigned TestRuns
3. Open runs Tab
4. See the issue

**Screenshots**
![photo_2021-04-15_11-26-21](https://user-images.githubusercontent.com/77803888/114838474-6acbb380-9ddd-11eb-8149-352f55c91731.jpg)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser chrome
 - Browser Version 89.0.4389.114 
 - Application: beta

**Comment by poliarush** [comment]
@TetianaKhomenko please retest it

**Comment by TetianaKhomenko** [comment]
fixed!
