### ISSUE TITLE
Scroll is too long on Run page which hides the last test in a Test Run

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#267]
**Describe the bug**
User can't see the last test in the Test Plan because it is hidden by the absence of space in the bottom.

**To Reproduce**
1. Go to https://beta.testomat.io/
2. Open a project
3. Go Runs tab
4. Launch manual Run with more than 15 tests
5. Scroll to the bottom of the page
6. See the issue, user can't see the last test in the list

**Screenshots**
![image](https://user-images.githubusercontent.com/77803888/115109865-08131d00-9f81-11eb-8e64-7693a5284c0c.png)

**Desktop (please complete the following information):**

- OS: Win 10, MacOS
- Browser chrome
- Application: beta

**Comment by DavertMik** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/220264/129263027-0b41d288-b994-4fd0-96e7-c36f1ae530d1.png)
