### ISSUE TITLE
User can not launch Automated tests because Menu button does not open menu itself on Runs page

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#291]
**To Reproduce**

1. Go to https://beta.testomat.io
2. Open a project
3. Go to Runs page
4. Click on Menu button on the top of the screen 
5. See the issue

**Expected behavior**
This action should open a menu with the ability to launch automated runs

**Screenshots**

![qwertyu](https://user-images.githubusercontent.com/77803888/117538609-a4c05c00-b00f-11eb-8851-3176ceb2db64.gif)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser chrome
 - Application: beta

**Comment by TetianaKhomenko** [comment]
Reopen. The issue is still present

**Comment by DavertMik** [comment]
Ups, I forgot to push it :) 
Fixed now
