### ISSUE TITLE
UI elements are misaligned on the Multi-Environment Run Report screen on Repot Tab 

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#306]
**To Reproduce**
1. Go to https://beta.testomat.io
2. Open a project with manual tests
3. Go to Runs page
4. Click on Manual Run
5. Add 3 or more envs
6. Complete this Multi-Environment Run 
7. Open the Report 
8. Click on Repot tab

**Screenshots**

![Screenshot_2](https://user-images.githubusercontent.com/77803888/118126021-64425300-b400-11eb-8593-534ec7904d50.jpg)

**Desktop (please complete the following information):**
OS: Win 10, iOs
Browser chrome
Application: beta

**Comment by TetianaKhomenko** [comment]
still present

![image](https://user-images.githubusercontent.com/77803888/149789697-cab634e5-dc8b-421c-bcf7-730d223f384c.png)

**Comment by poliarush** [comment]
@TetianaKhomenko please retest it

**Comment by TetianaKhomenko** [comment]
fixed
