### ISSUE TITLE
Image is not uploaded successfully 

### ISSUE THREAD

**Issue by Sinnv2710** [testomatio/app#320]
**Describe the bug**
Sometimes we would like to upload bug image attachment but after upload, the image is not displayed in attachments tabs
**To Reproduce**
1. Go to 'detail test case'
2. Click on 'attachments' options
3. Click upload and select any image to upload
4. After the process bar is loaded 100%
5. I noticed that the image is not displayed after uploaded

**Expected behavior**
Image attachments should be displayed after upload 
**Screenshots**
None

**Comment by poliarush** [comment]
@Sinnv2710 what is the file size? approxiate
