### ISSUE TITLE
Suites with sub-suites added in Editor are added in random order in Bulk edit

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#334]
**Describe the bug**

**To Reproduce**
1. Open a project with suites
2. Add suite with sub-suites
3. Go to Bulk edit
4. See the issue

**Expected behavior**
Added suites with sub-suites are added in right order

**Screenshots**

![qwertyu](https://user-images.githubusercontent.com/77803888/121377047-b8325000-c94a-11eb-86b2-901ed64ffa08.gif)

![qwertyu 1](https://user-images.githubusercontent.com/77803888/121377061-bbc5d700-c94a-11eb-9b06-5a14c9c9510b.gif)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser chrome
 - Application: beta

**Comment by TetianaKhomenko** [comment]
Please note that the issue affects also bulk-editing itself

**Comment by DavertMik** [comment]
Can't reproduce

**Comment by TetianaKhomenko** [comment]
@DavertMik I managed to reproduce. Please see the attached video

https://user-images.githubusercontent.com/77803888/192294725-785ad14a-0d77-4db9-ba52-c124e875031a.mp4

**Comment by littlefrontender** [comment]
@TetianaKhomenko I think this issue should be retested. I can't reproduce.

**Comment by TetianaKhomenko** [comment]
The issue was re-tested and verified as fixed
