### ISSUE TITLE
Error appears when dragging and drop tests within filters results 

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#380]
**To Reproduce**
1. Open a project
2. Filter tests by manual/automated
3. Drag and drop a test from one suite to another
4. See the error

**Expected behavior**
There should be no error.
OR the error should contain a relevant message. 

**Screenshots**

![image](https://user-images.githubusercontent.com/77803888/126067582-e40c1dca-5529-47b1-a7ae-ef5b6bce7961.png)

![image](https://user-images.githubusercontent.com/77803888/126067618-aac7d696-9c7b-4ee8-bb17-1b7e5dd32165.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Application: beta

**Comment by DavertMik** [comment]
Disallowed to move but error is nicer

![image](https://user-images.githubusercontent.com/220264/129271356-049037c6-8762-4745-86e5-0881d110ff3c.png)
