### ISSUE TITLE
Create / Update / Delete a Template from UI

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#4]
![image](https://user-images.githubusercontent.com/325722/81745825-c727a400-94a5-11ea-9575-a30c0f9acf09.png)

**Comment by koushikmohan1996** [comment]
Added Edit option. Create and delete redundant here
![template_edit](https://user-images.githubusercontent.com/24666922/82111451-0c2c2e80-9763-11ea-9626-1fc625872fec.gif)
