### ISSUE TITLE
UI elements does not adjust to window size on Feature Description screen

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#407]
**To Reproduce**

1. open a BDD project
2. open feature editor
3. resize the browser window
4. scroll the page
5. see the issue 

**Screenshots**

![CleanShot-Google Chrome-Testomat io-2021-07-20 at 19 56 06](https://user-images.githubusercontent.com/77803888/126593485-6d5caa0f-24db-4e75-81a5-31817d2ea075.gif)

![screencast 2021-07-22 08-17-01](https://user-images.githubusercontent.com/77803888/126593233-1fa98739-2125-4fea-9b9b-5960903495f5.gif)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Application: beta

**Comment by littlefrontender** [comment]
@TetianaKhomenko  i guess this issue doesn't reproduce now

**Comment by TetianaKhomenko** [comment]
re-check and verified as fixed
