### ISSUE TITLE
cypress demo project importing is failing with error

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#43]
TOTAL 114 TESTS FOUND

 🚀 Sending data to testomat.io

 ✖️  Eror while uploading data: Mysql2::Error: Incorrect string value: '\xF0\x9F\x91\x80\x0A ...' for column 'code' at row 1

**Comment by koushikmohan1996** [comment]
@DavertMik I think this is released

**Comment by poliarush** [comment]
now I have 

![image](https://user-images.githubusercontent.com/325722/83137463-80fb5300-a0e9-11ea-9ff3-1d05ce412348.png)

**Comment by poliarush** [comment]
deleted folder fully and recreated it again, it fixed issue

![image](https://user-images.githubusercontent.com/325722/83137677-dd5e7280-a0e9-11ea-9e8f-74db63965b2a.png)
