### ISSUE TITLE
Empty scenarios are deleted when editing Feature file in BDD editor

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#444]
**Please note, that the issue occurs when there is no indentation between empty scenarios.**

**To Reproduce**
1. open a Feature file with empty scenarios in BDD editor
2. click on Format button
3. see the issue

**Screenshots**

![CleanShot-Google Chrome-Testomat io-2021-07-27 at 11 35 23](https://user-images.githubusercontent.com/77803888/127135407-9ad57264-a524-4b8c-89bd-a5b7ca83b0e3.gif)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Application: beta

**Comment by DavertMik** [comment]
Added Undo command for that
The original issue can't be fixed
