### ISSUE TITLE
Format button is hidden by hint for Feature files with automated tests

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#446]
**Describe the bug**
Format button is hidden by hint when editing Feature files with automated tests. And it is not clickable till it appears in a full size. It will appear only after actually editing the feature. 

**To Reproduce**
1. open a bdd project with automated tests 
2. open a feature file
3. click on Edit button
4. see the issue 

**Screenshots**

![screencast 2021-07-27 13-46-26](https://user-images.githubusercontent.com/77803888/127144065-68fb47c2-6791-4a86-a402-4bf0be66260c.gif)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Application: beta

**Comment by DavertMik** [comment]
Should be fixed
