### ISSUE TITLE
Tests screen is very small, so it's hard to interact with tests on Suite view screen

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#450]
**To Reproduce**
1. open a suite with tests
2. take a look at the bottom of the screen
3. see the issue 

**Screenshots**

![screencast 2021-07-29 11-53-50](https://user-images.githubusercontent.com/77803888/127476928-1d705098-6324-464a-9812-91c815ddfa7a.gif)

![screencast 2021-07-29 15-42-57](https://user-images.githubusercontent.com/77803888/127495782-1fe584c6-18cd-4bf2-a141-32e5f2358b04.gif)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Application: beta

**Comment by littlefrontender** [comment]
@TetianaKhomenko I couldn't reproduce this issue

**Comment by TetianaKhomenko** [comment]
fixed
