### ISSUE TITLE
Test get misaligned when parameter name is long when running tests manually

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#459]
**Describe the bug**
When running automated tests manually, a test containing too long parameter name will break a table which may frustrate a user, because a user will not see the status of the test.

**To Reproduce**
1. open a project
2. create a test with long parameter name
3. go to Runs
4. launch the run
5. see the issue 

**Screenshots**

![image](https://user-images.githubusercontent.com/77803888/127997986-be7b401a-6b9c-4126-8db5-a29e88a65886.png)

![image](https://user-images.githubusercontent.com/77803888/128000076-68b308c5-acce-4d04-8efa-8db6350aead1.png)

![screencast 2021-08-03 13-16-57](https://user-images.githubusercontent.com/77803888/128000828-0b3266ea-d694-47b6-841b-5b6bbba6c9bd.gif)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Application: beta

**Comment by littlefrontender** [comment]
@TetianaKhomenko this issue doesn't reproduce

**Comment by TetianaKhomenko** [comment]
fixed
