### ISSUE TITLE
Project created in Free Projects will not be shown in invited members dashboard if this user has own company

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#466]
**Describe the bug**
When one user invites another to a project created within Free Project, the invited member will not have this project on his dashboard.

**To Reproduce**
1. create a project within Free Projects
2. invite another user to this project
3. open invited user's dashboard
4. see no project shown

**Expected behavior**
add "Free Projects"  tab to a companies drop-down on a start page

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Application: beta

**Comment by bpastukh** [comment]
> 3. open invited user's dashboard
Before this step, you have to accept the invitation via email

**Comment by TetianaKhomenko** [comment]
the issue is closed as fixed
