### ISSUE TITLE
Tests name needs word wrapping 

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#481]
**To Reproduce**
1. open a project
2. create a test with a very long name
3. resize the browser window
4. see the issue 

**Expected behavior**
The name of the test is wrapped by words,  o a user can see tests statuses

**Screenshots**

![screencast 2021-08-20 10-00-25](https://user-images.githubusercontent.com/77803888/130194128-c6fd0ebc-f65c-4af7-9366-90c6efa8f71a.gif)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Application: production and beta

**Comment by TetianaKhomenko** [comment]
the issue is still present

**Comment by littlefrontender** [comment]
this issue doesn't reproduce

![Image](https://user-images.githubusercontent.com/79913874/220365335-1692e5e8-fb2a-4a0c-8548-a73f88ea1da5.png)

**Comment by TetianaKhomenko** [comment]
fixed
