### ISSUE TITLE
CSV/XLS import shows wrong number of imported tests on Imports page

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#508]
**To Reproduce**
1. open a project
2. import tests from .csv file
3. go to Imports page
4. see the issue 

**Screenshots**

![image](https://user-images.githubusercontent.com/77803888/134336100-7480f531-7851-420a-8ae6-09e840648d65.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Application: beta

**Comment by komarov-v** [comment]
Import from Qase has the same problem

**Comment by TetianaKhomenko** [comment]
Zephyr and qTest imports also have problems with showing wrong number of imported tests

Here were 50 tests indeed imported:
![image](https://user-images.githubusercontent.com/77803888/146501205-4aed421a-4659-4bef-ba6b-b933cb5def86.png)

Here were nearly 10 indeed imported:
![image](https://user-images.githubusercontent.com/77803888/146501529-394c9da5-a7d0-437d-aabd-54db075540bf.png)

**Comment by poliarush** [comment]
@komarov-v could you please provide an example files you were used during import stage.

**Comment by TetianaKhomenko** [comment]
The issue is fixed and will be available with the next release.

![image](https://user-images.githubusercontent.com/77803888/148517243-9f3ad989-ac93-4cd4-b223-c41a7858f3dd.png)
