### ISSUE TITLE
Add default CI connection

### ISSUE THREAD

**Issue by Mkots** [testomatio/app#531]
When I use "Run in CI" functionality I always have to choose which connection would use in run. This strange thing frustrated me because I have only one connection and I don't want waste time for this unnecessary setup. 

As a solution, I suggesting you to add a special check-box in CI connection settings. This checkbox will be a flag that describes which connection should use as a default. In case any of the configurations is already specified as default, you should show a notice and allow overriding the default sign.
![Selection_588](https://user-images.githubusercontent.com/36552393/136661404-e831f080-8e57-46c8-8e69-8961ffc9edfc.png)
![Selection_589](https://user-images.githubusercontent.com/36552393/136661480-f487ba5b-37a6-4c28-a49e-78e95336a369.png)

In case if such functionality is difficult to implement there is an alternative. Perhaps the connection selector can choose the first or only configuration thus users would save time if they don't have many configurations.

**Comment by TetianaKhomenko** [comment]
Implemented and will be available with the next release.

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/77803888/160381354-66ad62cf-d993-4a2b-af23-7140d51343fc.png">
