### ISSUE TITLE
Steps Page has BDD UI in Classical project

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#546]
**Describe the bug**
In **classical** projects we don't use Given When Then paradigm. But in **classical** projects we have these on Steps Page. At the same time Given When Then columns are always empty.
Also, Automated steps are not shown, although the projects contain imported tests.

**Screenshots**

![screencast 2021-10-20 18-08-48](https://user-images.githubusercontent.com/77803888/138122434-7d304449-fd6a-465a-905b-44c984dad6b3.gif)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Application: beta

**Comment by jmychasiw** [comment]
Thank you for logging this issue.  I was trying to determine how log the multiple issues that I found.
As you pointed out, the BDD is confusing on top of the fact that the Classical steps implementation does not match the way steps work in BDD.  

The core functionality should be same between Classic and BDD.

**Comment by TetianaKhomenko** [comment]
The issue was fixed and will be added to the next release

<img width="530" alt="image" src="https://user-images.githubusercontent.com/77803888/160166946-1198d603-db42-4d25-b5e9-09f76e6c1d40.png">
