### ISSUE TITLE
add text to ask any questions by replying to welcome email if user struggle

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#56]
![image](https://user-images.githubusercontent.com/325722/83015757-36160880-a021-11ea-9717-53cc34adbd1f.png)

**Comment by poliarush** [comment]
the same for project invitation 

![image](https://user-images.githubusercontent.com/325722/83016030-a3299e00-a021-11ea-8f04-92e901273fa3.png)

**Comment by TetianaKhomenko** [comment]
implemented
