### ISSUE TITLE
Error: Data too long for column 'test_title'  while the title is not that long

### ISSUE THREAD

**Issue by XavierDeMontis** [testomatio/app#560]
Tried to run through the CI (jenkins) a Gherkin scenario which title is "Show users with source access in the visualization sharing modal".

In Testomat we end up with the following errors : 

Error reporting test to Testomat.io. Mysql2::Error: Data too long for column 'test_title' at row 1. Check runner logs

How can that happen ?

**Comment by TetianaKhomenko** [comment]
the issue is fixed in the next release
