### ISSUE TITLE
Import same test suite in a different project fails

### ISSUE THREAD

**Issue by XavierDeMontis** [testomatio/app#563]
Hi 
We have two projects in testomat, each one dedicated to a given version of our app. Let's call them projectA and projectB.
We run tests for projectA for months and it runs smoothly.
As projectB is quite similar to projectA, we did want to import the same tests to projectB
.
But when running the import command we end up with errors :

Import failed with following error message :
Suite 9c6e407e not found in project 'Linkurious Enterprise Stable'; Suite 9c6e407e not found in project 'Linkurious Enterprise Stable'; Suite 9c6e407e not found in project 'Linkurious Enterprise Stable'; Suite 9c6e407e not found in project 'Linkurious Enterprise Stable'; Suite 157da334 not found in project 'Linkurious Enterprise Stable'; Suite 157da334 not found in project 'Linkurious Enterprise Stable'; Suite 157da334 not found in project 'Linkurious Enterprise Stable'; Suite 078cbe02 not found in project 'Linkurious Enterprise Stable'; Suite 078cbe02 not found in project 'Linkurious Enterprise Stable'; Suite 078cbe02 not found in project 'Linkurious Enterprise Stable'; Suite 078cbe02 not found in project 'Linkurious Enterprise Stable'; Suite 078cbe02 not found in project 'Linkurious Enterprise Stable'; Suite 078cbe02 not found in project 'Linkurious Enterprise Stable'; Suite 078cbe02 not found in project 'Linkurious Enterprise Stable'; Suite 078cbe02 not found in project 'Linkurious Enterprise Stable'; Suite 4ea5eec4 not found in project 'Linkurious Enterprise Stable'; Suite 4ea5eec4 not found in project 'Linkurious Enterprise Stable'; Suite 4ea5eec4 not found in project 'Linkurious Enterprise Stable'; Suite 4ea5eec4 not found in project 'Linkurious Enterprise Stable'; Suite 4ea5eec4 not found in project 'Linkurious Enterprise Stable'; Suite 4ea5eec4 not found in project 'Linkurious Enterprise Stable'; Suite 4ea5eec4 not found in project 'Linkurious Enterprise Stable'; Suite 4ea5eec4 not found in project 'Linkurious Enterprise Stable'; Suite 4ea5eec4 not found in project 'Linkurious Enterprise Stable'; Suite f1f9d8e2 not found in project 'Linkurious Enterprise Stable'

Is this because Testomat cannot have similar id for different projects ? How can we solve this ?

**Comment by poliarush** [comment]
@XavierDeMontis just curious what use case do you want to achieve by using the same tests?

do you have some customization for your clients and do you want to keep such cases separately for each custom version?

**Comment by poliarush** [comment]
in fact, we do have branches in enterprise version where 
where you can create a branch per each version of your project and it will be centralized
what do you think?

**Comment by poliarush** [comment]
https://user-images.githubusercontent.com/325722/143427659-b6382517-60a1-4b8e-9e9f-161e71411370.mp4

**Comment by XavierDeMontis** [comment]
Let's see this as a set of tests ensuring basic features shared between all versions are still ok.
As we are not using the Enterprise but the Professional version we don't benefit from the branches feature of Testomat.

**Comment by poliarush** [comment]
shortly speaking, currently, you need to clean ids before you're importing to new project

**Comment by XavierDeMontis** [comment]
Well yes the idea was to keep the same set of tests and not modify the identifiers - which would not be really sustainable.

**Comment by DavertMik** [comment]
@XavierDeMontis the solution we can provide here is:

- to import tests for project A and set the IDs with `--update-ids`
- import tests to project B with `--create` flag which does not exist yet
- all IDs from project A will be created in project B

So the idea is to add an extra flag that will create tests and suite with the ids that were provided.

**Comment by DavertMik** [comment]
Implemented. This will be published in the upcoming release

**Comment by TetianaKhomenko** [comment]
Hi @XavierDeMontis! The solution with `--create` flag was implemented and will be provided with `check-tests v.0.7.2` in the next release soon. Here are some example screenshots:

![image](https://user-images.githubusercontent.com/77803888/143552394-061991b8-b96e-42a5-b235-a30eaf09c151.png)

![image](https://user-images.githubusercontent.com/77803888/143552548-20249d24-02d1-4e70-948e-00a139e88e42.png)

**Comment by XavierDeMontis** [comment]
Thanks @TetianaKhomenko
