### ISSUE TITLE
On re-importing automated tests, Testomat leaves folders with 0 tests 

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#567]
**Describe the bug**
On re-importing automated tests, Testomat leaves folders with 0 tests when the source code structure was changed. There may be a huge amount of such folders, especially when changes are imported automatically.
**This behavior creates inconveniences for users that make often changes in source code structure.**

**To Reproduce**
1. import automated tests with --update-ids
2. go to source code
3. relocate your test files to other folders
4. import automated tests again (you may use --keep-structure)
5. go to Testomat
6. see empty folders are present on Tests page

**Expected behavior**
The suggestion is to provide an ability to delete all folders with 0 tests with 1 click in UI by **delete all empty suites** button in the menu on Tests page
OR add flag  `--delete-empty-folders`

**Screenshots**

![image](https://user-images.githubusercontent.com/77803888/146392192-7af8b366-36fd-4591-be79-7aabe92b0e44.png)

![image](https://user-images.githubusercontent.com/77803888/146385632-491d8f63-5e22-4640-b206-4512d8358f9f.png)

**Comment by DavertMik** [comment]
![image](https://user-images.githubusercontent.com/220264/148640246-38fec1ea-c540-4cd2-8a0c-ec5ea820cfe3.png)

**Comment by TetianaKhomenko** [comment]
fixed 

https://user-images.githubusercontent.com/77803888/148761469-6785b7b1-a3b5-4146-8261-04bc337b6a1e.mp4
