### ISSUE TITLE
Collapsed tests trees reexpand themselves

### ISSUE THREAD

**Issue by XavierDeMontis** [testomatio/app#570]
**Describe the bug**
Impossible to collapse all the tests : they reexpand themselves

**To Reproduce**
- Have multiple tests - either manual or automated - containing each multiple scenarii
- By default the tests are expanded, so try to collapse most of them to keep a global overview 
- Suddenly, while you were progressively collapsing everything, everything reexpands, making it impossible to have a real overview of your tests

**Expected behavior**
I wanna have control over my tests, that's the main point of the tool. Here I can't have a clear overview.

**Screenshots**
https://user-images.githubusercontent.com/67690774/150552109-e421178d-17d3-4b2a-a815-9dc3453fb1d0.mp4

**Desktop (please complete the following information):**
 - OS: Win 10 Version 21H1 (Build 19043.1466)
 - Browser Chrome 97.0.4692.71
 - Application: prod

**Additional context**

**Comment by TetianaKhomenko** [comment]
The issue is fixed and will be available in the next release.
