### ISSUE TITLE
Tests synchronized by ID do not seem to actually be synchronized

### ISSUE THREAD

**Issue by XavierDeMontis** [testomatio/app#575]
**Describe the bug**
For a few months we come up with this disturbing situation : tests that are supposed to be synchronized by ID - as recommended - actually lost their sync. 
![image](https://user-images.githubusercontent.com/67690774/155945157-e32e8f53-e8a7-4fc8-8a2b-92bc7fea0de9.png)
This is particularly annoying as we regularly amend our test steps and examples in the code base, perform a test import and expect to have something clean in Testomat. As a matter of fact even the tests are not properly updated by the import command - but that may deserve an other bug ticket.

**To Reproduce**
Not really sure, I can just tell you that we perform imports regularly with options --update-ids --create

**Expected behavior**
As my tests are imported into Testomat using the option --update-ids I expect these ID to be properly taken into account by the system, keeping Testomat and the code base in Sync.

**Screenshots**
If applicable, add screenshots or video to help explain your problem.

**Desktop (please complete the following information):**
 - Browser Version [e.g. 22]
 - Application: [production or beta] 

**Additional context**

**Comment by TetianaKhomenko** [comment]
fixed
