### ISSUE TITLE
Projects name are truncated in the Projects Dashboard

### ISSUE THREAD

**Issue by XavierDeMontis** [testomatio/app#577]
**Describe the bug**
In the projects dashboard long project names are now truncated

**To Reproduce**
* Go to the project dashboard of Testomat 
* Create a project which name is longer than 17 characters
=> the project's name appears as truncated
![image](https://user-images.githubusercontent.com/67690774/162000406-2121afb7-ddd7-4698-b9ad-c4ef80823bb6.png)

**Expected behavior**
I expect to be able to easily differentiate my projects by being able to see their full name.

**Screenshots**
If applicable, add screenshots or video to help explain your problem.

**Desktop (please complete the following information):**
 - Browser Version [e.g. 22]
 - Application: [production or beta] 

**Additional context**

**Comment by TetianaKhomenko** [comment]
Hi @XavierDeMontis! The issue is fixed and will be added to the next release

![image](https://user-images.githubusercontent.com/77803888/164297914-28964259-fed3-473b-8256-eaf5cb421718.png)
