### ISSUE TITLE
Continous integration : Test CI Connection does not give enough information in case of failure

### ISSUE THREAD

**Issue by XavierDeMontis** [testomatio/app#580]
**Is your feature request related to a problem? Please describe.**
For a few months it seems liaison between Testomat and Jenkins is failing.
When we go to Settings > Continous Integration > Jenkins > Test Connection the only error message we receive is the following one :
{"error":"\n  \n  \u003c!DOCTYPE html\u003e\u003chtml\u003e\u003chead resURL=\"/static/9c2b1703\" data-rooturl=\"\" data-resurl=\"/static/9..."}
It's truncated and does not help to solve our issue.

**Describe the solution you'd like**
We would like to have a way to investigate such failure, at least an access to more complete logs would be appreciated.

**Describe alternatives you've considered**
For now we can only blindly try other configurations so no real alternatives.

**Additional context**

**Comment by TetianaKhomenko** [comment]
the issue was fixed and will be published with the upcoming 0.5.4 release
