### ISSUE TITLE
Add Code Template for Playwright projects

### ISSUE THREAD

**Issue by komarov-v** [testomatio/app#589]
**Is your feature request related to a problem? Please describe.**
There is no "Code template" for project with Playwright  both Typescript and JavaScript

**Describe the solution you'd like**
Add a "Code template" for Playwright projects

E.g.:
```typescript
test.describe('{{ suite }}', () => {
  test('{{ test }}', async () => {
    {{body}}
  });
});
```

**Comment by TetianaKhomenko** [comment]
Hi @komarov-v the issue was fixed and will be added to the next release. 

https://user-images.githubusercontent.com/77803888/173283708-a00480c4-b8c1-411e-a7c9-41f5e849357f.mp4
