### ISSUE TITLE
Import does not show actual changes in automated tests

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#592]
**Describe the bug**
When I import tests from the source code all imported tests are marked as `updated` although only few of them were changed.
This mislead users.

**To Reproduce**
1. open project with automated tests
2. import these tests again, without any changes in source code
3. open imports page
4. click on this import
5. see the issue 

**Expected behavior**
if 1 test has changed in the code, 1 has been added, 1 has been removed
then it is shown that 1 `updated`, 1 `deleted`, and 1 `added`
the rest can be shown in gray as `synced`

![CleanShot 2022-06-10 at 12 22 13@2x](https://user-images.githubusercontent.com/77803888/173035019-c0ef165a-d805-4b7c-bfc2-153c8b43bf13.jpg)

**Screenshots**
![CleanShot 2022-06-10 at 12 12 15@2x](https://user-images.githubusercontent.com/77803888/173032951-92db8dfe-56c8-44ae-b2bb-43e980be3e85.jpg)

**Comment by DavertMik** [comment]
![Image](https://user-images.githubusercontent.com/220264/175838062-515029fb-c708-4817-b77d-8684699e6af2.png)

**Comment by TetianaKhomenko** [comment]
fixed
