### ISSUE TITLE
Skipped test scenario shouldn't be treated as failed test scenario

### ISSUE THREAD

**Issue by jhenkie** [testomatio/app#594]
I tried to run my test with below conditions :
I run my test based on Cypress framework with Gherkin language
I use @tag to specify my test scenarios
I have 1 feature file consisting of 6 scenarios then I put tag "test" only for 3 scenarios then the 3 others without tag "test"
From my local terminal, I can see that it will run 3 Scenarios and the rest will be treated as Pending 
From Testomatio report, I can see that it will run 3 Scenarios but the rest will be treated as Failed

![023e9d2c-b8e1-4743-8e5f-f7b2a970fa73](https://user-images.githubusercontent.com/27183018/177182864-158b0b97-c03e-41d4-b6fb-5ae2dcd7d6c4.jpg)
![image](https://user-images.githubusercontent.com/27183018/177183103-993e8606-4c3f-49b3-a43f-e0bccf01c9c7.png)

**Comment by poliarush** [comment]
@jhenkie that is fixed, could you please re-check this

**Comment by jhenkie** [comment]
Hi Mykhailo,

Thank you for letting me know. I have informed the team about this.

Regards,
Johannes
