### ISSUE TITLE
Tests do not get created in bulk via the Jira plugin if duplicate tests are added

### ISSUE THREAD

**Issue by vlad-ap** [testomatio/app#598]
**Describe the bug**
If you attempt to create 20 test cases using the "Bulk Create" feature of the Jira plugin and if you accidentally put in duplicate names, the entire set will not get created.

**To Reproduce**
1. Go to a Jira ticket that is linked to a suite and tests and shows the Testomatio widget (aka section)
2. Scroll down to the Testomatio widget
3. Inside the widget:
4. Make sure you are logged in to Testomat
5. Click to open the meatball menu next to your user icon -> [•••]
6. See dropdown opens
7. Click "Bulk Create"
8. See Bulk Create modal opens
9. Choose a test suite
10. Add 4 example tests (separated by new line), i.e.:
11. Test one
12. Test two
13. Test three
14. Test one
15. Make 2 of them have exactly the same name (see above)
16. Click "Create"
17. See error notification pops up at the top "Can't have tests with the same name in one suite"
18. See modal remains open with an infinite spinner ❌
19. Refresh the page
20. See tests not created ❌

**Expected behavior**
The tests should get created anyway - even if there is a duplicate name

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Browser Version: 103
 - Application: Production

**Additional context**

**Comment by poliarush** [comment]
https://user-images.githubusercontent.com/325722/179173932-219a1de8-9217-4f75-9e22-f213e3e42296.mp4

**Comment by TetianaKhomenko** [comment]
Hi @vlad-ap! The issue was fixed. This improvement will be added to the upcoming release.
Please see the attached videos.

https://user-images.githubusercontent.com/77803888/180178713-c4899d32-cbc5-42d3-9fd7-033838452ab8.mp4

https://user-images.githubusercontent.com/77803888/180181019-8ffe991b-ade2-42bf-a297-85245fb3b25b.mp4
