### ISSUE TITLE
Add the ability to choose where to send the results of the wound run

### ISSUE THREAD

**Issue by kirhike** [testomatio/app#599]
**Is your feature request related to a problem? Please describe.**
sometimes the tests fail not because they are bad, but because there are problems on the test bench. In this regard, when you retrieve tests that fail, it is not always necessary to create a new run, clogging the run table

**Describe the solution you'd like**
add the ability or choice of where to send the results of the wound, whether to create a new use the same

**Comment by TetianaKhomenko** [comment]
Hi @kirhike! this enhancement was implemented. For now, testomat.io will not create new test runs when Relaunch All and Relaunch Failed in CI.
