### ISSUE TITLE
Image preview mode is missing on the individual test view page

### ISSUE THREAD

**Issue by tikolakin** [testomatio/app#609]
**Describe the bug**
Image preview mode is missing on the individual test view page
Expected
The image is opened in preview mode

**To Reproduce**
1. Open an individual test page, ex. URL https://app.testomat.io/projects/prjct/test/79e55566#
2. Upload an attachment 
<img width="1877" alt="image" src="https://user-images.githubusercontent.com/5860505/191315521-daa31834-ad64-4932-b3ec-ff891d6f0a3d.png">

3. Open test description edit mode and add available attachment
4. Save changes
5. On the test view page observe attachment is displayed
6. Click on the image

**Expected behaviour**
The image is opened in the preview mode

**Actual behaviour**
Image is downloaded

**Screenshots**
Please see the video here https://www.loom.com/share/72e2e7966ffc4b04a59fe1b4228d006e
**Observe:** user still can preview images on *Attachments* page but not at the test view page

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome
 - Browser 105.0.5195.102 (Official Build) (arm64)
 - Application: production

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin! The issue was fixed. The fix will be added to the upcoming release.

https://user-images.githubusercontent.com/77803888/193052494-9456242a-e6a2-4807-aef3-30f0a0effa08.mp4
