### ISSUE TITLE
Left main navigation is not adjustable

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#612]
**Describe the bug**

Left main navigation (in window with lower height - items can be pushed outside of viewport but navigation is not scrollable)

![CleanShot 2022-09-27 at 10 05 06@2x](https://user-images.githubusercontent.com/77803888/192457047-fe0ef7b8-a284-4e6a-bcac-8f8fb87d98ea.jpg)

**Comment by littlefrontender** [comment]
@TetianaKhomenko  this issue doesn't reproduce yet

**Comment by TetianaKhomenko** [comment]
the issue was fixed with one of previous releases. 
closing as fixed
