### ISSUE TITLE
Mark test as "Started" during ongoing test run and add statistics to ongoing test executions

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#615]
Problem - test runs executed in many days, need to track execution progress from day to day.
Goal - need to see extra information what tests started and differentiate tests from not completed.

So need to add ability:

- [ ] mark test case somehow as started
- [x] add extra statistics to ongoing windows to show (started tests, pending tests)
- [ ] add filter and sorting by date time
- [x] add run statistics for ongoing test runs (passed, failed, skipped, started, pending) in list view

![Google Chrome-Runs - Testomat io-2022-10-06 at 20 53 02@2x](https://user-images.githubusercontent.com/325722/194395197-f7af93b8-0426-460d-80b1-7f7e0c0b90c4.png)

![Google Chrome-Runs - Testomat io-2022-10-06 at 20 55 12@2x](https://user-images.githubusercontent.com/325722/194395675-0896461a-7744-4a9c-8bd4-5d035c397688.png)

**Comment by poliarush** [comment]
Client original question - **How can we see the execution report for manual without completing the test run?**

**Comment by TetianaKhomenko** [comment]
the feature was implemented

**Comment by poliarush** [comment]
@TetianaKhomenko it's not implemented fully, need to divide tickets 

<img width="591" alt="Google Chrome-Mark test as Started during ongoing test run and add statistics to ongoing test executions · Issue #615 · testomatioapp-2022-11-09 at 22 22 29@2x" src="https://user-images.githubusercontent.com/325722/200944512-bf50a183-3dbd-4458-80e5-796c6df92756.png">

**Comment by poliarush** [comment]
that's moved to the next sprint as we don't have capacity to close ticket in this release
