### ISSUE TITLE
ESC(close) button is not clearly noticeable to clients

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#616]
Can we make the ESC(close) button highlighted on the pages right now its kind of invisible ( a border or a different color could help)

![Google Chrome-Tests - Testomat io-2022-10-06 at 21 02 28@2x](https://user-images.githubusercontent.com/325722/194397109-4cc15ccf-bdc7-48c6-ab2a-80749a0aa45c.png)

**Comment by TetianaKhomenko** [comment]
implemented.

![Image](https://user-images.githubusercontent.com/77803888/197146756-cc0a880a-ffa9-43a8-8e6b-d7baf5b4759e.jpg)
