### ISSUE TITLE
UI is not refreshed automatically when we Copy test suite from one folder to another

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#617]
1. copy tests from to some folder
2. go to folder and check it
3. no items will appear there until you refresh a page

**Comment by poliarush** [comment]
question from client - How can the UI be refreshed automatically when we make changes (Copy from one folder to another)?

**Comment by littlefrontender** [comment]
Что если после копирования мы будем юзера отправлять в папку с тестом?

https://user-images.githubusercontent.com/79913874/215791481-415fa267-f5a7-474d-8b7a-a64f4cba9f89.mov

в самом дереве все обновляется кроме счетчика тестов
