### ISSUE TITLE
 Tags autocomplete stopped working

### ISSUE THREAD

**Issue by tikolakin** [testomatio/app#624]
**Describe the bug**
Tags autocomplete is not shown

**To Reproduce**
Given I have tests with tag ex. tag like @org:test
when create/edit a test
And start typing tag name ex. @org
Actual - I see no tags automatic suggestions

**Expected behavior**
expect to see all tags that start with @org
see feature in action on the demo
https://www.youtube.com/watch?v=2-gMXd9i-cc

**Screenshots**
![image](https://user-images.githubusercontent.com/5860505/197736577-4b657c99-dc08-491e-a7df-b211f16830c7.png)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome
 - Browser Version 106.0.5249.119 
 - Application: production

**Additional context**
I reported this issue in the support chat earlier but it seems to be not been fixed yet

**Comment by tikolakin** [comment]
Works on test edit screen
![image](https://user-images.githubusercontent.com/5860505/197752784-ac7dd555-10ad-491b-80ae-136227700236.png)

**Comment by TetianaKhomenko** [comment]
we can improve this with one of our future releases

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin this issue was fixed and the feature will be added to the upcoming release 🥳
