### ISSUE TITLE
Show test tags in the Run view

### ISSUE THREAD

**Issue by tikolakin** [testomatio/app#625]
**Is your feature request related to a problem? Please describe.**
When I execute a test case within a Run view I cannot see what tags a particular test case has. So I always have to open an individual test case to review its tags

**Describe the solution you'd like**
When I execute a test case within a Run view I would like to see exactly the same tags I can see on the test case view

**Describe alternatives you've considered**
Can't think of an alternative solution

**Additional context**
<img width="1281" alt="Screenshot 2022-11-03 at 12 13 42" src="https://user-images.githubusercontent.com/5860505/199974034-8c70c313-cebd-49c0-8f8f-ec9550366055.png">
<img width="2461" alt="Screenshot 2022-11-03 at 12 13 59" src="https://user-images.githubusercontent.com/5860505/199974058-2753085d-38bd-465d-8298-327ee3df0e07.png">

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin! This feature was implemented and will be added to the upcoming release.
