### ISSUE TITLE
Unable to link a test or suite from Jira plugin

### ISSUE THREAD

**Issue by Jose-Benitez** [testomatio/app#626]
**Describe the bug**
It launches an error when linking a test from Jira plugin

**To Reproduce**
1. Go to Jira issue and Testomat section
2. Login to Jira's plugin
3. Click on the three-dots menu
4. Click on Link test
5. Select your desired suite of tests from the dropdown menu
6. Click on LINK button on the test you wish to link
7. An error that says: `undefined method `public_uid' for nil:NilClass` appears. 

**Expected behavior**
I expect the test to be linked

**Screenshots**
https://user-images.githubusercontent.com/117646825/200316860-1a4879f2-25cb-492f-9d05-b5c91a932469.mov

**Desktop (please complete the following information):**
 - Browser: Chrome and firefox
 - Browser Version: Chrome 107.0.5304.87 and Firefox 106.0.5 
 - Application: prod

**Additional context**

**Comment by TetianaKhomenko** [comment]
closing the issue as fixed. @Jose-Benitez please re-open if it re-occurs for you.
