### ISSUE TITLE
JIRA's configuration is not kept

### ISSUE THREAD

**Issue by Jose-Benitez** [testomatio/app#627]
**Describe the bug**

**To Reproduce**
1. Go to JIRA integration setup https://app.testomat.io/projects/<your project>/settings/jira
2. Click on Configure Jira Integration
3. Full-fill all required fields. 
4. Click on save button
5. Close the pop up screen
6. The just created configuration gets lost. 

**Expected behavior**
Configuration is saved and can be edited. 

**Screenshots**
After doing the setup and clicking on save, configuration's link is visible. 
![image](https://user-images.githubusercontent.com/117646825/200318760-b53c113f-a2e7-41cf-8950-e6175874b685.png)

However, after clicking on the 'X' to close the pop up. The configuration disappears. 

![image](https://user-images.githubusercontent.com/117646825/200319106-8e760012-abef-4749-8096-eb1b0eab0724.png)

**Desktop (please complete the following information):**
 - OS: any
 - Browser any
 - Browser any
 - Application: [production or beta] 

**Additional context**
When clicking on Save button a message is visible and says: 
`Error: Jira was succesfully connected but webhook that unlinks deleted issues was not set`

I was said this is expected message however I wanted to mention it in case was relevant.

**Comment by poliarush** [comment]
implemented
