### ISSUE TITLE
Error on Runs page when branches are not available

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#629]
`Error: Branches is not available in your subscription plan` when opening Runs page on Professional plan

**To Reproduce**
1. create a company (trial plan)
2. create a project within this company
3. create a branch
4. create a suite with tests in this branch
5. launch and finish these tests within the branch 
6. upgrade to Professional plan
7. open this project
8. go to Runs page see the error

**Expected behavior**
This error should not be shown to users on the Runs page.
This error can be shown only on the test level in the Run Report.

**Screenshots**

![CleanShot 2022-11-11 at 09 00 39@2x](https://user-images.githubusercontent.com/77803888/201282654-bc3e0d00-e473-48a4-8d61-ef8076524ffb.jpg)

**Comment by poliarush** [comment]
@DavertMik is this fixed on beta? right?

**Comment by TetianaKhomenko** [comment]
@DavertMik still an issue

https://user-images.githubusercontent.com/77803888/210374125-d8a59380-280e-4105-b2c9-2ff2ab2860fa.mp4

**Comment by TetianaKhomenko** [comment]
will retest after fixing this #1888

**Comment by TetianaKhomenko** [comment]
fixed
