### ISSUE TITLE
Report is ignored using REST helper from CodeceptJS

### ISSUE THREAD

**Issue by AngelM-8Belts** [testomatio/app#631]
**Describe the bug**
Report is ignored when a test using REST helper from CodeceptJS (API Testing) is executed. Results are not reflected in "Runs" tab in Testomat.io.

**To Reproduce**
1. Have a CodeceptJS project using Gherkin (BDD) and REST Helper, connected with Testomat.io
2. Execute a test (or a set of tests)
3. (Optional) Execute the same test or set of tests with the prefix `npx start-test-run -c` . In this case, a message `[TESTOMATIO] ⚠️  Runner exited with 0, report is ignored` will be shown by console
4. No testomat.io process is started, therefore no reports are collected in the run. If we have executed the command `npx start-test-run -c` (as described in step 3) this process does start, but it ends with the message `[TESTOMATIO] ⚠️  Runner exited with 0, report is ignored` and no information is shown in "Runs" tab in Testomat.io.

**Expected behavior**
 Reports are generated and executions and results can be seen in "Runs" tab in Testomat.io.

**Screenshots**
If applicable, add screenshots or video to help explain your problem.

https://user-images.githubusercontent.com/112387654/201665134-130f86d8-7e67-4d74-94f3-2fca516e0e68.mov

https://user-images.githubusercontent.com/112387654/201665394-69c9a944-fc42-4b74-a9e8-2a513b8d5609.mov

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.0.1

**Additional context**
 - CodeceptJS 3.3.6
 - Testomat.io Reporter 0.7.0

**Comment by heidelmann91** [comment]
We are having the same problem in our setup! Would be really great to have this fixed! Thanks a lot!

**Comment by poliarush** [comment]
@AngelM-8Belts i don't see on video how do you pass API project key to reporter. Please clarify

**Comment by poliarush** [comment]
@heidelmann91 could you please video to show your defect

**Comment by AngelM-8Belts** [comment]
Hello @poliarush . API key is passed via env variable, loaded from an env file and used in the testomatio plugin in `codecept.conf.js`

![Captura de pantalla 2022-11-17 a las 10 23 05](https://user-images.githubusercontent.com/112387654/202407068-c3f6f1a2-73ba-4110-bcf9-194dfec93b3c.png)

**Comment by poliarush** [comment]
got it, thanks for clarification, just want to be sure you're passing it, 
we're taking this item for this sprint, the release date of this sprint is next week, I guess more or less next Wednesday

**Comment by AngelM-8Belts** [comment]
Great, thank you very much for your help :)

**Comment by AngelM-8Belts** [comment]
Hello @poliarush @DavertMik . Any news on this issue? Is there any possibility of having this bug fixed for the next sprint?

**Comment by poliarush** [comment]
@DavertMik had some problem to identify an issues,
@DavertMik please ask @AngelM-8Belts for any details, if necessary, please schedule a call

**Comment by DavertMik** [comment]
@AngelM-8Belts sorry, I couldn't see any issues in your video and can't say what may go wrong
maybe we could have a call next week to figure out what can be wrong?

**Comment by AngelM-8Belts** [comment]
Hi @DavertMik @poliarush . Sorry for my late reply, I just came back from vacations. Luckily, we found the cause. It was a configuration problem in our project. Now the reports are being generated correctly. You can close this ticket.
