### ISSUE TITLE
State % of completeness for ongoing run on progress bar 

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#632]
User stated:
> A tiny thing regarding the progress bar you’ve added, can it also display the cover percentages in the run also it shows for example in your video 23/28 tests and not also the percent.

![Google Chrome-Runs - Testomat io-2022-11-15 at 15 19 12@2x](https://user-images.githubusercontent.com/325722/201942608-159736d2-0a4c-4c91-8859-079e12ccf468.png)

**Comment by poliarush** [comment]
> A tiny thing regarding the progress bar you’ve added,  can it also display the cover percentages in the run also it shows for example in your video 23/28 tests and not also the percent.

**Comment by TetianaKhomenko** [comment]
implemented
