### ISSUE TITLE
Playwright parameterized tests not recognized

### ISSUE THREAD

**Issue by nathaner** [testomatio/app#641]
**Describe the bug**
When using Playwright, parameterized tests are not recognized. https://playwright.dev/docs/test-parameterize

**To Reproduce**
1. Use Playwright example for parameterized tests
```ts
// example.spec.ts
const people = ['Alice', 'Bob'];
for (const name of people) {
  test(`testing with ${name}`, async () => {
    // ...
  });
  // You can also do it with test.describe() or with multiple tests as long the test name is unique.
}
```
2.Import the tests: `npx check-tests@latest Playwright "**/*{.,_}{test,spec}.ts" --typescript`

Tests are not recognized: only one test case is added with the name `testing with ${name}`
![image](https://user-images.githubusercontent.com/25883088/205032831-c96b6ec8-370b-497e-9472-23a76f504d48.png)

**Expected behavior**
Each parameterized test should be added. In the example, we should have 2 tests:
- testing with Alice
- testing with Bob

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser chrome
 - Browser Version 107.0.5304.121 (Official Build) (64-bit)
 - Application: production

**Comment by DavertMik** [comment]
Well, this is correct behavior

We can't add all possible cases on the static analysis stage as we don't execute tests. So we add parameterized tests. Parameters will be added after the tests is executed. 

Parametrized test in Testomat.io is treated as one test with multiple examples.

The thing is you can have over 1000 parameters for one test so adding all of them into system won't make them maintainable.
