### ISSUE TITLE
Cannot delete a RunGroup

### ISSUE THREAD

**Issue by nathaner** [testomatio/app#644]
**Describe the bug**
After creating a RunGroup, I cannot delete it.

**To Reproduce**
1. Go to Runs
2. Click on New Group
3. Create a new RunGroup
4. Open the new RunGroup
5. Delete the RunGroup
The group cannot be deleted: an error is shown (_Error: Rungroup #b4074a63 was not found in this project. It could be deleted or not accessible anymore._)

**Expected behavior**
I should be able to delete a RunGroup.

**Screenshots**
![image](https://user-images.githubusercontent.com/25883088/205999607-1ca84b47-be98-4954-8e07-82f077acb10c.png)

**Comment by TetianaKhomenko** [comment]
Hi @nathaner the issue was fixed. The fix will be added to the upcoming release.

**Comment by nathaner** [comment]
Thanks a lot!

**Comment by nathaner** [comment]
Hi @TetianaKhomenko, do you know when will be the next release?

**Comment by TetianaKhomenko** [comment]
Hi @nathaner! We plan to publish it approximately next week.

**Comment by nathaner** [comment]
Ok thanks a lot

**Comment by nathaner** [comment]
I just tested and it worked, thanks :)
