### ISSUE TITLE
Nesting a list inside a numbered list resets numbering

### ISSUE THREAD

**Issue by alitheg** [testomatio/app#645]
**Describe the bug**
Can't nest unordered list inside ordered list without resetting numbering

**To Reproduce**
1. Edit a test
2. Create an ordered list with a nested unordered list using:
```
1. Step 1
* Inner step
* Inner step
3. Step 2
4. Step 3
```

**Expected behavior**
Should render the numbers contiguously, as written:
![Screenshot 2022-12-08 at 09 19 46](https://user-images.githubusercontent.com/450789/206407811-5ac9e37a-5f3c-4bfd-820c-705fff49668b.png)

**Screenshots**
What actually happens:
![Screenshot 2022-12-08 at 09 22 02](https://user-images.githubusercontent.com/450789/206408106-c3bc0f91-703c-4867-926d-445c51b4bb81.png)
Note that the inner list has broken the numbering of the outer list

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Browser Version: 107.0.1
 - Application: production

**Additional context**
Pasting the above code into another markdown editor, ie. this one, or the one on https://markdownlivepreview.com/ renders as expected.

**Comment by poliarush** [comment]
@DavertMik 
do we have support nested list ? 
also, how does it look with step management to step database? 
will nested list brake some logic to parce steps?

**Comment by poliarush** [comment]
@alitheg 

To nest one list within another, indent each item in the sublist by four spaces. 

https://www.markdownguide.org/basic-syntax/#unordered-lists

```
### Steps with unordered lists
* First item
* Second item
* Third item
    * Indented item
    * Indented item
* Fourth item

### Mixed steps with unordered and ordered lists
* First item
    1. Indented item
    1. Indented item
* Second item
* Third item
    1. Indented item
    1. Indented item
* Fourth item

### Mixed steps with ordered and unordered lists
1. First item
    * Indented item
    * Indented item
1. Second item
1. Third item
    * Indented item
    * Indented item
1. Fourth item
```

that will give you 

![Google Chrome-Tests - Testomat io-2022-12-08 at 10 44 00@2x](https://user-images.githubusercontent.com/325722/206413669-c1747b2d-c9ae-4e4a-b897-55f855addfc1.png)

so @alitheg please use this format

```
1. First item
    * Indented item
    * Indented item
1. Second item
1. Third item
    * Indented item
    * Indented item
1. Fourth item
```

**Comment by poliarush** [comment]
@alitheg please let me know if this resolve your issue and we can close the ticket
