### ISSUE TITLE
Run launch time does not match users' timezone

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#647]
**Describe the bug**
This issue can mislead users as far as difference in server time and users' can be really huge (e.g. 8-10 hours).

**To Reproduce**
1. go to User Account page
2. set up a timezone of your choice
3. open a project
4. go to Runs page
5. launch a manual/automated test run
6. see the started at time differs from the timezone

**Expected behavior**
Run launch time matches users' timezone.

**Screenshots**
![CleanShot 2022-12-12 at 12 18 36@2x](https://user-images.githubusercontent.com/77803888/207021276-c4f49447-e6e2-4604-bedc-557885eb4883.jpg)

**Comment by Chiel-CBTC** [comment]
I'm guessing that the timestamps on the left are UTC timestamps that are received from the client where the tests were executed (e.g. an Azure pipeline). The timestamps on the right look like local timestamps. If this is the case, maybe some explanation on the run-page is enough. Or timestamps on the left should be converted to local times to prevent confusion.

**Comment by poliarush** [comment]
related to https://github.com/testomatio/app/issues/1058

**Comment by TetianaKhomenko** [comment]
Hi @Chiel-CBTC! We will add the Timezone setting to Project > Settings > Project > Administration > Timezone. You will need to set a timezone so new runs will have the right time. The feature will be published in the next release.

![image](https://github.com/user-attachments/assets/d74d095d-7d5b-428b-9aea-661574a02392)
