### ISSUE TITLE
Add scroll to the right for logs 

### ISSUE THREAD

**Issue by bheemreddy181** [testomatio/app#651]
![image](https://user-images.githubusercontent.com/101338506/207209449-821b8fba-18c7-4b65-b3f3-572e377773db.png)

Add scroll to the right

**Comment by TetianaKhomenko** [comment]
Hi @bheemreddy181! The issue was fixed and will be added to the upcoming release. Attaching short video for the fix below

https://user-images.githubusercontent.com/77803888/208087470-f2da3a82-2435-4ade-9efe-f034403feff0.mp4
