### ISSUE TITLE
bug: ms teams doesn’t have reporting notifications

### ISSUE THREAD

**Issue by MickyThunder** [testomatio/app#655]
MS teams integration is not working as expected, Cant see any reports posted in the channel

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/84340730/207496950-b3a64236-a3f0-4b2e-8c92-ebbea2831c74.png">

**Comment by poliarush** [comment]
@MickyThunder could you please attach screenshot for reporting notification configuration

**Comment by MickyThunder** [comment]
@poliarush here is the screen shot
<img width="2125" alt="image" src="https://user-images.githubusercontent.com/84340730/210303575-3b456e0f-90ce-4bc5-9d47-4475c0dcc67f.png">

**Comment by poliarush** [comment]
@MickyThunder 

your rule expression is wrong, 

![Google Chrome-210303575-3b456e0f-90ce-4bc5-9d47-4475c0dcc67f png (4250×2198)-2023-01-05 at 14 28 13@2x](https://user-images.githubusercontent.com/325722/210791003-ef598892-e852-4d8d-aad0-2135968740d7.png)

it should be for example
```
automated and has_failed
```

**Comment by poliarush** [comment]
@MickyThunder we're closing this ticket, please reopen it's reproduced with "automated and has_failed"
