### ISSUE TITLE
Cannot delete a run group

### ISSUE THREAD

**Issue by alexandrchumakin** [testomatio/app#662]
**Describe the bug**
If I try to delete a run group it throws the error "Rungroup #groupId was not found in this project..."

**To Reproduce**
1. Go to Runs
2. Create a new group with "Build" group type 
3. Try to delete this group

**Expected behavior**
Group should be deleted successfully.

**Screenshots**
<img width="423" alt="image" src="https://user-images.githubusercontent.com/8362164/211833336-c32c4be1-07ef-4443-8557-b64f0a5a2339.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome & safari
 - Browser Version Chrome 108 (arm64)  & Safari 16.2
 - Application: production

**Comment by TetianaKhomenko** [comment]
closing as fixed

**Comment by poliarush** [comment]
https://github.com/testomatio/app/issues/644
