### ISSUE TITLE
Search tests by tags in JIRA plugin

### ISSUE THREAD

**Issue by wjaros** [testomatio/app#665]
At the moment you cannot search for automated test by a tag assigned to it. It is bit frustrating, please implement it

![image](https://user-images.githubusercontent.com/93591284/214281846-6af9fe79-119e-4958-9ae6-6ceb8f1514bd.png)
![image](https://user-images.githubusercontent.com/93591284/214281992-d4408ee0-535b-4099-8b22-2b740f0b5c47.png)

**Comment by TetianaKhomenko** [comment]
@wjaros can you try searching with @ sign?  for example `@T22091b4`

**Comment by wjaros** [comment]
That works! Thanks for quick response, in that case I guess the problem lays here:
![image](https://user-images.githubusercontent.com/93591284/214283562-ae71e22d-af2a-4954-97d1-93b8c7c5f1ec.png)

should look like here:
![image](https://user-images.githubusercontent.com/93591284/214283737-22984cbc-2764-4865-8095-f59170e2c8c3.png)

**Comment by TetianaKhomenko** [comment]
@wjaros thank you for the info!

**Comment by wjaros** [comment]
Hey, I have just tried to search test by tag with @ in the Jira app, it does not work:
![image](https://user-images.githubusercontent.com/93591284/214531389-5306bdfa-3059-448b-87e1-497b471909ed.png)

**Comment by TetianaKhomenko** [comment]
The issue was fixed. The fix will be published in the upcoming release. @wjaros test ids should be provided with @ sign.
