### ISSUE TITLE
Launch tests by IMS links and stories

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#672]
**Is your feature request related to a problem? Please describe.**

Many users use different IMS in their workflow. So they need to track IMS stories and tests linked to them. Users need to have the option to  Launch tests linked to specific Links.

**Describe the solution you'd like**

1. Add an option to UI to show a list of links on the project. 
2. Open the Detail View screen with the list of IMS links.
3. Show all links from the project with linked tests and suites.
4. Show the number of linked tests for each IMS link.
5. Show the Launch button for each IMS link.
6. On Launch show pop-up with Runs options according to types of linked tests: Run manually, Run in CI, Mixed Run.
7. Show Launch and Advanced Settings buttons.
8. On run confirmation create a generated Plan and launch Test Run.

**Additional context**
We can use the same schema as we have for Tags

![telegram-cloud-photo-size-2-5431787295087904617-y](https://user-images.githubusercontent.com/77803888/218712884-ce713f4e-9e0d-4cdc-950b-b0aafdad8d30.jpg)

![telegram-cloud-photo-size-2-5431787295087904637-y](https://user-images.githubusercontent.com/77803888/218714260-71730cc5-bbfc-42e0-9e2e-0ce7b3b3d503.jpg)

![telegram-cloud-photo-size-2-5431787295087904638-y](https://user-images.githubusercontent.com/77803888/218714390-686cbb08-d52c-4351-89da-95141bbf807d.jpg)

**Comment by littlefrontender** [comment]
@DavertMik please make endpoint for all issues

**Comment by poliarush** [comment]
needs for curo

**Comment by Fro0z1k** [comment]
@littlefrontender FYI
index => /api/:project/ims/issues - list of issues
show => /api/:project/ims/issues/:id - tests list of issue

Example responses:
INDEX:
{"data"=>[{ "id"=>"56",  "type"=>"issue",  "attributes"=>{ "id"=>56,  "title"=>"arcu adipiscing molestie",  "test-count"=>9 } },  { "id"=>"57",  "type"=>"issue",  "attributes"=>{ "id"=>57,  "title"=>"eget vulputate ut ultrices",  "test-count"=>11 } } ]} 

SHOW:
{"data"=> [{"id"=>"a076da00", "type"=>"test", "attributes"=> {"labels"=>nil, "issues"=>nil, "tags"=>[], "jira_issues"=>nil, "is_branched"=>false, "is_detail"=>false, "title"=>"sapien a libero nam dui proin leo odio porttitor", "state"=>"manual", "emoji"=>nil, "file"=>nil, "priority"=>"normal", "sync"=>true, "run-statuses"=>[], "assigned-to"=>nil, "created-by"=>2, "created-at"=>"2023-03-24T08:29:32.521Z", "updated-at"=>"2023-03-24T08:29:32.521Z", "saved-in-branch?"=>false, "to-url"=>"http://127.0.0.1:3000/projects/testomatio/test/a076da00", "has-examples"=>nil, "params"=>[], "public-title"=>"sapien a libero nam dui proin leo odio porttitor", "description"=>"sollicitudin vitae consectetuer eget rutrum at lorem", "code"=>nil, "suite-id"=>"16cec857", "position"=>1, "import-id"=>nil, "forks-count"=>nil, "attachments"=>nil}, "relationships"=>{}}]}

**Comment by littlefrontender** [comment]
@Fro0z1k  please add search by title

for example  /api/:project/ims/issues?query={search}

**Comment by DavertMik** [comment]
@littlefrontender merged https://github.com/testomatio/testomatio/pull/2746

**Comment by TetianaKhomenko** [comment]
the feature was implemented
