### ISSUE TITLE
Test Run: open next test if current is passed

### ISSUE THREAD

**Issue by vipovsk** [testomatio/app#677]
**Is your feature request related to a problem? Please describe.**
When I click pass on a test in a test run, the test becomes marked and that's it. So I have to do an extra click to proceed to next test in the test run.

**Describe the solution you'd like**
Open next test if current is passed

**Describe alternatives you've considered**
I like how Ctrl + ENTER works in test runs and that's what I'm looking for

**Additional context**
Test rail had this functionality and it was very useful

**Comment by poliarush** [comment]
@littlefrontender need to think it may be it's good to make a per user configuration for such behaviour

**Comment by poliarush** [comment]
that's implemented already with fast forwarding 



![Image](https://github.com/testomatio/app/assets/325722/2ab7d04f-93b5-4e3b-9853-cca6bab82d52)
