### ISSUE TITLE
Tests: return to the suite view to proceed editing tests

### ISSUE THREAD

**Issue by vipovsk** [testomatio/app#678]
**Is your feature request related to a problem? Please describe.**
Often I (1) open a suite in Tests (2) open a test (3) Edit the test (4) save (5) click 'Close'. Then I appear at the test view page and the only option to exit the test view is 'Esc' button that closes the view and the suit view. What I would really appreciate is a way to return to the suite view to proceed editing tests.

**Describe the solution you'd like**
As I see it: (1) 'Save' working as Save and Close - should return me to test view (2) Having a 'Close' button on test view to return me to suite view (3) perhaps an additional button 'Next test' on test view would help me a lot - this would open next test of the suite if there's some

**Comment by littlefrontender** [comment]
@vipovsk Is switching between tests using the keyboard okay for you?

https://user-images.githubusercontent.com/79913874/222173124-245f67ba-41de-4598-92d8-09c5d1c47952.mov

**Comment by vipovsk** [comment]
Yes
--
Sent from Mail.ru app for Android Wednesday, 01 March 2023, 08:43PM +06:00 from Valentin Tsvetkov  ***@***.*** :

**Comment by TetianaKhomenko** [comment]
Hi @vipovsk! the issue was implemented by arrow buttons. The feature will be published in the next release.

https://user-images.githubusercontent.com/77803888/228868377-5f2e9b13-d759-466a-86a9-1a1fee01fb5f.mp4
