### ISSUE TITLE
RunGroup with sub-RunGroups is still considered empty

### ISSUE THREAD

**Issue by isaac-pa-ma** [testomatio/app#682]
**Describe the bug**
If I have a run group that contains more run groups inside instead of single runs, it says the RunGroup is empty.
Only if there's a single run inside a group it'll no longer say its empty.

**To Reproduce**
1. Go to 'Runs'
2. Click on 'New Group' & Create a new run group
3. Add Manual Run with multiple environments (Manual run is added as a RunGroup, since it has multiple envs)
4. The RunGroup is still considered empty, even though it has sub-RunGroups

**Expected behavior**
Once a RunGroup has sub-RunGroups, it is no longer considered empty.

**Screenshots**
![Screen Shot 2023-02-28 at 11 53 58](https://user-images.githubusercontent.com/106246526/221871239-e6582b2c-0da0-4bd5-aef7-52866975dda5.png)
![Screen Shot 2023-02-28 at 11 56 21](https://user-images.githubusercontent.com/106246526/221871975-510b145e-8c8d-4503-b744-9113b6eec584.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Browser Version: 110.0.5481.100
 - Application: Production

**Comment by TetianaKhomenko** [comment]
Hi @isaac-pa-ma! The issue was fixed and will be published in the next release

![CleanShot 2023-03-10 at 13 52 33@2x](https://user-images.githubusercontent.com/77803888/224309435-a1ec7b08-d2c0-4f02-bba1-3babcdff37f9.jpg)
