### ISSUE TITLE
Error when saving tests in Suite Bulk edit

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#688]
**Describe the bug**
User can't save the bulk edit an error appears and endless loading state

here is a link to appsignal record
https://appsignal.com/testomatio/sites/611d2c787478202391730cb0/exceptions/incidents/1187

**Expected**
1. UI should not freeze
2. provide an error message with a relevant description

**Screenshots**

![image](https://user-images.githubusercontent.com/77803888/224025332-aed32ed4-a973-4551-b74d-af9c321a7e50.png)

https://user-images.githubusercontent.com/77803888/224029797-fb2529d5-48d8-4827-8282-fb8d71f5dfa5.mp4

**Comment by DavertMik** [comment]
Can't reproduce
