### ISSUE TITLE
Icon are not shown in run report

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#692]
**Describe the bug**
Original request: 

I use **Arch linux** and I know I had that issues with the icons on [testomat.io](http://testomat.io/) previously (but I fixed it by installing some fonts)

![image](https://user-images.githubusercontent.com/77803888/225734917-c3ba04c1-3872-470c-b6a6-6ab10497dab5.png)

**Comment by poliarush** [comment]
https://testomatio.slack.com/archives/C04QUC4UFBK/p1678983374891039
