### ISSUE TITLE
Hotkeys for Test and Suite creation

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#694]
**Is your feature request related to a problem? Please describe.**

Sometimes you need to add a minimum description to the title and this can be done separately by each test case.

It will be useful to have hotkeys to create a Suite and Test Cases, quick change of suite type (Folder or File). 

Also, we can add shortcuts for other actions in the test Editor.

**Comment by AlexLAA** [comment]
Could be very useful when first you need to write some cases with description and then start to automate it.
Four Suites it's not so Critical, but for Test Cases it should be)

**Comment by TetianaKhomenko** [comment]
The flow for test creation should be:

Shift-Cmd-S => Test title => TAB => Description => Shift-Cmd-S

**Comment by TetianaKhomenko** [comment]
1. Add the same flow for suite creation and editing :

> The flow for test creation should be:
> 
> Shift-Cmd-S => Test title => TAB => Description => Shift-Cmd-S

2. Add a shortcut for new **test** and **suite** creation directly from the Tests page.
2.1. for new test show pop-up to pick a suite
2.2. for new suite show New suite detail view

**Comment by TetianaKhomenko** [comment]
Implemented. Moving to the next sprint for further improvement:

> 2. Add a shortcut for new test and suite creation directly from the Tests page.
2.1. for new test show pop-up to pick a suite
2.2. for new suite show New suite detail view

**Comment by TetianaKhomenko** [comment]
implemented

**Comment by maxkryvoshyya** [comment]
URL: https://docs.testomat.io/getting-started/test-design/#creating-a-test
