### ISSUE TITLE
Documentation issue for Importing using CSV

### ISSUE THREAD

**Issue by TheZZ13** [testomatio/app#696]
**Describe the bug**
"critic" should be "critical" 

**To Reproduce**
1. Go to https://docs.testomat.io/getting-started/import-tests-from-csvxls/#create-custom-xls-for-testomat-io
2. View for Priority row, Content column.

**Expected behavior**
"Critic" should be "Critical".

**Screenshots**
<img width="800" alt="Screenshot 2023-03-22 at 10 22 19 AM" src="https://user-images.githubusercontent.com/36581640/226971519-a21fc5b9-ad0b-4285-9a2f-05919ef89ab6.png">

**Desktop (please complete the following information):**
 - OS: Mac OS, Ventura 13.1 
 - Browser Chrome 
 - Browser Version 111
 - Application: Production

**Comment by TetianaKhomenko** [comment]
Hi @TheZZ13! the typo was fixed
