### ISSUE TITLE
Ability to open Playwright Trace from Testomat.io

### ISSUE THREAD

**Issue by itz4blitz** [testomatio/app#698]
**Is your feature request related to a problem? Please describe.**
When triaging tests, we need to sometimes view the trace to diagnose why it failed. In Playwright we can click on the image icon and it opens. In Testomat.io we have to download the artifact and then upload it to trace.playwright.dev

**Describe the solution you'd like**
When I open the artifact, I have an option to open the trace in Playwright's trace viewer as well as the option to download the trace locally.

https://imgur.com/Z9th3jG

https://i.imgur.com/Z9th3jG.mp4

**Comment by poliarush** [comment]
we can probably generate a link to Playwright trace viewer for publicly uploaded artifacts
![image](https://user-images.githubusercontent.com/325722/228366126-29619645-10f1-4bce-be5c-56c6fdbeec5d.png)

**Comment by DavertMik** [comment]
Shoud work on our S3 bucket

But it is recommended to open and save S3 config in Settings > Artifacts



![Image](https://github.com/testomatio/app/assets/220264/8c1b629e-bcd6-44b6-8313-049f004384db)

Evne if you already config there you need to re-save it

**Comment by TetianaKhomenko** [comment]
@DavertMik need to improve behavior for private artifacts

**Comment by TetianaKhomenko** [comment]
The feature was implemented and will be published in the next release.

![Image](https://github.com/testomatio/app/assets/77803888/8ab48d49-aaff-4c09-bb67-5459c0cff632)

**Comment by poliarush** [comment]
@itz4blitz is this expected ?

https://github.com/testomatio/app/assets/325722/43f6b862-cd03-4b23-85ba-dd550ec3b0cd
