### ISSUE TITLE
Support creating Bug tickets in Azure DevOps based on failure rules 

### ISSUE THREAD

**Issue by bheemreddy181** [testomatio/app#701]
Support creating Bug tickets in Azure DevOps based on failure rules

**Comment by poliarush** [comment]
@DavertMik to whom should I assign this ticket?

**Comment by poliarush** [comment]
@bheemreddy181 please clarify what failures rules do you need?
Also do you need to auto-create defect feature for each failure or for all failures that will met rules.

**Comment by bheemreddy181** [comment]
Auto create defects for each failure as long as they are unique

**Comment by bheemreddy181** [comment]
@poliarush does that seems reasonable?

**Comment by poliarush** [comment]
We can't control defect is unique or no, by what criteria? title only?

What if we add feature for test report "Create defect for all failures".
Then you go to specific test run, check it, execute this functions and get the list of defect. 
Defects auto-creation may be too aggressive strategy because of test flakiness.
What do you think?

If not, need to understand what failure rules are you going to use? Only test passed or failed, or matching some text by stack tracking, etc?!

**Comment by bheemreddy181** [comment]
I feel we are fine with Auto creation of defects for that project where ever we have rules, we are confident of not hitting the flaky suite

**Comment by poliarush** [comment]
so will it be only status to be check in failure rule? 
namely, if test failed then create a auto-create defect,
no other rules will be applied, right?

**Comment by bheemreddy181** [comment]
Yes if the test is failed create the defects yes @poliarush

**Comment by bheemreddy181** [comment]
@poliarush  any updates on this ?

**Comment by poliarush** [comment]
https://testomatio.slack.com/archives/C03DY1CG353/p1687177190335619?thread_ts=1680543867.027529&cid=C03DY1CG353

> Michael Bodnarchuk
>   [4 days ago](https://testomatio.slack.com/archives/C03DY1CG353/p1687177190335619?thread_ts=1680543867.027529&cid=C03DY1CG353)
> [@Bheem](https://testomatio.slack.com/team/U02M7DZFMSS)
>  Hi, I'm not sure I correctly understood the business case.
> What I mean that we can attach create Azure DevOps ticket the same way as we do it for Jira
> (see screenshot)
> So you can define a rule where you create a Bugreport if a Run has failed
> This Bugreport will include a list of failed tests
> We can't automatically create a Bugreport on each failed testcase.
> Imagine you do 10 runs/day and you have 10 failures (same ones)
> This will lead to 100 open bugreports
> And the worst, we don't have anything to make it work
> So my proposal is to use current functionality, to create a Bugreport for a failed test run the same way as we do it for Jira. This feature is simple and we can make it in next release
> This file was deleted.
> 
> 
> 
> Michael Bodnarchuk
>   [4 days ago](https://testomatio.slack.com/archives/C03DY1CG353/p1687177237260989?thread_ts=1680543867.027529&cid=C03DY1CG353)
> image.png
>  
> image.png
> 
> 
> 
> 
> 
> Bheem
>   [17 hours ago](https://testomatio.slack.com/archives/C03DY1CG353/p1687450688627749?thread_ts=1680543867.027529&cid=C03DY1CG353)
> That should be fine if you can replicate the Jura functionality 
> [@Michael Bodnarchuk](https://testomatio.slack.com/team/U01449LP96Y)

**Comment by TetianaKhomenko** [comment]
Hi @bheemreddy181 ! The feature was implemented and will be published in the upcoming release.


![Image](https://github.com/testomatio/app/assets/77803888/cf380989-826e-4717-a390-efb7d032a264)


![Image](https://github.com/testomatio/app/assets/77803888/6ad07bf9-40ef-41a1-ac2e-cf3877906da4)
