### ISSUE TITLE
UX improvement: Change "Close window" to standard behaviour

### ISSUE THREAD

**Issue by pepepez111** [testomatio/app#704]
The User Experience needs improvement:
- The dialog / window handling is irritating and frustrating. This 'X [esc]' for closing a dialog is not standard and thus should be changed to a standard way of closing a dialog. 
![image](https://user-images.githubusercontent.com/8337594/231393861-9637d0db-12d4-4e09-b600-de6fb2e66d52.png)

**Comment by littlefrontender** [comment]
@poliarush @DavertMik I like this option



![Image](https://github.com/user-attachments/assets/a201239c-fb83-42ce-866b-634cd844267c)



![Image](https://github.com/user-attachments/assets/ec893e71-d44c-4d24-b07d-cef9b7c34954)

**Comment by poliarush** [comment]
@littlefrontender I also like it, however need to discuss on the call

**Comment by TetianaKhomenko** [comment]
Hi @pepepez111 ! Thanks for the suggestion. The improvement will be published in the upcoming release.

![Image](https://github.com/user-attachments/assets/0bcc9028-ef63-43d8-bdb7-0f5ae11e40c8)
