### ISSUE TITLE
Be able to generate a report for an ongoing Run

### ISSUE THREAD

**Issue by cgaulay** [testomatio/app#709]
**Is your feature request related to a problem? Please describe.**
I would like to be able to generate a report for an ongoing Run. 
Actually, we can have a report for a completed run. But a run can takes a time to be completed and it should be interesting to share the progress of the run when it's ongoing, not just when it's completed.

**Describe the solution you'd like**
Have the possibility to generate a report during a run

**Comment by DmytroBerestenko** [comment]
@TetianaKhomenko For PushkaStudios this is also a very important feature.
I hope it will be implemented as soon as possible.

**Comment by TetianaKhomenko** [comment]
Hi @cgaulay @DmytroBerestenko! The feature was implemented and will be published in the upcoming release 

![Image](https://github.com/testomatio/app/assets/77803888/fe991871-e840-4d59-a758-d00e16d8f8e2)
