### ISSUE TITLE
highlight line in editor when press on failed results in reporting

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#71]
As it's unclear where the test is failed as no stack trace is available

![image](https://user-images.githubusercontent.com/325722/83034991-2c989a80-a039-11ea-90dd-0d89ef7201e2.png)

![image](https://user-images.githubusercontent.com/325722/83035006-315d4e80-a039-11ea-9633-cff838d7e6a6.png)

**Comment by DavertMik** [comment]
@koushikmohan1996 do we have stacktrace on failures?
