### ISSUE TITLE
Labels can't be removed after disabling in Settings

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#710]
**To Reproduce**
1. open a project
2. go to Settings > Labels
3. create a label
4. go to Tests page
5. apply this label to suite/ test
6. go to Settings > Labels > Edit
7. disable the label for suite/ test
8. go to Tests page see the label is still shown for the disabled suite/ test
9. try to remove this label
10. see the label is not shown in the Labels pop-up

**Screenshots**

https://user-images.githubusercontent.com/77803888/235074923-a998c0e4-e46a-48bc-960a-2f7b97ea1c62.mp4

**Comment by poliarush** [comment]
@TetianaKhomenko btw, did labels removed from tree if label is removed from settings?

**Comment by TetianaKhomenko** [comment]
@poliarush yes

https://user-images.githubusercontent.com/77803888/235091485-51f6b15d-6c29-49ec-a199-2303d9dbe2bb.mp4

**Comment by TetianaKhomenko** [comment]
@TetianaKhomenko check Visibility and Scope

**Comment by TetianaKhomenko** [comment]
The issue was fixed. This fix will be published in the next release
