### ISSUE TITLE
I would like to change Manual type of tests to Automation without importing framework source code

### ISSUE THREAD

**Issue by kreminmaria** [testomatio/app#711]
**Is your feature request related to a problem? Please describe.**
I want to track Automation coverage metrics on my project without synching with our source code. 

**Describe the solution you'd like**
I would like to have the possibility to change Manual to Automation type of test case manually

**Comment by littlefrontender** [comment]
@trumenov please help

**Comment by poliarush** [comment]
@trumenov need to have backend for this feature

**Comment by TetianaKhomenko** [comment]
N.b. when manually changing the `manual` status to `automatic`, the analytics should be recalculated as well

**Comment by TetianaKhomenko** [comment]
Hi @poliarush @kreminmaria! The feature was implemented and will be published in the upcoming release. 

@kreminmaria please let us know if it is what you needed?

Attaching short demo video

https://github.com/testomatio/app/assets/77803888/4059a5e4-6ff0-4dcb-bdb9-5311ee9e91f6

**Comment by kreminmaria** [comment]
lovely. thank you so much, guys! you are rock <3
