### ISSUE TITLE
I am redirected to Tests tab when exploring test cases in other tabs/filters

### ISSUE THREAD

**Issue by kreminmaria** [testomatio/app#717]
**Describe the bug**
It appeared annoying when Tests tab is opened when I am exploring other tabs/filters (e.g. Analytics, steps, etc.)

**To Reproduce**
1. Go to 'Analytics'
2. Go to 'Automation Coverage'
3. expand folders to see files with tests
4. click on any file
5. close the file explorer (pop-up with a list of tests)

**Expected behavior**
I would love to stay in Analytics and continue to explore Automation coverage folder by folder

**Actual result**
I am redirected to Tests tab and need to go to Analytics tab again

**Additional context**
The same is when editing test cases in branches; also if applying filters in steps, make some changes in steps - the filter is reset

**Comment by TetianaKhomenko** [comment]
Hi @kreminmaria! The issue was fixed. This improvement will be published in the upcoming release. 
Attaching a short demo video

https://github.com/testomatio/app/assets/77803888/88e33d42-1328-4be8-80aa-0cc5f75ec286
