### ISSUE TITLE
Test run is showing deleted tests

### ISSUE THREAD

**Issue by panhiay** [testomatio/app#718]
**Describe the bug**
When a test is deleted and then a test run is created, the test run is still showing the deleted test. 

**To Reproduce**
1. Go to a project
2. Delete a tes
3. Create a test run
4. Go to test run and click Continue
5. Review the test that is listed

**Expected behavior**
- The deleted test run should be removed, however, it is still showing up in the test run. 
- Review the history of the suite in which the test was deleted. The Suite will no longer see the test but in the history, there is no record of the test being deleted. 

**Desktop (please complete the following information):**
OS: macOS
Browser: Chrome
Browser Version 112.0.5615.137
Application: Production

**Additional context**
N/A

**Comment by poliarush** [comment]
related to 
https://github.com/testomatio/app/issues/720
and
https://github.com/testomatio/app/issues/719

**Comment by TetianaKhomenko** [comment]
Hi @panhiay ! The issue was fixed. The improvement will be published in the upcoming release. 
Attaching short video:

https://github.com/testomatio/app/assets/77803888/b480cade-d9d2-4a15-bc7b-1a4b317d55e5
