### ISSUE TITLE
Test that were moved to a different folder is still showing up in a test run for the previous folder

### ISSUE THREAD

**Issue by panhiay** [testomatio/app#719]
**Describe the bug**
When we created a test in a folder and then moved that test over to another folder. If we create a test run for the first folder only, the test still shows up on the test run. 

**To Reproduce**
1. Create a project and folder
2. Add some tests
3. Create a new folder with the same level at the first folder
4. Move some of the tests from the first folder to the second folder
5. Create a test run for the first folder
6. 

**Expected behavior**
- Any moved tests should not be listed in the test run. 

**Screenshots**
This image shows that these tests belong under the "Not Yet Implemented" folder
![image](https://github.com/testomatio/app/assets/97122982/97c31ead-747a-4e61-b591-6e589f9a3717)

This image shows that the Tests folder does not contain the test above
![image](https://github.com/testomatio/app/assets/97122982/834a4926-9d28-49c2-aeca-de9b8cb429cf)

This image shows that some of these tests are showing up on the test run
![image](https://github.com/testomatio/app/assets/97122982/02c9b9df-2c6e-4fd6-ba35-2bab129d2bdd)

**Desktop (please complete the following information):**
OS: macOS
Browser: Chrome
Browser Version 112.0.5615.137
Application: Production

**Additional context**
N/A

**Comment by poliarush** [comment]
related to 

https://github.com/testomatio/app/issues/720
and
https://github.com/testomatio/app/issues/718

**Comment by TetianaKhomenko** [comment]
@panhiay @DavertMik I suggest keeping this issue in backlog since it reproduces mostly after Branch merge

**Comment by TetianaKhomenko** [comment]
The issue was re-tested and verified as fixed
