### ISSUE TITLE
can't search test by word

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#72]
![image](https://user-images.githubusercontent.com/325722/83035456-c5c7b100-a039-11ea-86ca-bcd4fdeb7e11.png)

![image](https://user-images.githubusercontent.com/325722/83035474-ceb88280-a039-11ea-9677-67884527f4d9.png)

![image](https://user-images.githubusercontent.com/325722/83035731-19d29580-a03a-11ea-9168-63ccecbd6084.png)

**Comment by koushikmohan1996** [comment]
@DavertMik @poliarush First one is due to the minimum threshold for search param - It should be minimum 4 chars. May be we have to show that in UI. Not sure about the second one. It is not reproduced. May be can you try loading the test and let me know?

**Comment by poliarush** [comment]
> It should be minimum 4 chars. 
Then it should be a hint to help user understand what is happening.

**Comment by poliarush** [comment]
> It is not reproduced. May be can you try loading the test and let me know?

ok

**Comment by TetianaKhomenko** [comment]
fixed
