### ISSUE TITLE
Tests are being duplicated when creating a test run

### ISSUE THREAD

**Issue by panhiay** [testomatio/app#720]
**Describe the bug**
When we create a test some, some of our tests are being duplicated. 

**To Reproduce**
1. Go to the project
2. Create a test run
3. Click on the test run and then continue
4. Review the test run 

**Expected behavior**
There should only be one instance of our tests, but we're seeing at least 4 of the same test names

**Screenshots**
![image](https://github.com/testomatio/app/assets/97122982/2fe73ab8-ebdf-44e2-96d0-755dc8e47a55)
![image](https://github.com/testomatio/app/assets/97122982/b9564516-4a05-49b8-8f9d-0e8150418ea7)

**Desktop (please complete the following information):**
OS: macOS
Browser: Chrome
Browser Version 112.0.5615.137
Application: Production

**Additional context**
N/A

**Comment by poliarush** [comment]
related to 
https://github.com/testomatio/app/issues/718
and
https://github.com/testomatio/app/issues/718

**Comment by panhiay** [comment]
here is a video showing extra details of duplicated test cases within a test run. When we look at the test case list, we see there are only one test per test case. However, whenever I try to edit the tests in bulk, I will see the duplicated tests that will show up on the test run. This is also impacting our ability to make bulk updates because of the duplicates. https://drive.google.com/file/d/13MEfzR_MQtOWmR8BUU59XHBvhShmYdiL/view?usp=sharing

**Comment by TetianaKhomenko** [comment]
fixed
