### ISSUE TITLE
500 server error when trying to merge branch with lot of changes 

### ISSUE THREAD

**Issue by kreminmaria** [testomatio/app#722]
1. make a lot of changes in the branch (e.g. 47 tests)
2. try to merge the branch 

expected: changes are merged;

actual: 500 server error 

![image (4)](https://github.com/testomatio/app/assets/14187016/b647a557-4399-47cc-9874-020e5479c63b)

**Comment by TetianaKhomenko** [comment]
the issue was fixed. the fix will be published in the next release.

**Comment by TetianaKhomenko** [comment]
@kreminmaria could you please check the issue on your project? Thank you in advance.

**Comment by kreminmaria** [comment]
seems fixed. thanks!
