### ISSUE TITLE
Code Templates are missing after changing Testing Framework in project settings

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#725]
**Describe the bug**
Users can't use preset or setup their own Code Templates in project settings.
Also related to this issue https://github.com/testomatio/testomatio/issues/971

**To Reproduce**
1. open a project
2. go to settings
3. enable Admin mode
4. change Testing Framework and Language
5. save changes
6. go to Templates settings
7. see no Code Templates shown 

**Expected behavior**
Users should be always available to setup and update Code Templates.

**Screenshots**

![CleanShot 2023-06-05 at 09 57 31@2x](https://github.com/testomatio/app/assets/77803888/7493b550-f030-4923-8f55-dcc611ad43cc)

![CleanShot 2023-06-05 at 09 58 03@2x](https://github.com/testomatio/app/assets/77803888/e2329956-4268-42e6-be56-733d77082cdd)

**Comment by littlefrontender** [comment]
@DavertMik templates are mixed up or missing, I found inaccuracies in codeceptjs, cucumber and playwright. Please check `/api/{project}/templates`. Button "Refresh Templates" doesn't help
![codeceptjs gherkin](https://github.com/testomatio/app/assets/79913874/b47d8ff8-dcd4-4d1e-a6e1-4a660a9b4e21)
![codeceptjs js](https://github.com/testomatio/app/assets/79913874/8e49cc45-be45-4a5d-bbaf-c11aaa607148)
![cucumber gherkin](https://github.com/testomatio/app/assets/79913874/1e05430d-602b-4548-8a0d-563df9e655cf)
![playwright js](https://github.com/testomatio/app/assets/79913874/2ed70d2d-e485-4441-afa1-2fa3aa4938f7)

**Comment by TetianaKhomenko** [comment]
fixed
