### ISSUE TITLE
The "o.model.destroyRecord is not a function" error is displayed on the Automated, Detected tabs (Tests page) after deleting a test/suite.

### ISSUE THREAD

**Issue by mykhailiukVitalii** [testomatio/app#726]
**Describe the bug**
The "o.model.destroyRecord is not a function" error is displayed on the Automated, Detected tabs (Tests page) after attempting to delete a test/suite.

**To Reproduce**
1. Import "automated" tests to the dashboard
2. Go to "Tests" page. Navigate to the Automated or Detected tab.
3. Choose any removing.
5. See error

**Expected behavior**
A remove selected suit/test

**Video / Screenshots**
![Screenshot-my-1](https://github.com/testomatio/app/assets/82405549/b941301d-82f4-4368-949d-055920fbc18c)

https://github.com/testomatio/app/assets/82405549/d9d638fd-90d9-415d-9469-710626ead80b

**Desktop (please complete the following information):**
 - Application: [beta - https://beta.testomat.io/]

**Comment by TetianaKhomenko** [comment]
the issue was fixed. the fix will be published in the next release
