### ISSUE TITLE
Can't setup Newman and Json as Testing Framework/language in the settings of the project

### ISSUE THREAD

**Issue by lcontroatmira** [testomatio/app#730]
**Describe the bug**
Can't setup Newman and Json as Testing Framework/language in the settings of the project

**To Reproduce**
1. Go to proyect
2. Click on Settings
3. Scroll down to Testing Framework And Language.
4. Select Newman as Testing Framework
5. In language appear Json (but you can't select in the dropdown)
6. Click on update button
7. See error

**Expected behavior**
i should select json on the dropdown of language and i should uptade and save the settings for the project

**Screenshots**
<img width="623" alt="image" src="https://github.com/testomatio/app/assets/136477666/b87be617-6f20-4480-a50c-5d2932941e6f">

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Browser Version 114.0.5735.134

**Comment by DavertMik** [comment]
@lcontroatmira you can create a new project and select Newman on import phase

![image](https://github.com/testomatio/app/assets/220264/049b235c-4a66-4878-95c1-c9c9245e651e)

**Comment by TetianaKhomenko** [comment]
fixed
