### ISSUE TITLE
Project name visible on each sub-page

### ISSUE THREAD

**Issue by Chiel-CBTC** [testomatio/app#731]
**Is your feature request related to a problem? Please describe.**
I have created seperate Testomat projects for each test environment we run our tests on.
Within each project I most often use the 'Runs' sub-page. But on this sub-page I cant see which project I am currently viewing.

**Describe the solution you'd like**
I would like to see the project name on top of each project sub-page. Just like it is shown on top of the 'Tests' sub-page.

**Describe alternatives you've considered**
I do not have a good alternative solution for this.

**Additional context**

![image](https://github.com/testomatio/app/assets/38032056/060e5343-49dd-4d55-87b3-46b02772f65f)
![image](https://github.com/testomatio/app/assets/38032056/ded43b1f-5fe5-4b4b-a4b6-500e219a1bad)

**Comment by TetianaKhomenko** [comment]
Hi @Chiel-CBTC! The feature was implemented and will be added to the upcoming release.

![CleanShot 2023-11-28 at 09 14 49@2x](https://github.com/testomatio/app/assets/77803888/c89802a0-aa1a-488e-862e-070566522a49)
