### ISSUE TITLE
Finish automated test runs manually

### ISSUE THREAD

**Issue by Chiel-CBTC** [testomatio/app#732]
**Is your feature request related to a problem? Please describe.**
Sometimes our testruns are not properly closed when running them in our Azure pipeline. This causes the testtuns in Testomat not to finish: The progress bar stays visible, in stead of the amounts of passed, failed and skipped tests.

**Describe the solution you'd like**
It would be nice to be able to mark testruns as finished, manually.

**Describe alternatives you've considered**
-

**Additional context**
![image](https://github.com/testomatio/app/assets/38032056/2e877016-aa44-4a0c-9458-12ba8e78e2d6)

**Comment by TetianaKhomenko** [comment]
Hi @Chiel-CBTC ! The feature was implemented, and it will be published in the upcoming release.

<img width="1387" alt="CleanShot 2023-07-24 at 10 39 39@2x" src="https://github.com/testomatio/app/assets/77803888/f7125b8b-2ec7-4d14-9239-9552a66c00f9">
