### ISSUE TITLE
In the test run, after the test case result is added, the next test case opens automatically.

### ISSUE THREAD

**Issue by RohalskyiOleksii** [testomatio/app#733]
video with reference from qase:
https://github.com/testomatio/app/assets/132286699/62c15b63-1b71-4495-a36e-ce7a3889ffc4

**Comment by RohalskyiOleksii** [comment]
> video with reference from qase: https://github.com/testomatio/app/assets/132286699/62c15b63-1b71-4495-a36e-ce7a3889ffc4

request from PushkaStudios. it`s a HIGH priority from our side

**Comment by poliarush** [comment]
@RohalskyiOleksii is this expected behaviour? 

https://github.com/testomatio/app/assets/325722/52200dab-a8ea-4475-a28b-2d86b7d20d63

**Comment by poliarush** [comment]
@RohalskyiOleksii we are going to release this feature next week

**Comment by RohalskyiOleksii** [comment]
yes, looks like we wanted! @poliarush

**Comment by poliarush** [comment]
@RohalskyiOleksii then we will release this next week,
keep tracking https://changelog.testomat.io/ once this ticket is fully closed

**Comment by TetianaKhomenko** [comment]
The feature was implemented and will be published in the upcoming release
