### ISSUE TITLE
Test cases included in a completed run can be altered

### ISSUE THREAD

**Issue by guilaharis** [testomatio/app#735]
**Describe the bug**
When a test case is included in a run, and the run is completed (closed), when the same test case is altered in the suite, the content of the test case in the completed run also changes. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to an open run
2. Close the run
3. Go to the suite included in the run 
4. Save the change of a test case that has been included in the closed run
5. Go back to the run and open the same case

**Expected behaviour**
The test case in the run is in its first version that has been tested. The change is saved only in the suite. 

**Actual behaviour**
The test case in the run is also changed. May not be visible from the list, but the altered content is displayed when the test case is opened 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac Ventura 13.4.1
 - Browser [e.g. chrome, safari] Chrome 
 - Browser Version [e.g. 22] 114.0.5735.133 
 - Application: [production or beta] 

**Additional context**

**Comment by TetianaKhomenko** [comment]
The issue is related to https://github.com/testomatio/testomatio/issues/889

**Comment by TetianaKhomenko** [comment]
Hello @guilaharis ! I would suggest refreshing the page as a temporary workaround. Attaching a short video:

https://github.com/testomatio/app/assets/77803888/88a4b4cc-2384-4a59-bb33-4cdb5e073c3a

**Comment by TetianaKhomenko** [comment]
Hi @guilaharis! The feature was fixed. The fix will be published in the upcoming release.
