### ISSUE TITLE
RunGroup combined report is wrong in combined report

### ISSUE THREAD

**Issue by SB-FB** [testomatio/app#738]
**Describe the bug**
I have a rungroup with merge strategy "Realistic". My last run doesn't have any failed tests, but 1 skipped test.
The status of the rungroup is "Failed" and the summary says I have 1 failed test.

![image](https://github.com/testomatio/app/assets/128134241/294dbb41-da28-49ac-9c7e-4e9e214f0893)

On the run overview page, the summary shows 1 failed test and 0 skipped tests.
![image](https://github.com/testomatio/app/assets/128134241/e80a2ba1-a2c7-452f-b2d0-d27a5fc3bcf4)

**To Reproduce**
1. Create a run group with realistic merge strategy
2. Add a testruns with several tests.
3. Run the testrun several times (set some tests on "failed" in the first runs). 
4. In the last testrun, make sure there are no "Failed" tests, and skip at least 1 test.

**Expected behavior**
In realistic mode, the result of the last testrun is shown as "status" for the rungroup.

**Screenshots**
See above in description.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Browser Version Chrome 114
 - Application: production

**Comment by poliarush** [comment]
@SB-FB 

I'd like to seek clarification. Was this "1 skipped test" previously executed?

Here's what the current behavior looks like: If a single test case is executed multiple times with different outcomes, like the following:
1. Passed on 01.01.2023
2. Failed on 02.02.2023
3. Skipped on 03.03.2023
4. Skipped on 04.04.2023
5. Skipped on 05.05.2023

Given a "Realistic" strategy, we will display this test case as "Failed" since we aim to represent the most recent result. This indicates that we disregard the "skipped" status if there's at least one occurrence of a failed or passed state.

Consider this example:
- You're testing a login form.
- You conduct a test and it passes.
- You rerun the test and it fails.
- Subsequently, you skip the test due to lack of time.
- Later, you skip it again due to limited capacity.

In such instances, the status of the test case will be shown as "Failed". This is because it reflects the actual events related to the functionality, rather than the fact that you didn't have the time to rectify it. 

Please note that a test case will only be marked as "Skipped" if all its executions ended in a skipped state.

**Comment by poliarush** [comment]
please give us screenshot for this 1 tests and previous execution in this run group

**Comment by poliarush** [comment]
just to sum it up

realistic strategy:
1. first run - failed, second - passed, third - skipped = it will be passed
2. first run - passed, second - failed, third - skipped = it will be failed
3. first run - passed, second - failed, third - passed = it will be passed
4. first run - skipped, second - failed, third - skipped = it will be failed
5. first run - skipped, second - skipped, third - skipped = it will be skipped

optimistic strategy:
1. first run - failed, second - passed, third - skipped = it will be passed
2. first run - passed, second - failed, third - skipped = it will be passed
3. first run - passed, second - failed, third - passed = it will be passed
4. first run - skipped, second - failed, third - skipped = it will be failed
5. first run - skipped, second - skipped, third - skipped = it will be skipped

pessimistic  strategy:
1. first run - failed, second - passed, third - skipped = it will be failed
2. first run - passed, second - failed, third - skipped = it will be failed
3. first run - passed, second - failed, third - passed = it will be failed
4. first run - skipped, second - failed, third - skipped = it will be failed
5. first run - skipped, second - skipped, third - skipped = it will be skipped

@SB-FB please let us know if you have any questions in this regards

**Comment by SB-FB** [comment]
Thanks for the explanation @poliarush . 

There is indeed one test which failed once and was skipped in following runs. So the behaviour is "by design".
You can close this "bug" ;-)
![image](https://github.com/testomatio/app/assets/128134241/c29c5f69-4ac3-43f5-ae42-30cf5e782a44)

PS: is might be a good idea to add this info to the realistic scenario? Because now it says "Prefer test results from the last executed run, which is not how it actually works.

**Comment by poliarush** [comment]
@SB-FB It may be we need to add one more strategy here

1. Realistic + taking into account skipped
2. Realistic + not taking into account skipped

We will discuss this with a team.
And now we will add a note that skipped is not taking into account in Realistic strategy.

**Comment by poliarush** [comment]
@littlefrontender need to mention in here that skipped is not taking into account if there is at least one passed or failed result before for the same test

![Google Chrome-251376651-11c877d6-912f-43b1-b7d0-15105335b2a6 png (522×416)-2023-07-06 at 09 32 42@2x](https://github.com/testomatio/app/assets/325722/b9619f88-5211-4e3c-9e4f-5a452d8d06b8)

**Comment by poliarush** [comment]
@SB-FB btw, in this case, do you want to see 1 skipped test or 1 failed test?

**Comment by SB-FB** [comment]
I like the logic which is implemented now = see a failed test when it failed once and was skipped afterwards. But it might be good to have the option to choose between
1. Realistic + taking into account skipped
2. Realistic + not taking into account skipped

As long as the description is clear, the user can choose what he likes most.

**Comment by poliarush** [comment]
@SB-FB we will add a new merging strategy "Latest", a new ticket is created https://github.com/testomatio/app/issues/745

**Comment by TetianaKhomenko** [comment]
resolving the issue as fixed 

![Image](https://github.com/testomatio/app/assets/77803888/f278e0f1-4508-4850-9c6c-3520b1e0de08)
