### ISSUE TITLE
Filtering some Labels values don't return results

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#739]
**To Reproduce**
1. open a project with enabled custom fields 
2. filter by Label's values
3. see no tests shown for some Label's values
4. expand suites and folders to see the "not found" Label's value is indeed present 

**Expected behavior**
Filtering any Labels values should return results.

**Screenshots**

![image](https://github.com/testomatio/app/assets/77803888/bc8bacb5-eebc-43a3-bccb-e0ea076972f6)

![image](https://github.com/testomatio/app/assets/77803888/14fe3e3a-904f-4cd0-9b5f-77e3cce5563b)

https://github.com/testomatio/app/assets/77803888/8f946494-127f-4c0b-b3e1-cc461722b4de

https://github.com/testomatio/testomatio/issues/2719

**Comment by littlefrontender** [comment]
@DavertMik i found no problems on the front side. Please check on the backend

**Comment by TetianaKhomenko** [comment]
The issue was fixed. The fix will be published in the upcoming release.
