### ISSUE TITLE
No possibility to remove own Avatar

### ISSUE THREAD

**Issue by mbiesiad** [testomatio/app#740]
Hi, first of all, great project!

**Describe the bug**
At this moment user can not remove uploaded Avatar - user has to upload another one (to 'overwrite'), so upload other image.

**To Reproduce**
1. As logged in user go to https://app.testomat.io/account
2. Click on 'Choose the file' - upload Avatar, save
3. See no possibility to remove Avatar

**Expected behavior**
User can easy remove uploaded Avatar, ie. use default avatar (like before uploading).

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

Best wishes,

**Comment by TetianaKhomenko** [comment]
Hi @mbiesiad! Thanks for reporting the issue. The issue was fixed. The fix will be published in the upcoming release.

**Comment by mbiesiad** [comment]
Hi @TetianaKhomenko my pleasure. sounds great! Thank you for your message. 

Have a good day, Best wishes
