### ISSUE TITLE
No Status Updates - User notification

### ISSUE THREAD

**Issue by GivennameSurname** [testomatio/app#742]
### **Describtion**
If you assign a user to a Testticket or Testrun, there is no notification for the user.

### **Steps to reproduce the behavior**
1. Go to 'Manuel Run'
2. Click on 'Assign users.'
3. Click on 'User-Name'
4. Click on 'Save'

### **Expected behavior**
The user will be notified via E-Mail.

### **Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome & Safari
 - Browser Version Chrome Version 114.0.5735.198 (Official Build) (x86_64)
 -  Browser Version Safari Version 16.5.1 (18615.2.9.11.7)
 - Application: **production**

**Comment by TetianaKhomenko** [comment]
The issue is still present.

**Comment by TetianaKhomenko** [comment]
The issue was fixed and available now
