### ISSUE TITLE
Typo in hyperlink for Github CI Connection Configuration tab

### ISSUE THREAD

**Issue by andrewrybak** [testomatio/app#746]
**Describe the bug**
Typo in hyperlink for GitHub CI Connection Configuration tab

**To Reproduce**
1. Go to project Settings GitHub CI /settings/ci/profile/github
2. Click on '[Learn more →](https://docs.testomat.io/usage/continious-integration/#environment-configuration)' https://docs.testomat.io/usage/continious-integration/#environment-configuration
3. Page 404 is opened

**Expected behavior**
Page https://docs.testomat.io/usage/continuous-integration/#environment-configuration must be opened

**Screenshots**
![image](https://github.com/testomatio/app/assets/134290917/9434b5e7-273b-4734-9f90-e71b087ccb3e)

**Comment by TetianaKhomenko** [comment]
The issue was fixed. The fix will be published in the upcoming release.
