### ISSUE TITLE
Add counter to JIRA Integration setting

### ISSUE THREAD

**Issue by andrewrybak** [testomatio/app#747]
**Is your feature request related to a problem? Please describe.**
When JIRA Integration is established there isn't a counter as for Continuous Integration or users, I believe the application would be more consistent with such improvement.

**Describe the solution you'd like**
Add counter of connected JIRA Integrations

**Additional context**
![image](https://github.com/testomatio/app/assets/134290917/233ee8b1-dde7-4637-baaa-e1c21be2af88)

**Comment by TetianaKhomenko** [comment]
The feature was implemented and will be published in the upcoming release


![Image](https://github.com/testomatio/app/assets/77803888/1ab02153-0106-41f6-960b-cf8ff7ca5573)
