### ISSUE TITLE
Copy to clipboard button doesn’t work

### ISSUE THREAD

**Issue by andrewrybak** [testomatio/app#748]
**Describe the bug**
Copy to clipboard button doesn’t work

**To Reproduce**
1. Go to the 'Import Project from Source Code' page
2. Choose a Project Framework 'Other'
3. Choose any Project Language
4. Click the icon Copy to the clipboard for the command 'npm i -g @testomatio/reporter'

**Expected behavior**
The command is copied to the clipboard

**Screenshots**
![image](https://github.com/testomatio/app/assets/134290917/88f0f484-616f-4736-8e3e-41f9aa9a95c5)

**Comment by TetianaKhomenko** [comment]
The issue was fixed. The fix will be published in the upcoming release
