### ISSUE TITLE
counter in Jira widget in analytics is wrong

### ISSUE THREAD

**Issue by SimiDrinkova** [testomatio/app#749]
**Describe the bug**
counter in Jira widget in analytics is wrong. Even If I have linked 30tests to Story, my widget shows me that I have only 4 tests

**To Reproduce**
[check video pls ](https://testomatio.slack.com/archives/C04CW130G2C/p1688025254620489)

**Expected behavior**
I should be able to see the correct numbers of tests in the analytics

**Screenshots**
https://testomatio.slack.com/archives/C04CW130G2C/p1688025254620489

**Desktop (please complete the following information):**
 Mac, Chrome

**Additional context**
As we spoke on the call

**Comment by trumenov** [comment]
In the Analitics JiraIssues is loading from the testruns database, so for get test in Analitics - you must launch this tests with linked JiraIssues and only than this tests will be shown in the Analitics statistics. Please recheck that you have ran this tests with already linked JiraIssues before the Run was started.

**Comment by TetianaKhomenko** [comment]
Hi @SimiDrinkova! Can we ask you to re-check this behaviour on your side?

**Comment by TetianaKhomenko** [comment]
Hi @SimiDrinkova how it's going with the Jira plugin? Can we close this ticket?

**Comment by SimiDrinkova** [comment]
@TetianaKhomenko  Hey :) Yes, i think we can close it. Now i understand how it should work. Thx :)

**Comment by TetianaKhomenko** [comment]
Closing ticket as done
