### ISSUE TITLE
UI Freeze after creating a suite with only tag in a title

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#752]
**Describe the bug**

The user was using bulk editing, Inputting tests > hit save > The screen seemed to disappear > suite with an @ in it > after the user refreshed the page UI got irresponsive

**Expected behavior**
Don't allow creating a suite without actual title.

**Screenshots**
![image](https://github.com/testomatio/app/assets/77803888/a8c62a52-c5a7-49ea-ac38-6410812daa4b)

**Comment by JeremyLWright** [comment]
I named a suite with an @ in it.

**Comment by TetianaKhomenko** [comment]
fixed
