### ISSUE TITLE
Sign In page background gets misaligned after resizing

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#753]
**Describe the bug**

https://github.com/testomatio/app/assets/77803888/3c6b84e1-cc2a-45e6-ad95-3dc3bd16f836

**To Reproduce**
1. open Sign In page
2. resize the browser window and make it small
3. see background image does not align

**Expected behavior**
Background image should adjust to any screen size

**Comment by littlefrontender** [comment]
@TetianaKhomenko 
I don't see any problems on this screen. This layout is done on purpose. I think all the information should fit on one screen without scrolling on the login/signin screen.

**Comment by TetianaKhomenko** [comment]
the issue was fixed. the fix will be published in the upcoming release.
