### ISSUE TITLE
Very long company's title shifts the layout of the site

### ISSUE THREAD

**Issue by TetianaWhite** [testomatio/app#759]
**Pre-conditions:**
Website http://testomat.io/  is opened on the page “Companies”

**Steps to reproduce:**
1. Click on the blue button “Create”.
2. Write 100 symbols in the company’s title.
3. Click on the “Create” blue button.
4. Click on the “Companies” button in the header.

**Actual result:** A very long title shifts the layout of the site.

**Expected result:** The company’s name should be approx. 50 symbols or a long title should be divided into paragraphs (f.e. 30 symbols in one line}.

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser chrome
 - Browser Version 114.0.5735.199 
 - Application: production 

![chrome_rdlf9xxWY1](https://github.com/testomatio/app/assets/126608399/cc60dc5e-3b34-4303-8902-c6107833cd0a)

**Comment by TetianaKhomenko** [comment]
The issue was fixed. The fix will be published in the upcoming release.


![Image](https://github.com/testomatio/app/assets/77803888/28777664-ef6b-4e73-8e71-4b8a19d8fc49)
