### ISSUE TITLE
A company name can be created with an empty name field

### ISSUE THREAD

**Issue by TetianaWhite** [testomatio/app#765]
**Describe the bug**
The user can create a company name without any name. 
The user sees a created company but can go “inside” because the title of the company is empty.

**To Reproduce**
1. Click on the blue button “Create”.
2. Clear the title field.
3. Click on the “Create” blue button.
4. Click on the “Companies” button in the header.

**Expected behavior**
The system shouldn’t allow to create a company without any name.

**Desktop**
- OS: Windows10
- Browser chrome
- Browser Version 114.0.5735.199
- Application: production

![InkedWsy6AEGmxh](https://github.com/testomatio/app/assets/126608399/0b69adf0-f5bf-47ed-bd94-7261288a65e7)

**Comment by TetianaKhomenko** [comment]
The issue was fixed. This fix will be published in the upcoming release.
