### ISSUE TITLE
The test count in the folder does not update after dragging a suite into it

### ISSUE THREAD

**Issue by DmytroBerestenko** [testomatio/app#766]
**Describe the bug**
When dragging a suite with tests into a folder, the test count in the folder does not get updated.
Even after refreshing the page, the test count remains unchanged.

**To Reproduce**
1. Open the project page.
2. Create a folder.
3. Create a suite.
4. Create some cases in the suite.
5. Drag the suite to the folder.

**Expected behavior**
The test count in the folder is updated after dragging a suite into it and displays the correct number of tests present in the folder

**Screenshots**
![image](https://github.com/testomatio/app/assets/137514646/ee8bf0f4-0757-4125-bab5-4d43069d81a4)
https://github.com/testomatio/app/assets/137514646/8fdb469b-4932-4dbd-bceb-da5ad9ed21cb

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Google Chrome
 - Browser Version 115.0.5790.99
 - Application: Production
 
 Bug-report from PushkaStudios.
 High priority for us.

**Comment by andrewrybak** [comment]
@DmytroBerestenko I have a question, maybe you've tried to refresh the page or re-index the tests in the project?

![image](https://github.com/testomatio/app/assets/134290917/9533b7fb-5aa9-438c-b5f0-de8b2ca92b51)

**Comment by DmytroBerestenko** [comment]
@andrewrybak Thank you for your response.
Indeed, reindexing tests updates the counter data. However, **this doesn't change the fact of the issue I described**.
We have a team working on the project. Newly added tests and their reordering are instantly displayed on all devices.
Nevertheless, the test counter doesn't update until someone presses the 'reindex tests' button in the project settings.
At least, it would be nice to add a button to refresh all data on the project's main page.

**Comment by TetianaKhomenko** [comment]
The issue was fixed. The fix will be published in the upcoming release.

**Comment by TetianaKhomenko** [comment]
@DmytroBerestenko could you please create a feature request for[ this comment ](https://github.com/testomatio/app/issues/766#issuecomment-1644166819)?
