### ISSUE TITLE
Search filter for Living documentation cannot be cleared unless from the URL

### ISSUE THREAD

**Issue by guilaharis** [testomatio/app#769]
**Describe the bug**
On the external Living Documentation link, once a filter is applied, it cannot be cleared. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Living documentation of a project
2. Apply a search filter, for example a tag
3. Clear the filter from the search field
5. Refresh the page

**Expected behaviour**
The filter is cleared and the full Living documentation is again displayed 

**Actual behaviour**
The filter is back on the field. The full Living Documentation can be accessed again only through correction of the URL 

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.4.1 (22F82)
 - Browser Chrome
 - Browser Version 114.0.5735.198 
 - Application: not sure whether production or beta

**Comment by TetianaKhomenko** [comment]
The issue was fixed/ The fix will be published in the upcoming release

https://github.com/testomatio/app/assets/77803888/7425884d-1e09-4ae7-8d5a-df5416a435ed
