### ISSUE TITLE
unclear message what need to do if test is not found in reporting

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#77]
![image](https://user-images.githubusercontent.com/325722/83040900-1b9f5780-a040-11ea-8db5-a97a9bfd723d.png)

**Comment by poliarush** [comment]
and good question here why test results are not binding as I use jest demo project, load tests and execute it thus results should be linked

**Comment by koushikmohan1996** [comment]
@poliarush @DavertMik I fixed the parsing error in jest. Do you have any suggestion in the message?
