### ISSUE TITLE
Keyword "Rule" breaks the formatting 

### ISSUE THREAD

**Issue by guilaharis** [testomatio/app#770]
**Describe the bug**
The content after the keyword "Rule:" is deleted after formatting 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to  a feature file
2. Use the keyword "Rule" with some content
4. Format the feature file 

**Expected behaviour**
Formatting as accepted

**Actual behaviour**
The content of the Rule is deleted 

**Desktop (please complete the following information):**

- mac OS Ventura 13.4.1 (22F82)
- Chrome browser 114.0.5735.198

**Comment by littlefrontender** [comment]
@TetianaKhomenko There is error message about "rule" already

<img width="1113" alt="Снимок экрана 2023-08-02 в 17 30 01" src="https://github.com/testomatio/app/assets/79913874/5ade636d-fe40-4c28-8d0e-b4893fc81258">

**Comment by TetianaKhomenko** [comment]
Also, need to improve this notification in order to be more noticeable


![Image](https://github.com/testomatio/app/assets/77803888/4de001e8-6fd8-46bf-9948-261b4124fa8d)

**Comment by TetianaKhomenko** [comment]
Hi @guilaharis! Unfortunately, Testomat doesn't support the keyword `Rule`. But we improved the warning message for the BDD editor. 
You can try using `Background` instead of `Rule`.
