### ISSUE TITLE
New suite type supporting both tests and suites

### ISSUE THREAD

**Issue by DmytroBerestenko** [testomatio/app#773]
**Is your feature request related to a problem? Please describe.**
In the current version of Testomat, there are two types of suites available for creation: a file containing tests or a folder with suites. However, this limitation prevents the creation of suites that can contain both tests and suites. As a result, after importing such suites from QASE to Testomat, _the ability to choose the suite type is blocked_, and consequently, new test cases or suites cannot be created within these imported suites.

Adding a new suite type will allow organize test sets more flexibly, create hierarchical structures, and improve management and support for projects with more complex testing arrangements.

**Describe the solution you'd like**
Add a third suite type that allows supporting both tests and suites simultaneously, similar to the functionality provided in QASE.

**Additional context**
![image](https://github.com/testomatio/app/assets/137514646/c661c8f4-92f9-42a3-8211-708f92453aab)

 Feature request from PushkaStudios.

**Comment by DavertMik** [comment]
@DmytroBerestenko no, we are not planning to build another Qase

We have our own design decisions. Separation of suite/folder mimics filesystem and is essential for BDD project. 
For instance, you can't place BDD `Scenario` into a folder without creating a file first.
We started as an automation-first test management system, so any manual test at any time can be turned into an automated test. This is why we need the correct data structure on this, so it can always be synchronized to the filesystem. 

But this is not just a limitation, this can also be a feature:

For instance, we work on a feature that allows you to export/store/import all manual test cases in Git
This will allow backups, conflicts management, and usage Git ecosystem as GitHub or VSCode for test management.

I know this can be confusing from the start and is not a common pattern for TMS, but we are building a next-gen TMS, and 1-to-1 sync with a filesystem is our design decision we need to keep to implement all planned features.

**Comment by TetianaKhomenko** [comment]
@DmytroBerestenko we have created another ticket to improve tests import for Qase https://github.com/testomatio/app/issues/774. So you can track progress on the issue
