### ISSUE TITLE
<> characters are shown coded in tests

### ISSUE THREAD

**Issue by kreminmaria** [testomatio/app#775]
**To Reproduce**
1. Create test case using < or > symbols in summary or description 
2. Save test
3. Observe symbols in the newly created test

**Expected behavior**
< > are shown

** Actual** 
![image](https://github.com/testomatio/app/assets/14187016/b7282ec5-874b-4eb0-ad11-3aba2e673c3c)

**Comment by TetianaKhomenko** [comment]
@kreminmaria the issue was fixed. The fix will be published in the upcoming release.

![Image](https://github.com/testomatio/app/assets/77803888/51c17216-43c2-4361-935f-30733d9fe1ff)
