### ISSUE TITLE
REGISTRATION: [BE] [FE] The password error message is incorrect in registration form when user put less than 6 symbols in password field

### ISSUE THREAD

**Issue by AnisimovDenys03** [testomatio/app#777]
Description

**Steps to Reproduce**
     1. Open the testomatio **Sign Up** page
     2. Fill all the required fields with valid data
     3. Write a password with lenght less than 6 symbols in "**Password**" field
     4. Write a password confirmation
     5. Click on "**Sign Up**" button
    
**Actual Result**:The password error message has two conditions about the length of the password. Message "**is too short (minimum is 6 characters)**" is redundant.

**Expected Result**: The password error message has one confirmation about lenght of the password “**is too short (minimum is 14 characters)**“

![image-20230717-103115](https://github.com/testomatio/app/assets/140817860/95497523-1f33-4049-8c98-d8ef9bfdcbcc)

**Comment by Fro0z1k** [comment]
The same behavior... 
<img width="465" alt="Screenshot 2023-08-31 at 12 30 38" src="https://github.com/testomatio/app/assets/7832212/4a07d686-a2b5-41aa-b7f2-6fef37459576">

**Comment by TetianaKhomenko** [comment]
fixed
