### ISSUE TITLE
PROJECTS: [BE] "Repository URL" field doesn't have URL validation in Project creation page

### ISSUE THREAD

**Issue by AnisimovDenys03** [testomatio/app#778]
Description

**Steps to Reproduce:**
1. Go to the **Projects** page
2. Click on **“Create”** button
3. Fill all the required fields with valid data
4. Insert any text in **“Repository URL”** field
5. Click on **“Create”** button

**Actual Result:** Project was created with invalid **“Repository URL”** link.

**Expected Result:** User get an error message **“That’s not a valid URL“**

![image-20230717-104725](https://github.com/testomatio/app/assets/140817860/fe5842b3-5a9a-40b4-8d41-76c5d9ba3884)

**Comment by TetianaKhomenko** [comment]
The issue was fixed. the fix will be published in the upcoming release

![Image](https://github.com/testomatio/app/assets/77803888/9db68109-7c95-4746-9101-5b00060c5819)
