### ISSUE TITLE
PROJECTS: [BE] [FE] Link with more than 255 symbols in  "Repository URL"  cause 500 error on Create operation

### ISSUE THREAD

**Issue by AnisimovDenys03** [testomatio/app#779]
Description
**Steps to Reproduce:**

1. Go to the **Projects** page
2. Click on **“Create”** button
3. Fill all the required fields with valid data
4. Insert in the **“Repository URL”** field value with 256 symbols
5. Click on **“Create”** button

**Actual Result:**  Link with more than 255 symbols in  **"Repository URL"**  cause 500 error on Create operation

**Expected Result:** User get an error message **“Max lenght of Repository URL is 255 symbols”**

![image-20230717-105533](https://github.com/testomatio/app/assets/140817860/20b86afa-7907-4062-be67-4a6e26792415)
![image-20230717-105458](https://github.com/testomatio/app/assets/140817860/808c943a-74e4-4bf7-aa20-7eca651c1ac4)

**Comment by TetianaKhomenko** [comment]
the issue is still present
