### ISSUE TITLE
PROJECTS: [BE] [FE] The project title with lenght more than 255 cause 500 error on Save operation

### ISSUE THREAD

**Issue by AnisimovDenys03** [testomatio/app#780]
Description

**Steps to Reproduce:**

1. Go to the **Projects** page
2. Click on **“Manage”** button
3. Choose created project and click on **“Change project name“** button
4. Insert into the **“Project title”** field value with 256 symbols
5. Click on **“Save”** button

**Actual Result:** The project title with lenght more than 255 cause 500 error on Save operation

**Expected Result:** User get an error message **“Max lenght of Project title is 255 symbols”**

![image-20230717-110453](https://github.com/testomatio/app/assets/140817860/3c6ed938-aec5-43a4-bc78-0d34a25667d7)
![image-20230717-110725](https://github.com/testomatio/app/assets/140817860/397c7664-9c4c-4b85-a120-6811bd57d5fd)
![image-20230717-110205](https://github.com/testomatio/app/assets/140817860/c7050f09-d784-4a64-b106-62d74844814d)

**Comment by TetianaKhomenko** [comment]
the issue was fixed
