### ISSUE TITLE
COMPANIES:  [BE] [FE] The Company title with lenght more than 255 cause 500 error on Save operation 

### ISSUE THREAD

**Issue by AnisimovDenys03** [testomatio/app#781]
Description
**Steps to Reproduce:**

1. Go to the **Companies** page
2. Choose created company and click on **“Edit“** button
3. Insert into the **“Company title”** field value with 256 symbols
4. Click on **“Save”** button

**Actual Result:** The company title with lenght more than 255 cause 500 error on Save operation

**Expected Result**: User get an error message **“Max lenght of Company title is 255 symbols”**

![image-20230717-112154](https://github.com/testomatio/app/assets/140817860/75ef2670-adb1-4abb-89b1-0feae8657e2e)
![image-20230717-112237 (1)](https://github.com/testomatio/app/assets/140817860/39923cc5-c9f9-4498-a443-c47b77b04e82)
![image-20230717-111529](https://github.com/testomatio/app/assets/140817860/7d1453b4-1ef9-4662-af13-7fc0829a8689)

**Comment by Fro0z1k** [comment]
150 symbols validation is present

https://github.com/testomatio/app/assets/7832212/7c755ef0-874c-4646-94ac-7f4b9aa09e00

**Comment by TetianaKhomenko** [comment]
fixed 

![Image](https://github.com/testomatio/app/assets/77803888/46ff00ca-a302-4f16-aa3e-fd804980940f)
