### ISSUE TITLE
User is able to switch to merged branch and add tests in the scope of it 

### ISSUE THREAD

**Issue by kreminmaria** [testomatio/app#782]
**Describe the bug**

**To Reproduce**
1. Merge some branch
2. go to the merged branches tab and invoke the menu of the branch by pressing three dots
3. press switch to branch

**Expected behavior**
user is not able to switch to merged branches

**Actual result**
user is able to switch and make changes in merged branches

**Comment by TetianaKhomenko** [comment]
related to https://github.com/testomatio/testomatio/issues/560

**Comment by DavertMik** [comment]
This happened when there were two branches with the same name, one merged, other active

**Comment by TetianaKhomenko** [comment]
Hi @kreminmaria! The issue was fixed. This fix will be published in the next release.
