### ISSUE TITLE
Not existent test case is shown in the list of test cases

### ISSUE THREAD

**Issue by kreminmaria** [testomatio/app#783]
**Describe the bug**
Test case was deleted but still is visible in the list of test cases (only if press on Automated tab) 
test case could not be opened - errors appear 

**Screenshots**
![image](https://github.com/testomatio/app/assets/14187016/a5c60486-2359-4c57-943b-84c197ca1395)

**Additional context**
Cannot reproduce with other test cases

**Comment by DavertMik** [comment]
@TetianaKhomenko tests from branch were included into filter results when filtering by Manual / Automated only
added unit tests for that

**Comment by TetianaKhomenko** [comment]
I didn't succeed in reproducing the issue. 
@kreminmaria please re-check the issue on your side after next release (probably next week) and let us know if the issue persists.
