### ISSUE TITLE
Make Autocomplete feature available for @Tags

### ISSUE THREAD

**Issue by antonioGamezll** [testomatio/app#784]
When creating tags its super frustrating to write them by hand, you may remember what it its that you want to write but maybe you write it in a slightest  different  way creating duplicates and messing with the filter 

Having a list of your already created tags in a dropdown with autocomplete will permanently fix this issue

**Comment by antonioGamezll** [comment]
![image](https://github.com/testomatio/app/assets/141318155/1f33f8c0-5421-4f33-a558-fe63cee9ffcd)

**Comment by TetianaKhomenko** [comment]
Hi @antonioGamezll the feature was implemented and will be published in the next release. 

![Image](https://github.com/testomatio/app/assets/77803888/cc838908-b312-41f6-ac42-a3f2b4928b11)
