### ISSUE TITLE
TestRun info does't contain plan data

### ISSUE THREAD

**Issue by halyavka** [testomatio/app#788]
**Describe the bug**

**To Reproduce**
1. Create new automated test plan with few cases
2. Launch this automated plan 
3. New test run should be created
4. Call API endpoint -> https://app.testomat.io/api/{PROJECT_ID}/runs/{RUN_ID}

**Expected behavior**
Response body contains relationships object with plan data.

**Screenshots**
If applicable, add screenshots or video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Browser Version ---
 - Application: production

**Additional context**
Actual result: relationships object contains plan obj with "data": null

**Comment by TetianaKhomenko** [comment]
should be fixed in the upcoming release. please re-open the ticket if the issue persists and attach screenshots.
