### ISSUE TITLE
[BE] [FE] User get an error messages after Saving changes in test suit

### ISSUE THREAD

**Issue by AnisimovDenys03** [testomatio/app#791]
**Steps to Reproduce:**
      1. Open https://testomat.io/

 2.Sign in

 3.Go to the **“Tests”** page

4.Select an already created suite

5.Click on **“Edit”** button

6.Click on **“Save and close”** button

**Actual Result:** User get two error messages and opened **“Test not found”** page

**Expected Result:** User get **“Saved”** message

![image-20230814-142805](https://github.com/testomatio/app/assets/140817860/e8df5729-3daf-42f7-ad80-00dd8e420774)
![image-20230814-142841](https://github.com/testomatio/app/assets/140817860/9c5870e0-1931-464b-93b5-9471f8a3e5b5)
![image-20230814-142921](https://github.com/testomatio/app/assets/140817860/7225f7ef-213a-4720-9e13-f8d5548cd4ef)

**Comment by TetianaKhomenko** [comment]
The issue was fixed. The fix will be published in the next release.
