### ISSUE TITLE
[BE] [FE] User can create a "NewRunGroup" using space in Group Name

### ISSUE THREAD

**Issue by AnisimovDenys03** [testomatio/app#792]
**Steps to Reproduce:**

1. Open  https://app.testomat.io/

2. Sign in

3. Go to the **“Runs”** page

4. Click on **“New Group”** button

5. In **“Name of Group**” field past the space

6. Fill all required fields

7. Click on the **“Save**” button

**Actual Result:** User get an message **“Error: undefined method `children' for nil:NilClass”**, but folder was created

**Expected Result:** Folder wasn’t created and user get an error message **“Field is can’t be blank“**
![image-20230814-150800](https://github.com/testomatio/app/assets/140817860/01c7f31a-d894-4456-95af-5179d1a4060f)

**Comment by TetianaKhomenko** [comment]
The issue was fixed the fix will be added in the upcoming release.
