### ISSUE TITLE
Add CI Link to the public report from notifications 

### ISSUE THREAD

**Issue by bheemreddy181** [testomatio/app#794]
It would help a lot if it can create a CI link which job created this notification to the public link like below 

<img width="1323" alt="Screenshot 2023-08-18 at 1 47 00 PM" src="https://github.com/testomatio/reporter/assets/101338506/7f03dbeb-9a67-472a-9fb2-902f33c83ff9">

**Comment by TetianaKhomenko** [comment]
Hi @bheemreddy181! The feature was implemented. It will be published in the upcoming release.

https://github.com/testomatio/app/assets/77803888/c333d70b-23a7-4fe0-8ca4-a88155453bf0
