### ISSUE TITLE
Capture last login for users to understand who are actively using the platform

### ISSUE THREAD

**Issue by bheemreddy181** [testomatio/app#795]
**Is your feature request related to a problem? Please describe.**
Inability to capture who are really active on the platform

**Describe the solution you'd like**
Capture the last login for each user

**Comment by poliarush** [comment]
@Fro0z1k need to add last login date time

![2023-08-21_23 11 48@2x](https://github.com/testomatio/app/assets/325722/f78c1c1f-1335-4061-a419-91f80372f1ea)

**Comment by poliarush** [comment]
![image](https://github.com/testomatio/app/assets/325722/79124d1e-b504-4686-bd8f-4d19558c637b)

**Comment by poliarush** [comment]
@trumenov please help to fix tests

**Comment by poliarush** [comment]
application controler

**Comment by Fro0z1k** [comment]
use user.last_sign_in_at - 12 hours

**Comment by TetianaKhomenko** [comment]
Hi @bheemreddy181 the feature was implemented and it will be published in the upcoming release

![Image](https://github.com/testomatio/app/assets/77803888/27fc2180-07cb-44b3-96d1-e7b47bf2e285)
