### ISSUE TITLE
[ Slack Notifications ] Executed 0 automated tests in slack notification in case if user use TESTOMATIO_RUNGROUP_TITLE= as a parameter to launch tests

### ISSUE THREAD

**Issue by denys-iaremenko** [testomatio/app#797]
**Describe the bug**
`Executed 0 automated tests` displayed in slack notification in case is user launch tests with TESTOMATIO_RUNGROUP_TITLE=<group_name> . In case TESTOMATIO_RUNGROUP_TITLE= is not added amount of tests calculates correctly. 

**To Reproduce**
1. Set up slack integration 
2. Run command  TESTOMATIO_RUNGROUP_TITLE=<any_group_name> TESTOMATIO=<your_token> npx playwright test
3. Wait until run is completed and check slack report

**Expected behavior**
`Executed 9 automated tests` in slack message

**Screenshots**
<img width="316" alt="Screenshot 2023-08-22 at 17 41 12" src="https://github.com/testomatio/app/assets/84392142/06384804-8def-4afa-b5f0-513af24ae41e">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser N/A
 - Browser Version N/A
 - Application: production

***Additional Info***
Framework: Playwright (TS)

**Comment by TetianaKhomenko** [comment]
Hi @denys-iaremenko! The issue was fixed. The fix will be published in the upcoming release.

**Comment by TetianaKhomenko** [comment]
Hi @denys-iaremenko the fix is live now
