### ISSUE TITLE
TEAM MEMBERS: [BE] [FE] The Search operation doesn't work when in "Search Members" field put less than 3 symbols 

### ISSUE THREAD

**Issue by AnisimovDenys03** [testomatio/app#798]
**Steps to Reproduce:**

1. Go to the **"Team Members"** page
3. In **“Search Members”** field put less than 3 symbols
3. Click **“Enter”**

**Actual Result:** The search operation doesn’t work, all previous users is shown

**Expected Result:** Users with the letters entered were shown or user with this name wasn’t found

![image-20230805-123556](https://github.com/testomatio/app/assets/140817860/368d8f24-29e4-4667-80bc-fb47cec6877f)
![image-20230805-124018](https://github.com/testomatio/app/assets/140817860/be2956fb-4ead-4651-8a2e-e455ecb17ae3)

**Comment by TetianaKhomenko** [comment]
Hi @AnisimovDenys03! The search functionality becomes operational upon inputting the initial 3 characters. This adheres to the established standard behavior within the realm of search queries.
