### ISSUE TITLE
[Test Report] Increase max-hight for the logs card element

### ISSUE THREAD

**Issue by mariiakostenko** [testomatio/app#801]
**Is your feature request related to a problem? Please describe.**
After clicking "Complete log" button in test report, the current behavior does not provide an optimal experience for viewing logs. I expect max possible height of card to be displayed to increase logs visibility.

**Describe the solution you'd like**
Increase max-hight for logs card element, automatically increase height after clicking "Complete log" button.

<img width="1475" alt="Screenshot 2023-08-23 at 17 18 38" src="https://github.com/testomatio/app/assets/133783730/211e8595-a86d-4dbf-aec9-b6b6164853c7">

**Comment by TetianaKhomenko** [comment]
The feature was implemented and will be published in the upcoming release

![Image](https://github.com/testomatio/app/assets/77803888/179efb8b-227e-4f7f-bb19-bf46b8022726)
