### ISSUE TITLE
 [Runs] result details: to add active links to defects in the list of test cases

### ISSUE THREAD

**Issue by growthaccelerator** [testomatio/app#811]
**Is your feature request related to a problem? Please describe.**
If there are errors related to cases, I can filter them out and view them all at the top for convenience.
But the links to these bugs are not clickable, in order to look at a specific bug, I have to open each of them and inside test case I can already open the defect.

**Describe the solution you'd like**
It would be convenient to have an active link immediately in the list of tests cases

**Additional context**
<img width="1007" alt="image" src="https://github.com/testomatio/app/assets/99483691/96fed60b-69d7-4c87-93a0-104187f9b9ca">

**Comment by poliarush** [comment]
@littlefrontender 
i think we should outtline list of all issues in simplified version of test report 

related to https://github.com/testomatio/testomatio/issues/3084
related to https://github.com/testomatio/testomatio/issues/3083

**Comment by poliarush** [comment]
@growthaccelerator as workaround you can access list of defects in detailed view 
![2023-09-08_21 49 42](https://github.com/testomatio/app/assets/325722/64d678a5-a488-4a3e-97f8-704e0582dddd)

**Comment by TetianaKhomenko** [comment]
Hi @growthaccelerator! The feature was implemented and will be published in the upcoming release. 
Also attaching short demo video 

https://github.com/testomatio/app/assets/77803888/3610405c-5401-4c28-b56b-1ea5fc26833b
