### ISSUE TITLE
[Tests] filters: filters by TAGs doesn't work

### ISSUE THREAD

**Issue by growthaccelerator** [testomatio/app#813]
**Describe the bug**

**To Reproduce**
1. Go to Tests
2. Click Filters
3. Choose TAG
4. Click Apply

**Expected behavior**
Displays test cases with chosen TAG 

**Actual result**
Test cases with TAG don't display.
The same behavior for TestPlan creation and try to filter TestCases by TAGs

**Screenshots**
https://github.com/testomatio/app/assets/99483691/5640df29-a30f-4583-9861-bd7a5b4a750b

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser [chrome]
 - Browser Version [116.0.5845.110]
 - Application: [production]

**Comment by poliarush** [comment]
@growthaccelerator 

could you please go to Settings and reindex tags

![2023-09-06_16 48 27@2x](https://github.com/testomatio/app/assets/325722/b4ff0fe5-0df3-4d1c-910a-6437ac5f0d2c)

and try again

**Comment by TetianaKhomenko** [comment]
Hi @growthaccelerator and @YuriiChernikov! The issue should be fixed in the upcoming release. Please re-open this ticket if the issue reoccurs.

**Comment by TetianaKhomenko** [comment]
Hi @growthaccelerator  and @YuriiChernikov !  The fix should be live now

**Comment by YuriiChernikov** [comment]
@TetianaKhomenko  thank you very much. It works now, but this does not work in reverse; if you remove the filter, the number of selected test cases does not change
<img width="980" alt="image" src="https://github.com/testomatio/app/assets/144252457/aa54b6ad-64a3-4450-842e-53914f05afab">
