### ISSUE TITLE
Some folders could not be deleted 

### ISSUE THREAD

**Issue by kreminmaria** [testomatio/app#814]
**Describe the bug**
The following folders could not be deleted 
@Sb06c60b2
@S2459edd2
in the project https://app.testomat.io/projects/helsi-web-24e49/

**Expected behavior**
Folder is deleted right after confirming the deletion and not coming back

**Screenshots**

https://github.com/testomatio/app/assets/14187016/f9c7a975-3816-454e-a7d1-21bf207e03ab

**Comment by TetianaKhomenko** [comment]
Hi @kreminmaria! Could you please re-check this issue?
