### ISSUE TITLE
A lot of cases disappers after merging branch

### ISSUE THREAD

**Issue by kreminmaria** [testomatio/app#815]
**Describe the bug**
In project https://app.testomat.io/projects/helsi-web-24e49/
The following test cases disappear 
@Te4cebf32
@T34ecf4be
@T28a63723
@Ta97da298
@T08440b01
@Tc0b990c9
@T96101fb9
@Tee0898a2
@Tca6d45dc
@Tcc2f2ee9
@T55609a01
@T6ac8ad01
@Tbda51653
@T00b73b5b
@T08738381
@Ta0e51511
@T9437b8c3
@T22091a4e
@T2034ef65
@T25b849a4
@Tc78718be
@Tb3656f7c
@T2d0bfba0
@T3905a1e6
@T7e2caaf2
@T89358fea
@Tf573e331
@Ta9257041
@T0ccc2956
@Tdd2c0ffb
@T13aa2e57
@T9d96562b
@Tcf41c79f
@Tf04481d8
@T5bf9b42e
@T7d50f3d8
@Tcac82a8e
@T2cfd7740
@T7fc9a442
@T6d62afff
@T4b7fd95e
@Tb4a70a5b
@Tc469f431
@Te5451d6d
@T4b23e4d8
@T4a5645a8
@T771fb1a8
@Tc1971b70
@T6d629735
@T7fc9a442
@T4b7fd95e
@T6d62afff
@Tb4a70a5b
@T5bf9b42e
@T7d50f3d8
@Tcac82a8e
@T2cfd7740
@Tbb5c51d9
@T1c41ac86
@T7e2caaf2

after merging branches 
https://app.testomat.io/projects/helsi-web-24e49/branches/annabond_his_admissionencounter_add_admission_2
https://app.testomat.io/projects/helsi-web-24e49/branches/annabond_his_admissionencounter_add_admission_3

**Comment by poliarush** [comment]
@kreminmaria please invite support team to your project

![2023-09-06_23 26 48@2x](https://github.com/testomatio/app/assets/325722/0eb7d735-d2cc-4d72-96ae-9c9434344f60)

**Comment by kreminmaria** [comment]
not valid anymore. our bad. we deleted suite with those test cases
