### ISSUE TITLE
[TestPlan] RunGroups: Unable to add runs to a group created in the TestPlan tab

### ISSUE THREAD

**Issue by YuriiChernikov** [testomatio/app#818]
**Describe the bug**
I have a set of test cases  in TestPlan and I need to make a Run group called Prod regression.
In this group should be 4 Runs with the same test cases, but different Environments.
And two Runs without Environments, but one for the Web project, one for Mobile.  I can't configure them with envs because they have a different set of checks
Now I managed it to implement through a Group in which I created 4 Runs and 1 sub-group in which I created 2 more Runs for Web and Mobile.

I would like to be able to add any runs and any number of runs to the group. But in GroupRuns there is no option to add a manual run only for a SubGroup

**To Reproduce**
1. Create 'TestPlan' with TestCases
2. On tab TestPlan click 'Launch'
3. Chose TCs and 4 Environments for the same TCs. 
4. Click 'Launch All' or 'Launch in Sequence' 
5. Go to 'Runs' open created GroupRuns
6. Try to Add one more Manual Run

**Expected behavior**
I can add one more manual Run like in Group which I create in Runs tab.

**Actual behavior**
There is no button to Create new Manual Run, only SubGroup or AutomationRun
<img width="753" alt="image" src="https://github.com/testomatio/app/assets/144252457/c56545d6-6977-4a3c-8520-927a37efc124">

**Screenshots**
If applicable, add screenshots or video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [any]
 - Browser Version [e.g. 22]
 - Application: [production]

**Comment by TetianaKhomenko** [comment]
Hi @YuriiChernikov! For now, we added the option to add existing Runs to a Group. Please see the demo video.

https://github.com/testomatio/app/assets/77803888/425ee751-412a-4e94-980a-8ad1eff1d224

**Comment by TetianaKhomenko** [comment]
Sorry, this can't be done. Multienv is more Run than a Rungroup. Even technically it is Rungroup...

You can add some new Runs into it as it contains a list of the same Runs that differ only by environment
If you introduce some new Run without that constraint this creates a data mess

**Comment by YuriiChernikov** [comment]
Thank you @TetianaKhomenko , I understand
