### ISSUE TITLE
Filters in Tests tab is not working

### ISSUE THREAD

**Issue by kreminmaria** [testomatio/app#819]
**Describe the bug**
No correct test cases are returned after using filters in Tests tab

**To Reproduce**
1. Go to Tests 
2. Try to use filter by priority, by labels, by tag

**Expected behavior**
Correct test cases are returned by filter

**Screenshots**

https://github.com/testomatio/app/assets/14187016/c00b52e2-c3f4-41e4-8765-e704e54dd251

https://github.com/testomatio/app/assets/14187016/eab9ea55-4911-4b10-b6c1-43013699f89d

https://github.com/testomatio/app/assets/14187016/0e8627d5-6e86-41a3-a5ae-62a33e9e9d4a

**Comment by TetianaKhomenko** [comment]
hi @kreminmaria have you tried re-indexing tests in project settings?

**Comment by kreminmaria** [comment]
@TetianaKhomenko yeap. and recalculated tags as well 
and tags still contain not existing cases

**Comment by TetianaKhomenko** [comment]
The issue was fixed. The fix will be published in the upcoming release.

**Comment by TetianaKhomenko** [comment]
@kreminmaria the fix is live now. Could you please check on your side?
