### ISSUE TITLE
severity is not aligned to title field and important items is on next line

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#82]
![image](https://user-images.githubusercontent.com/325722/83044267-3f649c80-a044-11ea-8294-49b445daa673.png)

![image](https://user-images.githubusercontent.com/325722/83044309-4ab7c800-a044-11ea-8ab0-8c6408e9dc63.png)

**Comment by DavertMik** [comment]
UX was updated

![image](https://user-images.githubusercontent.com/220264/94319230-d9a50480-ff92-11ea-8d26-7580492adaf5.png)
