### ISSUE TITLE
date period filter for failure, issues, defects analytics widget

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#820]
**Is your feature request related to a problem? Please describe.**

> Also, we can see the uniques errors via the dashboard, is there another entry point ?
> Is it the one accessible via the dashboard ? 

It seems some failure disappear if the new run don't reproduce the error (so if I have a test in error on my first run, then run the same suite and there is no error, i will not find the first error on the report). It is not always the case but I have some error that disappeared.

**Describe the solution you'd like**
- date period filter for failure, issues, defects analytics widget

**Describe alternatives you've considered**
no

**Additional context**
Need for deel.com

![2023-09-08_20 15 27@2x](https://github.com/testomatio/app/assets/325722/42bbd6d1-4d3e-4363-a6e7-e7109daac23e)

![2023-09-08_20 15 49@2x](https://github.com/testomatio/app/assets/325722/cd7a3750-6e79-4fb4-ab11-4a08db575a71)

![2023-09-08_20 16 08@2x](https://github.com/testomatio/app/assets/325722/5efcc34a-82d1-41a1-8576-aac29ed8980f)

**Comment by poliarush** [comment]
related to https://github.com/testomatio/auth0-issues/issues/85

**Comment by TetianaKhomenko** [comment]
implemented for all widgets

![CleanShot 2024-01-15 at 12 51 51@2x](https://github.com/testomatio/app/assets/77803888/d430933a-f010-466b-8bbb-f0d53ee107dd)
