### ISSUE TITLE
Some tests can't be deleted 

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#822]
**Describe the bug**
The issue appears to multiple users.

here are some of them

> users deleted tests from the project, from within Testomat, but it is still displaying the deleted test suites and displays errors. The deleted test suites show intermittently and disappear if you do a refresh of the browser page. We have had a problem with this project before and had to manually remove items from this project.

> facing issue with this folder - doesn’t let me delete that as well

![CleanShot 2023-09-12 at 17 21 17@2x](https://github.com/testomatio/app/assets/77803888/1ac48024-fc48-448c-a28b-aed55c50ed3f)

![CleanShot 2023-09-12 at 17 22 21@2x](https://github.com/testomatio/app/assets/77803888/c9b43b17-452c-4bb0-811b-b5bbca0434e0)

**Comment by poliarush** [comment]
https://testomatio.slack.com/archives/C03DY1CG353/p1694522686798049
https://testomatio.slack.com/archives/C04PM8N3KGA/p1694468583221039

**Comment by TetianaKhomenko** [comment]
fixed
