### ISSUE TITLE
Creating a test plan with filter always displays 150 tests

### ISSUE THREAD

**Issue by TheZZ13** [testomatio/app#823]
**Describe the bug**
When creating a test plan with a filter applied always displays 150 tests. 

**To Reproduce**
1. Be sure to have the multiple labels or tags assigned to 200 tests.
2. Select Plans from the left menu
3. Select + from the upper right to create a new plan
4. Select Manual
5. Enter a title
6. Select the Filter button
7. Select Filter by Field (drop down) or Select by Tag. 
8. Select a label or tag that has more than 200 tests assigned.
9. The plan displays 150 tests selected.

**Expected behavior**
All 200 tests should display as selected.

**Screenshots**
<img width="1353" alt="Screenshot 2023-09-11 at 3 26 04 PM" src="https://github.com/testomatio/app/assets/36581640/8227b1a7-abbb-4ece-b7cd-0a4f7398c671">
<img width="1357" alt="Screenshot 2023-09-11 at 3 29 46 PM" src="https://github.com/testomatio/app/assets/36581640/25912321-7b3e-4227-b649-192bc12e8a84">

**Desktop (please complete the following information):**
 - OS: Mac 13.3.1
 - Browser: Chrome
 - Browser Version 116
 - Application: Production

**Additional context**
This is happening in more than one project and even after Reindexing one of the problematic projects.

**Comment by TetianaKhomenko** [comment]
The issue was fixed. The fix will be published in the upcoming release.
