### ISSUE TITLE
400 (Bad Request) while DELETing an jira issue from testRUN

### ISSUE THREAD

**Issue by RohalskyiOleksii** [testomatio/app#826]
**Describe the bug**
400 (Bad Request) while DELETing an jira issue from testRUN
Precondition; linked Jira issue to testRUN. delete issue from Jira
**To Reproduce**
1. Go to testRUN with linked Jira issue
2. Click on X button to unlink ![image](https://github.com/testomatio/app/assets/132286699/88da530e-6b7b-4d74-8b94-0aacf2dba53c)
3. click OK
4. See error ![image](https://github.com/testomatio/app/assets/132286699/163f5a64-21a4-4873-af4a-661fe2b6496c)

**Expected behavior**
no error on issue unlink

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
  - Browser Version  117.0.5938.92 (Official Build) (64-bit)
 - Application: production

**Comment by littlefrontender** [comment]
@DavertMik, please check webhooks

**Comment by poliarush** [comment]
@RohalskyiOleksii did you installed Webhook for JIRA Profile? 

![2023-09-26_13 49 15@2x](https://github.com/testomatio/app/assets/325722/b760dac9-30bd-426c-8673-39abb60c13f0)

**Comment by poliarush** [comment]
@RohalskyiOleksii we deleted these links for you, please check it,
but for the next time, please install webhook so it's cleared automatically when jira ticket is deleted.

**Comment by TetianaKhomenko** [comment]
the issue was re-tested and resolved as a fixed
