### ISSUE TITLE
Test case templates - Ability to add tags to it

### ISSUE THREAD

**Issue by Cervi18** [testomatio/app#828]
**Is your feature request related to a problem? Please describe.**

We would like to setup the template with specific tags to it. Adding them in advance before creating the test case. 
Currently, there isn't said option to define this in the template

**Describe the solution you'd like**

Ability to go more in depth when defining the template.

**Describe alternatives you've considered**

N/A. There isn't one. 

**Additional context**

Currently this isn't the option in the tool. 

<img width="1792" alt="image" src="https://github.com/testomatio/app/assets/73466037/a0764d58-94c8-43b0-9705-fc8d093ec0ba">

**Comment by yammoon** [comment]
@TetianaKhomenko @poliarush I think we accidentally didn't open this in "moonactive-issues", is it possible to move it?

**Comment by TetianaKhomenko** [comment]
@yammoon sorry there is no way to copy it to your repo. But you can create this issue in
