### ISSUE TITLE
[Public reports] add Environment filed

### ISSUE THREAD

**Issue by YuriiChernikov** [testomatio/app#830]
When I have a test run with different environments and then want to create a public report, it would be a good idea to see what the environment is, since it's impossible to understand right now. They look the same and for PM it's an issue.

https://app.testomat.io/report/8a1ad3f8/4119e0a8-ac30-4a71-be04-6e20ad6f81f6
https://app.testomat.io/report/5305cf4d/d797a98a-b4b1-4dd2-b0c4-d0681255ab43

Just add this field
<img width="440" alt="image" src="https://github.com/testomatio/app/assets/144252457/9e88b0b9-6c62-4828-a79a-ef9260070fef">

**Comment by poliarush** [comment]
add % to graph 

![Image](https://github.com/testomatio/app/assets/325722/ccf212bb-6671-4243-b462-4ab45487f5bf)

**Comment by littlefrontender** [comment]
@poliarush i created new separate issue https://github.com/testomatio/testomatio/issues/3205

**Comment by TetianaKhomenko** [comment]
Hi @YuriiChernikov the feature was implemented. It will be published in the upcoming release


![Image](https://github.com/testomatio/app/assets/77803888/78693fc2-6854-4ed1-8cea-aea7ac8ec8eb)
