### ISSUE TITLE
Pop-up on sharing report publicly

### ISSUE THREAD

**Issue by guilaharis** [testomatio/app#834]
**Description**
When sharing a report publicly, there is a pop-up showing 1, and the percentages are not visible. 

**Steps To Reproduce**
1. Complete a manual run
2. Share it publicly

**Expected behaviour**
The link opens a page where the percentages of passed/failed/skipped can be seen on a piechart

**Environment**
 - MacOS Ventura 13.4.1
 - Chrome, Version 116.0.5845.187

https://github.com/testomatio/app/assets/72572005/1e27567b-0e4b-4e7e-81ad-a1adbb51f1da

**Comment by poliarush** [comment]
related to https://github.com/testomatio/app/issues/834

**Comment by TetianaKhomenko** [comment]
Hi @guilaharis! The issue should be fixed. Could you please check on your side and let us know if it is ok now?

**Comment by TetianaKhomenko** [comment]
Hi @guilaharis! Could you please confirm that the issue was fixed?

**Comment by TetianaKhomenko** [comment]
closing ticket as done
