### ISSUE TITLE
'create/edit/delete' buttons for tests

### ISSUE THREAD

**Issue by KateDiminutive** [testomatio/app#837]
**Describe the bug**
It is not possible to use the control buttons on the project's shared page.
**To Reproduce**
1. Go to project page
2. Hover the cursor over the buttons 'create/edit/delete' for test
3. Try to click on 'create/edit/delete' 

**Expected behavior**
When you press the 'create/edit/delete' buttons, actions corresponding to the selected button occur.
**Screenshots**
https://prnt.sc/CGFQnEtowPtT   https://prnt.sc/HZWwvPAfgCtW

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser GChrome
 - Browser Version 117.0.5938.92
 - Application: production

**Additional context**
I think tooltips interfere with clicking.

**Comment by TetianaKhomenko** [comment]
Hi @KateDiminutive the issue was fixed. The fix will be published in the upcoming release 

https://github.com/testomatio/app/assets/77803888/cf5d569a-7191-429d-8d1c-3441b34a85dd
