### ISSUE TITLE
Mark checkbox with a "some selected" state if some child elements are selected

### ISSUE THREAD

**Issue by ivasholeksii** [testomatio/app#838]
**Is your feature request related to a problem? Please describe.**
In a list of test cases from the folder when creating a Run I would like see whether some are already selected in the child nodes. If not all are selected - folder's checkbox is being shown as "not selected"

**Describe the solution you'd like**
Introduce intermediate step of the checkbox

**Describe alternatives you've considered**
As an alternative I have to expand each folder to check whether there are any selected elements.

**Additional context**
<img width="616" alt="Screenshot 2023-10-04 at 09 30 10" src="https://github.com/testomatio/app/assets/72669639/f294a883-1b88-412d-bcd5-1e59c4b84ea9">

Example of intermediate state: 
https://www.jqueryscript.net/images/jQuery-Plugin-To-Create-Indeterminate-Checkboxes-Tristate.jpg

**Comment by poliarush** [comment]
@ivasholeksii are you talking about test tree in test design module?

is it about this screen? 
![2023-10-04_10 10 15@2x](https://github.com/testomatio/app/assets/325722/bab7de33-c905-4a27-9640-fa5e750fd179)

**Comment by ivasholeksii** [comment]
It is about `/plans/new` page.

**Comment by poliarush** [comment]
so it's here, right?

![2023-10-04_10 28 57@2x](https://github.com/testomatio/app/assets/325722/531bbb9c-d8d1-42af-9a04-0d07206ec378)

**Comment by ivasholeksii** [comment]
correct. But in general - it would be nice to have this for the whole app for such conditions :)

**Comment by poliarush** [comment]
so, you're looking for such behaviour? 

![2023-10-04_10 29 53](https://github.com/testomatio/app/assets/325722/67e44596-a1d7-402f-9893-d94ce4bbee38)

if so, it will be released in next version, I guess next week

**Comment by ivasholeksii** [comment]
yes. am I doning smth wrong and it exists already? 😅

**Comment by ivasholeksii** [comment]
Thank you!

**Comment by poliarush** [comment]
@ivasholeksii let's us test it a bit, and we will close it by ourselves @TetianaKhomenko

**Comment by TetianaKhomenko** [comment]
this behavior was implemented and will be published in he upcoming release

https://github.com/testomatio/app/assets/77803888/0fc38fb4-3209-4ec6-aab1-7b4db065d2cd
