### ISSUE TITLE
IMPORTS: User can import tests with invalid format when choosen any other system except testomatio

### ISSUE THREAD

**Issue by AnisimovDenys03** [testomatio/app#839]
Description
**Steps to Reproduce:**

1. Open the **Imports** page
2. Click on the **“Import from CSV”** button
3. Choose any **Bug Tracking System EXCEPT TESTOMATIO** in **“Import Format”** filed
4. Click on the **“Choose file”** button
5. Choose the file with **“.doc“** format
6. Click **“Create”** button

**Actual Result:** The User got a message **“Import has finished, open tests  to see the updates”**.

**Expected Result:** The User got a message **“Import has failed, open latest imports to see details”**.
![image-20231004-184257](https://github.com/testomatio/app/assets/140817860/5d892c1f-7a67-44c2-b0a0-be8fa1a8a5c1)
![image-20231004-184442](https://github.com/testomatio/app/assets/140817860/b0873683-7880-423c-a7bf-5ec52d25a204)
![image-20231004-184604 (1)](https://github.com/testomatio/app/assets/140817860/8782bcc2-45ac-448b-b4f4-23b92f9659b7)

**Comment by TetianaKhomenko** [comment]
Hi @AnisimovDenys03! The issue was fixed. The fix will be published in the upcoming release. 

![Image](https://github.com/testomatio/app/assets/77803888/0b49a818-62be-4343-852b-ca59b666d17a)
