### ISSUE TITLE
Show all path to the test when applying the filter

### ISSUE THREAD

**Issue by kreminmaria** [testomatio/app#840]
I would love to see completed paths to the test when applying the filter to the tests. One folder could be not too informative 

![image](https://github.com/testomatio/app/assets/14187016/6204bf7c-4dd9-40b1-81d6-d40b56006b9e)
![image](https://github.com/testomatio/app/assets/14187016/09c9bac7-47b6-42e7-9aea-521409a83471)

**Comment by poliarush** [comment]
@DavertMik need to discuss this

**Comment by littlefrontender** [comment]
@DavertMik backend required. Add path to filter suites, please

**Comment by TetianaKhomenko** [comment]
Hi @kreminmaria! The feature was implemented and it's live now. 

![Image](https://github.com/testomatio/app/assets/77803888/5dda4845-16e1-4515-b678-11f5a5d419f2)
