### ISSUE TITLE
Capability to link selected test cases to a jira issue

### ISSUE THREAD

**Issue by tikolakin** [testomatio/app#846]
**Is your feature request related to a problem? Please describe.**
At the moment there is no fast way to link multiply test case to a jira ticket
Instead of linking each test individually. The current approach of bulk edit could be extended to to include option to link a Jira issue. 

**Describe the solution you'd like**
Select multiply test cases in the test list view
In the selection panel I want a link issue button (similar as with label and tags already)
So that selected issue could be linked to a Jira issue
<img width="833" alt="image" src="https://github.com/testomatio/app/assets/5860505/4c5292ca-a685-4a01-89f2-7fb6836848e6">

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin! The feature was implemented and it will be published in the upcoming release. 

![Image](https://github.com/testomatio/app/assets/77803888/f8fd3ee2-61f5-4408-b85d-d4ca359685be)
