### ISSUE TITLE
Filtering results doesn't show all tests

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#847]
**Describe the bug**
When filtering tests on Tests page users will get only 30 tests. 
It looks like a pagination issue.

**To Reproduce**
1. open a project
2. assign a label to 35+ tests / suite with 35+ tests
3. filter tests by this label
4. try scroll-down
5. see tests don't upload

**Expected behavior**
all tests should be shown when filtering results scroll-down

**Screenshots**

![CleanShot 2023-10-24 at 10 06 35@2x](https://github.com/testomatio/app/assets/77803888/6e47cd0e-8aa7-4904-a6fd-9ead288863da)

https://github.com/testomatio/app/assets/77803888/fb617859-21dc-4df5-8d6f-441c9d4ef957

**Comment by littlefrontender** [comment]
@DavertMik please check this

**Comment by TetianaKhomenko** [comment]
needed for https://github.com/testomatio/moonactive-issues/issues/83

**Comment by TetianaKhomenko** [comment]
fixed
