### ISSUE TITLE
add possibility to multiselection edit tests priorities 

### ISSUE THREAD

**Issue by RohalskyiOleksii** [testomatio/app#850]
**Is your feature request related to a problem? Please describe.**
No possibility to bulk edit tests priorities.

**Describe the solution you'd like**
add priority edit to multiselection
![image](https://github.com/testomatio/app/assets/132286699/a459ef9b-4d33-4d23-83fd-d04a598f4219)

**Comment by TetianaKhomenko** [comment]
Hi @RohalskyiOleksii! The feature was implemented and will be published in the upcoming release.

![CleanShot 2023-11-17 at 19 18 27@2x](https://github.com/testomatio/app/assets/77803888/4a8035b7-5679-4978-a3cc-b56e6508be57)
