### ISSUE TITLE
Tree View for public report with correct order of cases

### ISSUE THREAD

**Issue by RohalskyiOleksii** [testomatio/app#851]
**Is your feature request related to a problem? Please describe.**
People who open public report can't see the suites tree structure and correct order of cases.
![image](https://github.com/testomatio/app/assets/132286699/24aa0cf4-f9c7-47ed-8a29-5f889c6d4981)

**Describe the solution you'd like**
_add a tree view option_ to view public report like it is possible while performing test run. +add an option to filter test by status
![image](https://github.com/testomatio/app/assets/132286699/42249209-e702-4f00-8359-56643015105d)

**Comment by littlefrontender** [comment]
backend required

**Comment by TetianaKhomenko** [comment]
+ add tests search

**Comment by TetianaKhomenko** [comment]
@littlefrontender as an example, attaching html report screenshot 

![CleanShot 2024-04-19 at 15 01 58@2x](https://github.com/testomatio/app/assets/77803888/e8fbd721-f9b9-4b8d-abfb-774b26df62be)

**Comment by TetianaKhomenko** [comment]
Hi @RohalskyiOleksii! Unfortunately there is no way to introduce test tree in public report, but we added filtering by test status, search by test title and improved tests order. Improvements will be published in the upcoming release.
