### ISSUE TITLE
add possibility to view attachments of results in public report

### ISSUE THREAD

**Issue by RohalskyiOleksii** [testomatio/app#852]
**Is your feature request related to a problem? Please describe.**
attachment to test result can`t be seen in public report
![image](https://github.com/testomatio/app/assets/132286699/16a489e2-1c2c-4898-ac86-9da683d33e1e)

**Describe the solution you'd like**
add possibility to view attachments in public report

**Comment by littlefrontender** [comment]
@RohalskyiOleksii  it's already implemented. You can add image to description by markdown https://docs.testomat.io/getting-started/test-design/#how-to-add-an-attachment-to-a-test

![Image](https://github.com/testomatio/app/assets/79913874/95971c17-0323-444b-9816-e2d22a7a7693)

**Comment by TetianaKhomenko** [comment]
@RohalskyiOleksii please let us know if the feature works well on your side.

**Comment by RohalskyiOleksii** [comment]
@littlefrontender @TetianaKhomenko are we all talking about same thing? issue was raised to add image preview of testcase RESULT from test result in test RUN, not test description itself from repository. hope this image will help to clear things out:
![image](https://github.com/testomatio/app/assets/132286699/5b2be524-2cee-49d3-842d-16ddc41ca56d)

**Comment by TetianaKhomenko** [comment]
Hi @RohalskyiOleksii! Thanks for the clarification. I think we are on the same page now :)

**Comment by littlefrontender** [comment]
@Fro0z1k Please add testrun's :attachments for report, I couldn't do that. 



![Image](https://github.com/testomatio/app/assets/79913874/4b6e1d40-c400-4e66-ab42-7c193075bb3a)

**Comment by TetianaKhomenko** [comment]
Hi @RohalskyiOleksii! The feature has been implemented. It will be published in the upcoming release. Attaching a short demo below

https://github.com/testomatio/app/assets/77803888/2d2b0881-4b8d-49ba-8328-415e9ccbadfb

**Comment by TetianaKhomenko** [comment]
Hi @RohalskyiOleksii! The feature is live now. Thanks for the nice feature request ;)
