### ISSUE TITLE
Make users aware of the extended Edit mode

### ISSUE THREAD

**Issue by tikolakin** [testomatio/app#855]
**Is your feature request related to a problem? Please describe.**
The text input editor (ex. folder/suite/test edit form) has a whole new world of editing experience.
Yet, I found this feature only by accident when I hit cmd+e in the text field (actually, it was the input of a Slack notification rule).
And **find and replace** feature popups! 
<img width="1509" alt="image" src="https://github.com/testomatio/app/assets/5860505/946dd629-04cf-4fbf-8951-02c0f54e9bec">

Then I wrote to the support channel asking why they hid such a killer feature.
And they said there is a **F1** short key to open the rest of the features, ex. multicursor...
I wish I had known about that feature much earlier I would need to use VS code to edit my content.

**Describe the solution you'd like**
As for me, the easiest solution would be just to update the help information in the shortcuts modal 
with up-to-date information about 
<img width="912" alt="image" src="https://github.com/testomatio/app/assets/5860505/9691833a-fd73-452b-a27f-a889c390689e">

**Describe alternatives you've considered**
Given not all fields have extended edit mode - maybe it would be a good idea to add a toolbar to fields that support "advanced" edit mode
Similar to the current field I am writing this text
As in such toolbar edit features would be quite prominent.

<img width="904" alt="image" src="https://github.com/testomatio/app/assets/5860505/d58d1e08-5b1a-41b1-84dc-d1291db19e00">
I think reusing well-accepted and generally good approaches isn't harmful 👍🏻 

**Additional context**
Thank you for such a great edit mode functionality.  It makes editing experience similar to what you get in a regular IDE

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin! The feature has been implemented and will be added to the next release ;)

https://github.com/testomatio/app/assets/77803888/7b76d379-a81b-4c6f-8e4f-a3b6b6507736
