### ISSUE TITLE
Send notification when last "registered" executors completes

### ISSUE THREAD

**Issue by tikolakin** [testomatio/app#858]
**Is your feature request related to a problem? Please describe.**
As outlined in the documentation 
When testomatio reports into a shared test run
`TESTOMATIO_SHARED_RUN=1 TESTOMATIO_TITLE="UniqTitleForThisBuild" <actual run command>`
Then each executor finishes a test run.
Such an approach results in notifications (we use Slack) being sent multiple times when each executor completes a test run.
Additionally, each notification sends a current state of test run - until the last notification arrives every previous notification is misleading as they don't represent a complete run.
![image](https://github.com/testomatio/app/assets/5860505/d4492c0f-bcd4-4c11-860d-7c2b7577be1c)

**Describe the solution you'd like**
Send a notification when the last "registered" executor finishes the test run

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by DavertMik** [comment]
Sorry, we don't know what is last registered executor in this case.
There can be as many runs under the same value.

You can probably update the notification rule to be triggered only a specific number of tests are reported.

Send message when tests > 100

We will look into other ideas to improve report notifications
