### ISSUE TITLE
Adding tests\suites to launched testRun not corresponds to repository structure.

### ISSUE THREAD

**Issue by RohalskyiOleksii** [testomatio/app#860]
**Describe the bug**
Adding tests\suites to launched testRun not corresponds to repository structure.

**To Reproduce**
1. Go to previously launched in-progress testRun
2. Click on edit
3. Add more tests from other suites
4. check testRun structure

**Expected behavior**
Added testRun structure corresponds to test repository structure

**Actual behavior**
newly added test\suites to launched testRun - are added to the last suite instead of corresponding number of repository structure
**Screenshots**
![image](https://github.com/testomatio/app/assets/132286699/4e30bd71-4a6e-4d04-84de-01e9f569081f)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome
 - Application: production
 
_this behaviour is quite **critical** for us because he had no such issue on previous TMS_

**Comment by TetianaKhomenko** [comment]
Hi @RohalskyiOleksii! The issue was fixed and will be published in the upcoming release.
