### ISSUE TITLE
Checkbox  Multiselection logic in repository differs from testRun logic

### ISSUE THREAD

**Issue by RohalskyiOleksii** [testomatio/app#864]
**To Reproduce**
1. Go to repository
2. Click on multiselection
3. Check that multiselection can select all items in folder but can`t deselect contents
![image](https://github.com/testomatio/app/assets/132286699/8e95c8ef-0dda-42e0-be72-560c48a49893)
4. Go to testRun
6. Check that multiselection can select all items in folder but CAN deselect contents afterwards

**Expected behavior**
Unify all multiselection logic to possibility of deselection contents afterwards![image](https://github.com/testomatio/app/assets/132286699/f2303e18-3d44-45f6-8813-9c9ebaf5ed0c)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser  chrome

**Comment by TetianaKhomenko** [comment]
Hi @RohalskyiOleksii! We added "Select all tests" option for suites, so you can switch and deselect tests. Attaching a demo video below. The feature will be published in the upcoming release. Please let us know if this solution works for you.

https://github.com/testomatio/app/assets/77803888/7d2a3304-5b54-477d-9474-8cddc5cd3257
