### ISSUE TITLE
add Markdown quick actions in test suites

### ISSUE THREAD

**Issue by RohalskyiOleksii** [testomatio/app#866]
**Is your feature request related to a problem? Please describe.**
Markdown quick actions are present in testcases but absent in test suites, even tho they are supported there

**Describe the solution you'd like**
add Markdown quick actions in test suites
![image](https://github.com/testomatio/app/assets/132286699/ee918186-f21b-4bcd-b6a3-4fb582cc62cd)

**Comment by TetianaKhomenko** [comment]
Hi @RohalskyiOleksii! The feature was implemented and will be published in the next release ;)

![Image](https://github.com/testomatio/app/assets/77803888/ea22f138-2223-494d-8a6f-b8deb37ac0f2)
