### ISSUE TITLE
Test run editor expand bar and scroll bar are not following user in long lists

### ISSUE THREAD

**Issue by RohalskyiOleksii** [testomatio/app#872]
**Is your feature request related to a problem? Please describe.**
while editing test run if the list is long - expand bar and scroll bar are not following user which makes UX difficulties 

**Describe the solution you'd like**
expand bar and scroll always visible and accessible

https://github.com/testomatio/app/assets/132286699/d10d5249-e416-42d0-8f7b-d4e10747402f

**Comment by TetianaKhomenko** [comment]
Hi @RohalskyiOleksii! The issue has been fixed. The fix will be published in the upcoming release.

**Comment by TetianaKhomenko** [comment]
Hi @RohalskyiOleksii! This fix is live now.
