### ISSUE TITLE
All indents before the text disappear in review mode

### ISSUE THREAD

**Issue by inf0lio** [testomatio/app#875]
**Describe the bug**
Now it's impossible to save the text peace in test case with saving indents(whitespaces/tabs) before it.

**To Reproduce**
1. Open a test case;
2. Click on "Editor" button;
3. Put something like:
```
{
    "fruit":"Apple",
    "sizes":{
        "foo":"Large",
        "bar":"Small"
    },
    "color":"Red"
}
```
4. Click on "Preview" button;
5. I see the code was formatted like:
```
{
"fruit":"Apple",
"sizes":{
"foo":"Large",
"bar":"Small"
},
"color":"Red"
}
```

**Expected behavior**
The structure of the text formatting is the same as in "Editor" mode.

**Artifacts**
https://github.com/testomatio/app/assets/17621498/4461bbf5-ef6b-48fe-aa2f-9599b48d4961

**Desktop (please complete the following information):**
 - OS: macOS 14.1
 - Browser: Chrome
 - Browser Version: 119.0.6045.123
 - Application: Production

**Comment by TetianaKhomenko** [comment]
Hi @inf0lio! The issue was fixed. The fix will be published in the upcoming release.

<img width="752" alt="CleanShot 2023-11-17 at 12 39 07@2x" src="https://github.com/testomatio/app/assets/77803888/d7e058d2-12aa-4796-b75a-785aabacfe8d">
