### ISSUE TITLE
Creating an empty Plan adds all tests

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#876]
**Describe the bug**
Users may need to create empty plans for some reason. 
Now system adds all existing tests instead of showing 0 when there are no picked tests in a plan

**To Reproduce**
1. open a project
2. go to Plans
3. create new plans
4. don't add any tests
5. save
6. see all tests from the project added

**Expected behavior**
plan with 0 tests shows 0 tests

**Screenshots**

![CleanShot 2023-11-20 at 19 28 16@2x](https://github.com/testomatio/app/assets/77803888/cd0c6c19-7af0-44b0-9228-dd065492cda5)

<img width="1243" alt="CleanShot 2023-11-20 at 19 27 58@2x" src="https://github.com/testomatio/app/assets/77803888/0785b162-2a58-488e-9544-fce412e082ae">

![CleanShot 2023-11-20 at 19 27 18@2x](https://github.com/testomatio/app/assets/77803888/6d53594b-b16b-45d1-983d-339532da1ac7)

https://github.com/testomatio/app/assets/77803888/20092932-b7ea-42cc-aef2-f6529158fec2

**Comment by littlefrontender** [comment]
i send to backend empty arrays, but get back all tests



![Image](https://github.com/testomatio/app/assets/79913874/538345a7-ba8f-4719-9229-83077b0d3edf)
![Image](https://github.com/testomatio/app/assets/79913874/f005bbfc-ef79-43a1-9e66-b13bca3372ee)
![Image](https://github.com/testomatio/app/assets/79913874/b7752cd2-7bee-4701-9e42-04c09ee1b49f)

**Comment by TetianaKhomenko** [comment]
The issue was fixed. The fix will be published in the next release.
