### ISSUE TITLE
Test description pointer incorrect placement and visibility 

### ISSUE THREAD

**Issue by RohalskyiOleksii** [testomatio/app#877]
**Describe the bug**

**To Reproduce**
1. Go to test description
2. Try to edit or add text in middle or end of line

**Expected behavior**
Pointer correct placement and visibility 

**Screenshots**

https://github.com/testomatio/app/assets/132286699/a44735a1-514a-40d9-8f49-33c9bcb74d98

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome
 - Application: production

**Comment by RohalskyiOleksii** [comment]
> Hi @RohalskyiOleksii! It seems that the issue is quite hard to reproduce. Does it occur in all tests?

repro rate is not 100%, but it happens even with new tests _sometimes_. so it can be considered to lower priority

**Comment by TetianaKhomenko** [comment]
Hi @RohalskyiOleksii ! Fix for this issue will be published in the next release.
