### ISSUE TITLE
TestRun multiselect with Result Messages

### ISSUE THREAD

**Issue by RohalskyiOleksii** [testomatio/app#878]
**Is your feature request related to a problem? Please describe.**
If completing tests with multiselection user can`t add result message in addition to status.

**Describe the solution you'd like**
add possibility to add result message to status while multiselection
![image](https://github.com/testomatio/app/assets/132286699/610448f9-1e28-489a-9b65-c8aa735b2fc8)

**Comment by TetianaKhomenko** [comment]
Hi @RohalskyiOleksii! We plan to implement this request. Here is a UI prototype. Please let us know what do you think?

![telegram-cloud-photo-size-2-5424594951443963531-y](https://github.com/user-attachments/assets/8779cf20-bfcd-425a-9d61-444cce3f17d4)

https://github.com/user-attachments/assets/9e63d89c-894e-422d-a570-46fbf6f9e851

**Comment by TetianaKhomenko** [comment]
Hi @RohalskyiOleksii! Thanks for the feature request. The feature was implemented and will be published in the upcoming release.

![Image](https://github.com/user-attachments/assets/44b39667-4ce7-47e9-bdcf-3a15f1e491ad)

**Comment by TetianaKhomenko** [comment]
@YanaBaranova0909 please re-test this [Custom statuses are missing in bulk apply testomatio/testomatio#5357](https://github.com/testomatio/testomatio/issues/5357) and add to documentation
