### ISSUE TITLE
Test cases are getting mixed up in the list when duplicating the test case

### ISSUE THREAD

**Issue by khristoev13** [testomatio/app#880]
**Description**
Test cases are getting mixed up in the list of tests when the user duplicates one or more test cases.

**Steps To Reproduce**
1. Go to your Project
2. Create several test cases
3. Open any test case
4. Open test case menu (button with 3 dots)
5. Click "Duplicate"
6. Observe the list of test cases

**Actual result**
Test cases are getting mixed up

**Expected behavior**
Test cases shouldn't mixed up

**Screenshots**
<img width="1066" alt="Tests are mixed up" src="https://github.com/testomatio/app/assets/57759749/b7047ce6-4688-4f7f-8987-1a96e0dd1cbf">

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Browser Version 119
 - Application: Production

**Additional context**
Would be better to place the duplicated test case below the original one (currently, it appears above the original test case).

**Comment by khristoev13** [comment]
Hi @poliarush👋🏼
Could you please raise up the priority to `High`? This issue makes me crazy when I'm working with huge lists of test cases. For instance, I can update those tests that shouldn't be updated because of this bug. It just mixed all my cards. That's completely not OK. Thank you!

**Comment by poliarush** [comment]
@khristoev13 please let me know whether you're paid client so we will raise priority quicker (mention your company name)

**Comment by littlefrontender** [comment]
couldn't reproduce, @TetianaKhomenko please help

**Comment by TetianaKhomenko** [comment]
@khristoev13 could you please see attached video and confirm if that is the behaviour you described?

https://github.com/testomatio/app/assets/77803888/9e6d3184-54f8-46ce-9f8a-d06fde66d5fd

**Comment by TetianaKhomenko** [comment]
Hi @khristoev13! The issue has been fixed. The fix will be published in the upcoming release.

**Comment by TetianaKhomenko** [comment]
Hi @khristoev13! The fix is live now. You can check on your side.

**Comment by khristoev13** [comment]
Hi @TetianaKhomenko 👋🏼
Thank you for informing me. The fix is verified.
