### ISSUE TITLE
This field can't be blank on Flaky Update Query pop-up 

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#885]
**To Reproduce**
1. open a project
2. go to Analytics
3. click Flacky widget
4. click Min-Max extra button
5. enter any value within rule Set 0 to include ever-failing tests
6. see _This field can't be blank error_

**Expected behavior**
No _This field can't be blank error_ for right values

**Screenshots**

FLAKY

https://github.com/testomatio/app/assets/77803888/907fb6ec-7c92-49a5-9f99-382f2630e73b

NEVER RUN

https://github.com/testomatio/app/assets/77803888/098e09b2-2518-4d77-bc2a-845c29b35e01

**Comment by TetianaKhomenko** [comment]
@littlefrontender the issue is still there. but ticket can be moved to next release.

![CleanShot 2023-12-13 at 09 12 11@2x](https://github.com/testomatio/app/assets/77803888/49eb545c-3332-4f3e-ab1c-463b513c704e)

**Comment by littlefrontender** [comment]
@DavertMik I think we should update Ember

![Снимок экрана 2023-12-13 в 12 34 30](https://github.com/testomatio/app/assets/79913874/73b4e761-4dce-425f-9b6b-1fd56436445c)

**Comment by poliarush** [comment]
requires new emberjs

**Comment by TetianaKhomenko** [comment]
fixed
