### ISSUE TITLE
Imported test history shows 'Deleted user' as creator

### ISSUE THREAD

**Issue by esmithslcyber** [testomatio/app#886]
**Describe the bug**
When Playwright tests are imported then the creator of the import is shown as 'Deleted user'.  

**To Reproduce**  
1. Click the Tests sidebar item then the button to import from source code.  
2. Run this command in Terminal window on Ubuntu OS:   
`TESTOMATIO=tstmt_Tp05XOwQwnLMabGWISyWgmRssaXc01xCtw1701256513 npx check-tests@latest Playwright "**/*{.,_}{test,spec,cy}.js" `  
3. Check the Testomat import history for one of the imported tests  

**Expected behavior**  
The 'Created by' value shows as the Git user that triggered the import by running the npx check-tests command as mentioned in step 2.  

**Screenshots**  
![image](https://github.com/testomatio/app/assets/152515132/d93937a4-841c-4736-a0ef-0ea24d4df33b)  

**Desktop (please complete the following information):**  
 - OS: Ubuntu

**Comment by TetianaKhomenko** [comment]
Hi @esmithslcyber! The issue was fixed and will be published in the upcoming release.
