### ISSUE TITLE
"Invalid S3 config" message is displayed on project that has no private storage connected

### ISSUE THREAD

**Issue by RohalskyiOleksii** [testomatio/app#889]
**Describe the bug**
incorrect message is displayed
**Severity**: trivial
**To Reproduce**
1. Go to testRUN
2. Click on pass\fail\skip result
3. Add image from clipboard

_note: happens not in every project, random_

**Expected behavior**
no error messages for "Invalid S3 config"  in project without private storage connected

**Screenshots**
![image](https://github.com/testomatio/app/assets/132286699/4c33e596-2da0-44bd-a90a-09b18cb27ec6)

**Desktop :**
 - OS: win10
 - Browser chrome

**Comment by Fro0z1k** [comment]
<img width="1045" alt="Screenshot 2024-01-23 at 11 09 51" src="https://github.com/testomatio/app/assets/7832212/3105e134-ab3f-414a-8fb5-479cf0ef07ad">

**Comment by TetianaKhomenko** [comment]
Hi @RohalskyiOleksii the issue should be fixed now. Could you please check it on your side?

**Comment by TetianaKhomenko** [comment]
Hi @RohalskyiOleksii! Closing this ticket. Please feel free to re-open it if the issue persists.
