### ISSUE TITLE
run command locally is build incorrectly for codecept.js + bdd project

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#89]
In fact only tag is present in grep but should be a scenario name

![image](https://user-images.githubusercontent.com/325722/83050227-8787bd00-a04c-11ea-89ed-eb112a93718c.png)

![image](https://user-images.githubusercontent.com/325722/83050249-92425200-a04c-11ea-9cef-dd916e77e50a.png)

**Comment by koushikmohan1996** [comment]
@poliarush The idea is to grep with test id tag if available, But made a small mistake so it took all the available tags, Fixing this
