### ISSUE TITLE
Edit test case steps/description while in a test run 

### ISSUE THREAD

**Issue by estmikey** [testomatio/app#890]
It is inconvenient to only be able to update tests outside of the test run. As a lead QA, when I see test steps that are incorrect I want to be able to update those steps without stepping out of my current work flow.

**Solution**
- Users can edit a test case while viewing it in a testrun
- The edits, when saved, update the original test case
- Access the edit mode in the menu of the open test case:
![CleanShot 2023-12-01 at 14 22 44@2x](https://github.com/testomatio/app/assets/134728327/b994e7c2-29de-4850-8921-bb7d750e808c)

**Comment by TetianaKhomenko** [comment]
Hi @estmikey! The feature has been implemented and will be published in the upcoming release. Attaching a short demo below.

https://github.com/testomatio/app/assets/77803888/e34716cd-d2fd-43b3-b307-3eace337aea5
