### ISSUE TITLE
Test Data input fields from TMS QASE doesn't transfer to Testomat through export/import

### ISSUE THREAD

**Issue by volodymyrkononenko** [testomatio/app#892]
**Describe the bug**
Test Data input fields from TMS QASE doesn't transfer to Testomat through export/import

**To Reproduce**
1. Open QASE TMS
2. Create test case
3. Fill in the fields _Action, Data, Expected result_
4. Save the test case
5. Click on Export Data
6. Export test case in CSV file format
7. Open Testomat
8. Import the test case (params: QASE, CSV)
9. Check imported test case

**Expected behavior**
"Data" field value transfers alongside with Action, Expected Result

**Screenshots**
![test data example in QASE](https://github.com/testomatio/app/assets/144227578/4b9610c3-18ba-45c7-9271-9f8d356398ec)
![test data field exported from QASE (Testomat file)](https://github.com/testomatio/app/assets/144227578/02dae683-df31-4e0e-b106-4264d6da8f6d)
![Test data missed after impoting to Testomat](https://github.com/testomatio/app/assets/144227578/e053edf6-d7c8-4d9e-94a7-5a3c8ea9ddb0)

**Desktop (please complete the following information):**
- Google Chrome 119.0.6045.200
- Windows 10 Home

**Additional context**

**Comment by TetianaKhomenko** [comment]
related to https://github.com/testomatio/testomatio/issues/3454

**Comment by TetianaKhomenko** [comment]
@trumenov steps_data should be shown as part of steps_actions

![Image](https://github.com/testomatio/app/assets/77803888/8bcccbd9-4bb4-496a-a8a6-19e98cfbcbb6)

![Image](https://github.com/testomatio/app/assets/77803888/1e09ece3-08f8-409c-b610-daa27862fcf0)

![Image](https://github.com/testomatio/app/assets/77803888/9120f1f1-ccc8-4a2a-badc-17210785a155)

**Comment by trumenov** [comment]
Please recheck is all normal for test with
```
* Check video player works: Play/pause functions
Volume controller
Quality settings
Picture-in-picture mode
Timescale works
    * *Expected:* Video player works
```
I am not sure that normal importing this text when in step_data present multilines.

**Comment by TetianaKhomenko** [comment]
@trumenov For now multiline data is imported in one line

![Image](https://github.com/testomatio/app/assets/77803888/19c2758c-b6d4-4932-8146-1c9070b02b76)

![Image](https://github.com/testomatio/app/assets/77803888/6010dcd9-1483-4d19-b2a2-921fc1298fc6)

Please let me know if we can import it as a list.

**Comment by TetianaKhomenko** [comment]
Closing the issue as fixed. @volodymyrkononenko the fix will be published in the upcoming release.
