### ISSUE TITLE
Import to Testomat blocked after QASE changed export params to v2

### ISSUE THREAD

**Issue by volodymyrkononenko** [testomatio/app#893]
**Describe the bug**
QASE changed export params to v2 and it blocks importing test cases to Testomat

**To Reproduce**
1. Open QASE
2. Create suite with test cases
3. Export Suite in CSV
4. Open Testomat
5. Import CSV file from QASE
6. Chech importing report

**Expected behavior**
Suite imported with test cases with all info saved

**Screenshots**
![import QASE](https://github.com/testomatio/app/assets/144227578/ee929d1a-ee5a-4ab9-a6fb-45498a9827a2)
![import QASE example](https://github.com/testomatio/app/assets/144227578/b9af307b-ac77-45e7-b484-48cfc4a3dc83)
![import QASE real data](https://github.com/testomatio/app/assets/144227578/df302127-8b0c-4fa3-bbcb-0aa565aa02c0)

**Desktop (please complete the following information):**
- Google Chrome 119.0.6045.200
- Windows 10 Home

**Additional context**
QASE has updated the export function. in each exported file, the prefix is now "v2.id"
export parameters have also changed 

old version: 2. Login as an existing customer
Open My Account > Starting with us

new version: 2. ""Login as an existing customer\nOpen My Account > Starting with us""

old version: Check the buttons ""Previous"" and ""Save and next"" appears
new version: ""Check the buttons "Previous" and "Save and next" appears""

**Check all related changes**

**Comment by TetianaKhomenko** [comment]
related to https://github.com/testomatio/app/issues/892

**Comment by TetianaKhomenko** [comment]
@volodymyrkononenko the issue was fixed. The fix will be published in the upcoming release.
