### ISSUE TITLE
Trying to load .feature tests into my Cypress.io + Gherkin project raises error

### ISSUE THREAD

**Issue by lucasgdo** [testomatio/app#895]
**Describe the bug**
Trying to load .feature tests into my [Cypress.io](http://cypress.io/) + Gherkin project gives me the message "Tried to load tests from Cucumber framework but the project is already loaded with [Cypress.io](http://cypress.io/) framework"

**To Reproduce**
1. Inside a project go to Settings > Project
2. Set Project Framework to Cypress.io
3. Set Project Language to Gherkin
4. Click "Update"
5. On the project directory execute "TESTOMATIO=API_KEY npx check-cucumber -d cypress/e2e/tests"

**Expected behavior**
Shows how many tests where found and uploads them to Testomat.io

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Browser Version: 120.0.6099.71
 - Application: production

**Additional context**
In my Cypress.io project I use cypress-cucumber-preprocessor, cypress-esbuild-preprocessor and typescript.

**Comment by TetianaKhomenko** [comment]
Hi @lucasgdo! We didn't succeed in reproducing the issue. It might be fixed by the latest changes. Could you please re-check this behavior?

**Comment by lucasgdo** [comment]
Hi, @TetianaKhomenko, today as I was updating my suite with automated tests, I tried reproducing the same scenario that I've described, but this time it worked fine! As you said, it probably was fixed by the latest changes.

**Comment by TetianaKhomenko** [comment]
@lucasgdo Thanks for the feedback. Closing this ticket as fixed. But you can re-open it if the issue reoccurs.
