### ISSUE TITLE
Tests change their position in Test tree occasionally

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#896]
**Describe the bug**

Encountered a problem when the test case moves around the repository on its own when trying to edit the description.

the issue can be related to https://github.com/testomatio/app/issues/880

**To Reproduce**

1. Create a test case.
2. Move it to the required place in the suite.
3. Open description.

**Expected behavior**
Tests don't change their position in the test tree.

**Screenshots**

https://github.com/testomatio/app/assets/77803888/67bda3be-153f-49de-bf16-2e880d95a1de

**Comment by littlefrontender** [comment]
backend issue

**Comment by littlefrontender** [comment]
@DavertMik please help with websocket

**Comment by littlefrontender** [comment]
tests are losing position in BDD, because of 0 position in suite list


![Image](https://github.com/testomatio/app/assets/79913874/25bd3c36-e5f0-442f-abf2-20857a777fb4)

steps to reproduce:
1. create manual tests via Edit feature file
2. check tests positions

**Comment by TetianaKhomenko** [comment]
@littlefrontender the issue is still there :( we need to refresh the page

https://github.com/testomatio/app/assets/77803888/843ea3da-cb00-4f23-bbca-ceb289ff8564

**Comment by TetianaKhomenko** [comment]
fixed
