### ISSUE TITLE
Add feature to generate charts of single automated TC run time in selected period of time  

### ISSUE THREAD

**Issue by ewelinaboruch** [testomatio/app#897]
**Is your feature request related to a problem? Please describe.**
1. I want to be able to check the performance of tests - I have data on how long the test took for each run, but I can't generate a chart for it. So I know there is data I need, but there is no easy way to use it. 

**Describe the solution you'd like**
I can go to the automated TC, click on 'Runs,' and see how much time it took to finish this test. There is a button to generate a chart of time run changes in a selected period of time. 

The best would be to select a customized period of time - to use it depending on needs. In my case, it's about checking the progress of performance - so at least 'from last month till now'

![image (7)](https://github.com/testomatio/app/assets/68733993/5fe16cc3-7c20-402f-a459-68ae3a958724)

**Comment by poliarush** [comment]
related to https://github.com/testomatio/testomatio/issues/3440

**Comment by poliarush** [comment]
@ewelinaboruch what if we just add duration for each run, there is a ticket for this https://github.com/testomatio/testomatio/issues/3440

**Comment by TetianaKhomenko** [comment]
Hi @ewelinaboruch! This view was enhanced with filters and duration.

![Image](https://github.com/user-attachments/assets/fc7bcddd-9093-4b7c-a3b1-53bac89b95d2)
