### ISSUE TITLE
Assignee is missing in Run Archive 

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#898]
**Describe the bug**

![telegram-cloud-photo-size-2-5467438508646977359-y](https://github.com/testomatio/app/assets/77803888/82c83379-ad5a-40aa-94ae-d852e7f02929)

**Expected behavior**

users need to have Assignees on Run Archive as well on Runs page

![telegram-cloud-photo-size-2-5467438508646977360-y](https://github.com/testomatio/app/assets/77803888/e064a4b1-156e-416a-8cc9-78bb5b9283cc)

**Comment by SuMund** [comment]
thank you

**Comment by littlefrontender** [comment]
@DavertMik runs from rungroups is missing

**Comment by TetianaKhomenko** [comment]
hi @SuMund! The issue was fixed. The fix is live now. 

<img width="1370" alt="CleanShot 2023-12-29 at 15 28 26@2x" src="https://github.com/testomatio/app/assets/77803888/f678cc80-e850-4f8b-9c6c-98736e4db0e9">
