### ISSUE TITLE
can't load TestCafe tests

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#90]
![image](https://user-images.githubusercontent.com/325722/83050821-64a9d880-a04d-11ea-96a0-3d36428c7bde.png)

![image](https://user-images.githubusercontent.com/325722/83050846-6b385000-a04d-11ea-8e15-391c36f3cbe0.png)

**Comment by koushikmohan1996** [comment]
@poliarush Merged update examples, It is because the test files did not end with `_test.js` previously
