### ISSUE TITLE
Text editing issue in the description of the test case

### ISSUE THREAD

**Issue by volodymyrkononenko** [testomatio/app#901]
**Describe the bug**
When you open a test case for editing and put the cursor at the end of a word, it puts the cursor in the middle of the word, and the text appears at the end

**To Reproduce**
1. Open the test case
2. Click on Edit
3. Put the mouse somewhere in the text
4. Click the mouse
5. Pay attention that the cursor is not in the place where you clicked

**Expected behavior**
No text editing issues

**Screenshots**

https://github.com/testomatio/app/assets/144227578/b1765473-1a30-4ece-9aa0-ce4997034a39

**Desktop (please complete the following information):**
 - Windows 10 Home
 - Chrome
 - Browser Version 120.0.6099.72
 - Application: production

**Additional context**
The chance of reproducing the bug is 50%
The bug is not a blocker, but it isn't very pleasant

**Comment by TetianaKhomenko** [comment]
related to https://github.com/testomatio/app/issues/877

**Comment by TetianaKhomenko** [comment]
Hi @volodymyrkononenko! Fix for this issue will be published in the next release.

**Comment by volodymyrkononenko** [comment]
@TetianaKhomenko appreciate!

**Comment by TetianaKhomenko** [comment]
Hi @volodymyrkononenko! The issue should be fixed now. Please reopen the ticket if the issue still appears
