### ISSUE TITLE
Recurring setup test mismatch error even when tag added via source code and other workarounds attempted

### ISSUE THREAD

**Issue by esmithslcyber** [testomatio/app#903]
**Describe the bug**
A Playwright 'setup' test keeps getting detected as unmatched even after manually tagging it in the source code.
There appear to be a few related issues actually and these will be detailed. 

**To Reproduce**
1. Add a setup test to test project and manually add a unique tag
![image](https://github.com/testomatio/app/assets/152515132/ee1a46a2-6f99-467a-97d6-7cd709268b19)
2. Execute all playwright tests: 
`TESTOMATIO='APIKEY' npx playwright test --workers=1`
3. Observe that an unmatched test was found
![image](https://github.com/testomatio/app/assets/152515132/986484ce-194e-4f48-99b3-a6d52694c01e)
4. Update the command to be below and execute tests again:
`TESTOMATIO='APIKEY' npx playwright test --workers=1 TESTOMATIO='APIKEY' npx playwright test --workers=1 TESTOMATIO_CREATE=1`
5. Take note of test run results within Testomat UI
![image](https://github.com/testomatio/app/assets/152515132/f5fae71a-6ba4-4b9a-9e93-0ac3c83f64a3)
6. Click the 'Create Unmatched Tests' button

**Expected behavior**
1. After step 4 the unmatched test is automatically added to Testomat test case repository.
2. No messages appear related to unmatched tests in Testomat

**Actual behavior**
1. In step 4 after updating the command to include `TESTOMATIO_CREATE=1` no tests are executed
2. After step 6 the unmatched setup test is created in Testomat although it remains as unmatched on subsequent test runs

**Workarounds attempted**
To try and resolve the issue the Playwright tests were all reimported. The setup test is located in the 'tests' folder in Playwright together with the other tests.
Note that setup files were specified to be included
`TESTOMATIO=APIKEY npx check-tests@latest Playwright "**/*{.,_}{test,spec,cy,setup}.ts" --typescript --update-ids`
At this stage the message states that all the test files were updated in the source code which is not accurate as none of the files were updated.
![image](https://github.com/testomatio/app/assets/152515132/efb75727-5222-4a59-ada6-03f1ae48e04e)

**Comment by olexandr13** [comment]
retest. should work

**Comment by olexandr13** [comment]
rechecked. looks like works. discuss cases with CREATE env var and Create button on ui

**Comment by esmithslcyber** [comment]
Seems to be OK now. Thanks for the quick fix.

**Comment by esmithslcyber** [comment]
Fixed
