### ISSUE TITLE
Run Report notifications are duplicated

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#906]
**Describe the bug**

All run report messages are sent twice. Related to slack, mail, jira.

**To Reproduce**

<img width="1305" alt="CleanShot 2024-01-03 at 15 44 24@2x" src="https://github.com/testomatio/app/assets/77803888/c3a212fc-fad0-4661-9fce-cd9cff1535c4">

![CleanShot 2024-01-03 at 15 44 58@2x](https://github.com/testomatio/app/assets/77803888/72e0e601-b64a-46d1-95d2-ea6f1920ad9c)

**Screenshots**

![CleanShot 2024-01-03 at 15 35 24@2x](https://github.com/testomatio/app/assets/77803888/df521ebd-20df-43a9-8cdf-d6f7a66d295b)

![CleanShot 2024-01-03 at 15 36 40@2x](https://github.com/testomatio/app/assets/77803888/36185e86-f53e-4130-82aa-0c1af82853e6)

![CleanShot 2024-01-03 at 15 42 45@2x](https://github.com/testomatio/app/assets/77803888/b90eae55-ad06-479a-a386-8b79b636913d)

**Comment by tikolakin** [comment]
not sure, but isn't it the same issue as here https://github.com/testomatio/app/issues/858 ?

**Comment by TetianaKhomenko** [comment]
verified as fixed
