### ISSUE TITLE
code template is not fully shown on preview

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#91]
![image](https://user-images.githubusercontent.com/325722/83051227-fc0f2b80-a04d-11ea-8016-46453b4c5359.png)

![image](https://user-images.githubusercontent.com/325722/83051319-27921600-a04e-11ea-89b3-f31929347baa.png)

**Comment by DavertMik** [comment]
this is not a but, preview is a pre-view, so we don't have to show the full text there
