### ISSUE TITLE
Integrate WDIO v8 with Testomat

### ISSUE THREAD

**Issue by dnlstpnv** [testomatio/app#910]
I'm proposing integration of WebDriverIO v8 into Testomat.

For version compatibility details, please refer to [WebDriverIO Versions](https://webdriver.io/versions).

FYI: WebDriverIO v7 is currently in Long-Term Support (LTS), and versions preceding v7 are deprecated.

**Comment by poliarush** [comment]
https://testomatio.slack.com/archives/C067WEKC06L/p1705365675670879
> Працює, артефакт є в репорті в мене немає нарікань, але все ж таки виглядає як костиль для мене. Тегніть плс як буде релізнуто нову версію addArtifact, я з радістю її протестую і скажу фідбек.
> Тим не менш, вигладає так що хотілось би ‘нативне’ від wdio. Вони вже готують 9 версію, зараз актуальна 8. Чи є сенс зробити ішю в гітхаб для інтеграції 8 версії в тестомат? Дякую. (edited)

**Comment by olexandr13** [comment]
https://github.com/testomatio/examples/pull/62

**Comment by poliarush** [comment]
linkedin to https://github.com/testomatio/examples/issues/60

**Comment by poliarush** [comment]
linked to https://github.com/testomatio/testomatio/issues/530

**Comment by olexandr13** [comment]
[1.4.1-beta-wdio-bdd](https://www.npmjs.com/package/@testomatio/reporter/v/1.4.1-beta-wdio-bdd)
