### ISSUE TITLE
Not all test cases available in the suite are listed when returning to the suite from test-case page

### ISSUE THREAD

**Issue by anya-anatska** [testomatio/app#912]
**Describe the bug**
Test suite does not list all test cases if there are more then 20 tests cases; only first 20 are listed

**To Reproduce**
1. Go to suite that has more than 20 test cases
2. Click on any test case to edit it
3. Come back to the suite by clicking on the suite from here
<img width="1283" alt="Screenshot 2024-01-17 at 15 38 41" src="https://github.com/testomatio/app/assets/99194430/f8b3cec5-7442-4554-8b22-ee3d897d629c">

4. Check test cases

**Expected behavior**
All test cases existed in the suite are listed

**Screenshots**
If applicable, add screenshots or video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Browser Version: Version 120.0.6099.216 (Official Build) (arm64)
 - Application: [production or beta] 

**Additional context**
For suites that are less then 20 test cases, all tests are listed

**Comment by TetianaKhomenko** [comment]
Hi @anya-anatska! The issue should be fixed in the upcoming release.

**Comment by anya-anatska** [comment]
thank you very much!

**Comment by poliarush** [comment]
@anya-anatska next release is planned for today-tomorrow

**Comment by anya-anatska** [comment]
so fast! coo! thank you a lot!

**Comment by TetianaKhomenko** [comment]
Hi @anya-anatska! The new Testomat version is live. The issue should be fixed. Please re-open this ticket if the issue re-occurres
