### ISSUE TITLE
Fail to load playwright trace from private bucket

### ISSUE THREAD

**Issue by tikolakin** [testomatio/app#914]
**Describe the bug**
Testomatio fails to show playwright traces that are accessible on AWS/Gcloud bucket with private URL

**To Reproduce**
1. Have S3/Gcloud artifacts configured in private mode
<img width="682" alt="image" src="https://github.com/testomatio/app/assets/5860505/018152f8-b517-42f4-b263-8ce14147aedd">
2. Run playwright tests that uploads artefacts to cloud storage
3. Open test report to locate test artifacts
4. Click on *.zip trace file

**Expected behavior**
Trace is displayed on testomatio page

**Screenshots**
Error
<img width="1070" alt="image" src="https://github.com/testomatio/app/assets/5860505/5d4aa0b0-4b57-4ae4-8bbb-0df70d1259eb">

**Additional context**
URL is alright, if you visit the same URL in a new browser tab - you will get file downloaded fine.

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin! are third-party cookies allowed in your browser? 

<img width="422" alt="CleanShot 2024-01-18 at 14 28 26@2x" src="https://github.com/testomatio/app/assets/77803888/412df5b1-1dc2-4198-98dd-25cb0e9feddd">

**Comment by tikolakin** [comment]
I don't have a request to allow third party cookies on the testomato page.
Yet, when enabling it manually doesn't solve the issue
<img width="1161" alt="image" src="https://github.com/testomatio/app/assets/5860505/ba20db33-8063-49a1-ace8-e7d5684780c0">

**Comment by DavertMik** [comment]
@tikolakin to my experience this happens when `trace.playwright.dev` website can't fetch the file

please check the CORS permissions on your bucket to allow `trace.playwright.dev` to access it

not sure how to do that in Google Cloud

**Comment by tikolakin** [comment]
Thanks @DavertMik , it works.
It might be a good idea to update documentation as well - https://docs.testomat.io/reference/reporter/artifacts.html#troubleshooting
here is a reference to configure gcloud bucket
https://cloud.google.com/storage/docs/using-cors#command-line
TY!

**Comment by poliarush** [comment]
@TetianaKhomenko please add task to docs repo.
