### ISSUE TITLE
Improve Autocomplete settings savings

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#918]
**Describe the bug**
Autocomplete settings are not consistent for the moment. 
Users often need to update Autocomplete preferences.

Also, it seems that Autocomplete settings don't save per user.

**Expected behavior**
Autocomplete preferences saved since they are set up by a user and there is no need to update them.

**Screenshots**
![image](https://github.com/testomatio/app/assets/77803888/f2b3a139-3b9b-424e-bd29-fb86a1587748)

**Comment by littlefrontender** [comment]
backend issue
