### ISSUE TITLE
Archived Runs and Groups are shown on Runs page

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#923]
**Describe the bug**

https://github.com/testomatio/app/assets/77803888/c5910d89-891a-42fd-a879-402f843435a8

**To Reproduce**
1. open a project
2. go to Runs
3. pick a Run/ Group
4. click Extra menu (or use multiselect)
5. archive Run/ Group
6. see archived Run/ Group is still shown on Runs page

**Expected behavior**

1. archived Run/ Group is hidden from Runs page
2. archived Run/ Group is placed in the Archive

**Comment by littlefrontender** [comment]
@trumenov  isArchvied is misssing https://github.com/testomatio/testomatio/issues/3756

**Comment by TetianaKhomenko** [comment]
fixed
