### ISSUE TITLE
Archived Runs don't have grayed out icon

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#925]
**Describe the bug**
Users need visual identification of which Runs/ Groups were archived 

**To Reproduce**

1. open a project
2. go to Runs
3. pick a Run/ Group
4. click Extra menu (or use multiselect)
5. archive Run/ Group
6. open Run/ Group archive
7. see manually archived Run/ Group has not grayed icon

**Expected behavior**

<img width="1305" alt="CleanShot 2024-02-01 at 12 44 55@2x" src="https://github.com/testomatio/app/assets/77803888/2830b326-4ab3-4db4-b6d8-7283c3772bae">

**Comment by TetianaKhomenko** [comment]
@littlefrontender can we show greyed status icon only for runs that were archived manually?

**Comment by littlefrontender** [comment]
@TetianaKhomenko sure, but i need backend improvement

**Comment by TetianaKhomenko** [comment]
@trumenov please help

**Comment by TetianaKhomenko** [comment]
fixed
