### ISSUE TITLE
API "noempty" option is ignored on testomatio backend

### ISSUE THREAD

**Issue by tikolakin** [testomatio/app#928]
**Describe the bug**
https://github.com/testomatio/check-tests/issues/135

**To Reproduce**
see  referenced issue 

**Expected behavior**
see  referenced issue 

**Screenshots**
see  referenced issue 

**Additional context**
This issue has been open for a while - would be good to have some eyes on it
Thanks

**Comment by TetianaKhomenko** [comment]
https://github.com/testomatio/check-tests/issues/135#issuecomment-2059112618

**Comment by tikolakin** [comment]
It doesn't work, https://github.com/testomatio/check-tests/issues/135#issuecomment-2100768495

**Comment by tikolakin** [comment]
cc @poliarush

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin! The issue should be fixed now. Can we ask you to check it on new imports?

**Comment by TetianaKhomenko** [comment]
Closing the ticket as done. Please reopen if the issue reproduces.
