### ISSUE TITLE
Cert doesn't match the URL 

### ISSUE THREAD

**Issue by bheemvennapureddy** [testomatio/app#929]
Email reporter links are broken 

![image](https://github.com/testomatio/app/assets/144472943/7379925a-1ada-405b-aac4-9ef0781a15c8)

**Comment by poliarush** [comment]
https://testomatio.slack.com/archives/C03DY1CG353/p1706801850993199

```
Don't really want to leave it this way but it's the only option I have (I bypassed url6194.testomat.io from SSL decryption). Really testomat needs to fix this issue as the cert name doesn't match the URL
```

**Comment by DavertMik** [comment]
Can we rediect this issue to support of our email send service?

**Comment by DavertMik** [comment]
In all reporting mails all links should have "clicktracking="off" attribute

More info:
https://app.testomat.io/projects/notes/test/7e4196fa

**Comment by TetianaKhomenko** [comment]
the issue should be fixed in the upcoming release

**Comment by TetianaKhomenko** [comment]
Hi @bheemvennapureddy! The fix is live now, could you please check on your side?

**Comment by TetianaKhomenko** [comment]
Hi @bheemvennapureddy! We are closing this ticket. But please reopen the ticket if the issue still occurs.
