### ISSUE TITLE
Error when import tests from Spreadsheet 

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#932]
**Describe the bug**
Error 'Type error no implicit conversion of nil into String' when impoting manual tests.

**To Reproduce**
1. create a project
2. go to Imports
3. import tests from Spreadsheet 
4. see error 'Type error no implicit conversion of nil into String' 

**Expected behavior**
No errors. All tests are imported.

**Screenshots**

![telegram-cloud-photo-size-2-5348503837654243404-y](https://github.com/testomatio/app/assets/77803888/0d4a8f8f-96d8-42bc-ba47-13f5917571b7)

**Comment by DavertMik** [comment]
Fixed

**Comment by TetianaKhomenko** [comment]
The issue was checked and verified as fixed
