### ISSUE TITLE
Testomatio Playwright reporter | Full page screenshots cause exception errors and prevent completion of test runs

### ISSUE THREAD

**Issue by mascarion** [testomatio/app#934]
**Describe the bug**
Testomatio Playwright reporter exception errors occur during test execution as a result of taking full page screenshots in some tests. This prevents the completion of test runs and also prevents results reports from being generated.

**To Reproduce**
1. Add the following code to a Playwright test case:  
```await testInfo.attach('resultsPage', { body: await page.screenshot({ path: 'card_validation.png', fullPage: true }), contentType: 'image/png' })```
2. Execute the test case using testomat as the reporter (default html reporter also used for artifact generation)

**Expected behavior**
Test execution completes successfully and test reports generated containing all artifacts including full page screenshots. 

**Actual behaviour**
![image](https://github.com/testomatio/app/assets/152515132/0a2a233d-3523-4867-8d4c-5b6873632722)

![image](https://github.com/testomatio/app/assets/152515132/c22e1158-f98c-4f19-a8a2-f1ca0b4d63d1)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - Browser: N/A
 - Testomat reporter: "@testomatio/reporter": "^1.0.17"

**Additional context**
Issue found during Gitlab pipeline run.

**Comment by olexandr13** [comment]
@mascarion please retest on the latest reporter version
