### ISSUE TITLE
Test run report link created without password protection still requires a password after opening

### ISSUE THREAD

**Issue by Tny6918** [testomatio/app#937]
**Test run report link created without password protection still requires a password after opening**

**To Reproduce**
1. Go to Runs
2. Click on a completed test run
3. Push the button Report 
4. Push the button Share report publicly and unselect the checkbox "Protect by passcode"
5. Push the button Share and copy the link

The user is asked for a password if the report  is opened in incognito mode or another browser

**Expected behavior**
any user with a link can see the report
**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Browser Version [e.g. 22]
 - Application: [production ]

**Comment by Tny6918** [comment]
sorry, but what is the current status of this fix? 
this is a crucial functionality part for our company since we need to present our test reports on each test run

**Comment by poliarush** [comment]
@Tny6918 it's already in development stage and will be published within next release

**Comment by TetianaKhomenko** [comment]
Hi @Tny6918! The issue was fixed. The fix will be published in the upcoming release.

**Comment by TetianaKhomenko** [comment]
Hi @Tny6918! The fix is live now. Could you please check on your side?
