### ISSUE TITLE
The test run report opened by the link has a constant loader for the diagram

### ISSUE THREAD

**Issue by Tny6918** [testomatio/app#938]
**The test run report opened by the link has a constant loader for the diagram**

**To Reproduce**
1. you have a link with the test report run and you open it

you have run time in seconds 
you have a constant loader
you have no summary for the test cases

**Expected behavior**
run time in hours/min/sec 
you have an uploaded diagram
you have a summary of the test cases 

**Screenshots**
![Screenshot_137](https://github.com/testomatio/app/assets/43401901/7d4f9695-b179-4a4a-935d-2baeec7d01b3)

**Desktop**
 - OS: [Windows]
 - Browser [Chrome]
 - Browser Version [121.0.6167.161]
 - Application: [production]

**Comment by littlefrontender** [comment]
@DavertMik fixed

**Comment by TetianaKhomenko** [comment]
Hi @Tny6918! The constant loading diagram was fixed. Please check it on your side.

**Comment by TetianaKhomenko** [comment]
Moving this ticket to the next milestone for further improvements:

- [ ] run time in hours/min/sec
- [ ] you have a summary of the test cases

**Comment by Tny6918** [comment]
![Screenshot_275](https://github.com/testomatio/app/assets/43401901/cd1018e8-e353-4cc1-950c-855951c3fc50)
Can we have hours/min/sec ?

**Comment by TetianaKhomenko** [comment]
Hi @Tny6918! The fix is live now

![Image](https://github.com/testomatio/app/assets/77803888/67ef7b2b-2853-4021-ab01-a710865737dd)
