### ISSUE TITLE
Show the test case author icon on the test tab and test suit author on the test suit tab

### ISSUE THREAD

**Issue by Tny6918** [testomatio/app#939]
**Show the test case author icon on the test tab**
when you open the test case  tab (screen) where you can see the test case description you can only see the author of the test case in the sub-tab History

**Show the author icon next to the assignee icon with a tooltip "created by `user-name`"*

**Describe alternatives you've considered**
show the whole sign - "created by `user-name`" and last "edit by `user-name`"

**Comment by TetianaKhomenko** [comment]
Hi @Tny6918! could you please attach a screenshot or any other visual reference of how you expect to see?

**Comment by TetianaKhomenko** [comment]
attaching a reference

![Image](https://github.com/testomatio/app/assets/77803888/c2206b5c-d91c-44a6-af2e-8ec2a0bd8714)

**Comment by Tny6918** [comment]
idea: to get the info about author and assignee with less steps

current implementation:
- user assigned is visible in the Title line of the test-case

request:
- add the author icon with the same tooltip but the text "Author: created at <date>"
![Screenshot_189](https://github.com/testomatio/app/assets/43401901/21b907d1-faa3-44ee-a97e-774bb448813a)

**Comment by poliarush** [comment]
![image](https://github.com/testomatio/app/assets/325722/2c5909bc-b1ad-403b-9bde-bb66bcb2d634)

**Comment by poliarush** [comment]
under title interface already overloaded

![2024-03-14_14 32 35@2x](https://github.com/testomatio/app/assets/325722/fe4c9906-6556-4a75-85d7-536d5c1a1bae)

**Comment by TetianaKhomenko** [comment]
The feature was implemented and will be published in the upcoming release.
Attaching screenshot. 

![Image](https://github.com/testomatio/app/assets/77803888/f9fc8b1e-140e-48bd-89d6-678d6d030337)
