### ISSUE TITLE
The system shows only label name in the searching results instead of the actual value of the label

### ISSUE THREAD

**Issue by hanna-kuzub-CG** [testomatio/app#941]
**Describe the bug**
The system shows only label name in the test tree if the user applied some searching params (e.g. by tag, by linked jira ticket and so on).

**Precondition:**
* There are a few test cases where custom labels are applied
* Labels visibility is enabled in the settings (show in list = true, show in filter = true)
* Test cases are linked to jira and contains some tags

**To Reproduce**
1. Go to 'Tests' list page
2. Pay attention to the label values visibility in the test cases list
3. Apply some filters/searching params
4. Pay attention to the label values visibility in the searching results

**Actual result:**
* Label values are not displayed, the system shows only label names instead.

**Expected behavior**
* The system shows label & values according to the settings applied both **on Tests list page itself** and **on Tests list page with searching applied**.

**Screenshots**
https://github.com/testomatio/app/assets/148227507/37a9cd5b-2788-4330-ab4d-c94f455d09fa

**Desktop (please complete the following information):**
 - macOS Sonoma 14.1
 - Browser - Chrome 120.0.6099.234

**Additional context**
The problem appears only when search/filter is applied

**Comment by littlefrontender** [comment]
@TetianaKhomenko @DavertMik missing "value" param



![Image](https://github.com/testomatio/app/assets/79913874/912f3e3c-95cd-46b8-8293-9cdc1ebb0c44)

**Comment by TetianaKhomenko** [comment]
Hi @hanna-kuzub-CG! The issue was fixed. The fix will be published in the upcoming release. Attaching a short demo below

https://github.com/testomatio/app/assets/77803888/e5dabce3-6fbe-47ff-8289-733a6d2e5e4e
