### ISSUE TITLE
allow only image to be uploaded and limit image size 

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#95]
currently event pdf file can be added with big size.
![image](https://user-images.githubusercontent.com/325722/83054240-64600c00-a052-11ea-9ee2-410dc7ae2c06.png)

**Comment by koushikmohan1996** [comment]
@poliarush What should be the size limit? 2 MB

**Comment by poliarush** [comment]
i think 5 mb maximum

**Comment by koushikmohan1996** [comment]
@poliarush used 5mb!
