### ISSUE TITLE
Test runs using "@testomatio/reporter" are very slow when running API tests in GitLab

### ISSUE THREAD

**Issue by qakos** [testomatio/app#950]
**Describe the bug**
In GitLab, test runs using "@testomatio/reporter" are slow when running API tests, including some parameterized tests. With a total of over 3,000 tests, the run takes 2.6 minutes to complete. However, the GitLab job still waits for "@testomatio/reporter" for an additional 20 minutes, causing a significant delay.

**To Reproduce**
1. Run tests with @testomatio/reporter

**Expected behavior**
Test runs using "@testomatio/reporter" should not be causing a significant delay, such as 20 minutes.

**Screenshots**
If applicable, add screenshots or video to help explain your problem.
![28-02-24__01](https://github.com/testomatio/app/assets/93794669/15a1eceb-e778-4e77-8d80-87c8bb6a929c)

**Desktop (please complete the following information):**
 - Browser Version [e.g. 22]
 - Application: [production or beta] 

**Additional context**
Playwright: 1.42.0
@testomatio/reporter: 1.2.1

**Comment by DavertMik** [comment]
@qakos we think it was temporary issue with out job server
if issue persist please reopen it

**Comment by DavertMik** [comment]
Should have been fixed with bulk reporting in reporter 1.4.0

**Comment by TetianaKhomenko** [comment]
@qakos can we ask you to check this on your CI with the latest reporter version?

**Comment by TetianaKhomenko** [comment]
@qakos please re-open the ticket if the issue still persist
