### ISSUE TITLE
Error when exporting tests

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#951]
**Describe the bug**

https://appsignal.com/testomatio/sites/611d2c787478202391730cb0/exceptions/incidents/3395

**To Reproduce**
1. open a project
2. click the extra menu
3. click Export as spreadsheet
4. see the error: "undefined method `current' for Branch:Class\nDid you mean?  current_role"

**Expected behavior**
No errors, tests are exported as xlsx

**Screenshots**
<img width="1355" alt="Screenshot 2024-02-28 at 16 28 45" src="https://github.com/testomatio/app/assets/77803888/8bc82807-e2b2-45aa-9f4e-a14efb802b90">

**Comment by DavertMik** [comment]
Fixed on production

**Comment by TetianaKhomenko** [comment]
tested and confirmed as fixed
