### ISSUE TITLE
Cannot open any Test run via archives

### ISSUE THREAD

**Issue by bt-jagababu** [testomatio/app#953]
**Describe the bug**
As a part of triaging, we filter the latest result by date. As Date Filter is only supported in Archive runs, post-filtering 
I cannot open any test run via archive due to the below issue.

![image](https://github.com/testomatio/app/assets/150358630/5bda693d-2d6d-4676-88ff-acc784d8a5f8)

**To Reproduce**
1. Go to runs
2. Click on Archive
3. Select a run
4. Click on a test you will see only blank screen.

**Expected behavior**
Need to see the test result

**Screenshots**
Added above

**Desktop (please complete the following information):**
 - Browser Version [e.g. 22]
 - Application: [production or beta] 

**Additional context**

**Comment by TetianaKhomenko** [comment]
fixed

**Comment by bt-jagababu** [comment]
@TetianaKhomenko  Do you know when this will be deployed to prod?

**Comment by poliarush** [comment]
@bt-jagababu we're planning to make release next week, approximately in Wednesday

**Comment by TetianaKhomenko** [comment]
Hi @bt-jagababu! The fix is live now. Please check it on your side.
