### ISSUE TITLE
Page refresh returns the user to the project default home page

### ISSUE THREAD

**Issue by anya-anatska** [testomatio/app#960]
**Describe the bug**
When on the suite page or on the filtered data mode, after clicking page refresh button (or pressing cmd/cntr+R) the page is reset to the project home page, all filters applied are reset

**To Reproduce**
1. Go to any suite or filter data
2. Click on browser refresh button or press cmd/cntr+R

**Expected behavior**
Opened suite/filters should remain, after refresh the data should be updated

**Desktop (please complete the following information):**

- OS: [macOS]
- Browser [chrome]
- Browser Version [Version 122.0.6261.94 (Official Build) (arm64)]
- Application: [production]

**Additional context**
NA

**Comment by TetianaKhomenko** [comment]
Hi @anya-anatska! Thanks for reporting the issue. The issue was fixed. The fix will be published in the upcoming release.

**Comment by TetianaKhomenko** [comment]
Hi @anya-anatska! The fix is live now.
