### ISSUE TITLE
Changing filters to show less data, does not set the user on the 1 page

### ISSUE THREAD

**Issue by anya-anatska** [testomatio/app#961]
**Describe the bug**
When re-filtering data that results in less pages, the user stays on the page he/she scrolled to with the original filter; if new filter provides less pages, the user gets an empty page

**To Reproduce**
1. Apply a broad filter
2. Scroll till the end 
3. Apply a more specific filer

**Expected behavior**
A user is set to the firs page

**Screenshots**
<img width="1603" alt="Screenshot 2024-03-07 at 19 06 25" src="https://github.com/testomatio/app/assets/99194430/21e2768c-a347-4466-8216-ea83c1b134d9">

**Desktop (please complete the following information):**

- OS: [macOS]
- Browser [chrome]
- Browser Version [Version 122.0.6261.94 (Official Build) (arm64)]
- Application: [production]

**Additional context**
NA

**Comment by TetianaKhomenko** [comment]
Hi @anya-anatska! The issue was fixed and the fix will be published in the upcoming release.

**Comment by anya-anatska** [comment]
thank you!
