### ISSUE TITLE
Run group counters don't update without assigned strategy

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#963]
**Describe the bug**

**To Reproduce**
1. open a project
2. go to Runs
3. create a Run Group with manual runs
4. don't set the strategy
5. finish runs
6. see Group test counters don't update
7. open the  group
8. edit > Apply any strategy
9. see counters updated

**Expected behavior**

I suggest applying a realistic strategy by default when creating a group. @poliarush what do you think about this?

**Screenshots**

https://github.com/testomatio/app/assets/77803888/2d500230-55c8-473d-97f1-b60f9ba2224d

**Comment by poliarush** [comment]
realistic strategy by default is fine.

**Comment by Fro0z1k** [comment]
<img width="1650" alt="Screenshot 2024-03-23 at 15 30 48" src="https://github.com/testomatio/app/assets/7832212/366fd497-c2f7-42ee-9a99-8074c37ff067">

So, as we can see from the screenshot, the backend returns the saved data for the RunGroup
FYI: by default realistic strategy without choosing strategy.

highlighted in orange
Also, need to check why we have 2 requests to RunGroups API

task redirected to @littlefrontender

**Comment by TetianaKhomenko** [comment]
https://github.com/testomatio/testomatio/pull/3951

**Comment by TetianaKhomenko** [comment]
fixed
