### ISSUE TITLE
Mixed run launched to broken CI can't be executed manually

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#964]
**Describe the bug**
Users get the Run Finished screen when the mixed run is launched in a broken CI profile (wrong credentials, or any other error).

**To Reproduce**

1. Have several CI profiles
2. Launch Mixed run 
3. Select mixed test plan
4. Choose a CI profile with broken credentials
5. Click "Launch"
6. Observe Mixed test run create form still open
7. Observe Error message
8. Observe Test run is created
9. **Choose a valid CI profile**
10. Click "Launch"
11. Observe test run is updated
12. Observer test run completion success screen

**Expected behavior**

1. The mixed run is accessible for execution after changing broken CI profile to working one.
2. Automated tests are launched on the updated CI profile.

**Screenshots**

https://github.com/testomatio/app/assets/77803888/bad1205b-0d13-488a-bd78-0204ae9ef0b8

https://github.com/testomatio/app/assets/77803888/3979e9af-e8c2-4262-b393-d3bd9af1a1e8

**Comment by TetianaKhomenko** [comment]
Need to improve behavior for the case when a mixed run was launched with non-working CI connection. I suggest adding automated tests to the manual part so users can execute them manually.

**Comment by DavertMik** [comment]
![Image](https://github.com/testomatio/app/assets/220264/57f4dde6-92d9-4e0f-b4de-38f1e16aa386)



![Image](https://github.com/testomatio/app/assets/220264/52fa9bcd-06c1-4d38-859a-9b2645f5611d)

**Comment by TetianaKhomenko** [comment]
@DavertMik need to apply changes to cases with this error as well 
`Can't launch automated tests for this run. Failed to open TCP connection to beta-ci-jenkins.testomat.:443 (getaddrinfo: Name or service not known)` 

https://github.com/testomatio/app/assets/77803888/6006ae06-5e15-45f9-8a4e-d3d994cb2987

**Comment by TetianaKhomenko** [comment]
closing as fixed
