### ISSUE TITLE
Adding a new user to the project requires 2 invites

### ISSUE THREAD

**Issue by dmrock** [testomatio/app#966]
**Describe the bug**
The project invite works only on the second attempt

**To Reproduce**
1. Send an invite via email
2. The user accepts it
3. The user registers in the system, and the project is not displayed for them
4. Send the invite again to the same email
5. The user sees the project

**Expected behavior**
The user sees the project after the first attempt.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Browser Version: 122.0.6261.94 (Official Build) (arm64)
 - Application: production

**Additional context**
The trial period, without company.

**Comment by TetianaKhomenko** [comment]
Hi @dmrock! The issue seems to be CNR. Closing ticket for now. Please reopen the ticket if the issue reoccurs or if any other details appear.

https://github.com/testomatio/app/assets/77803888/64304cdd-700f-40cb-beb8-6d7210c6ee34
