### ISSUE TITLE
Show full path to Test-Cases when filter is applied on Tests View

### ISSUE THREAD

**Issue by AlexLAA** [testomatio/app#969]
Without filter
![image](https://github.com/testomatio/app/assets/12410819/8896aaf0-aabb-4700-aff2-c2cda2e8d7a0)

With filter by (**Automated** status)
![image](https://github.com/testomatio/app/assets/12410819/87237411-26f3-4f0d-a1b4-aae0175102a3)

**Comment by AlexLAA** [comment]
@DavertMik

**Comment by poliarush** [comment]
@AlexLAA there is no way to show full nested structure for search result, you can go inside of test case to see full path

![2024-03-19_19 43 36@2x](https://github.com/testomatio/app/assets/325722/bf4423c2-0d48-450c-875a-4445a83231f1)

**Comment by poliarush** [comment]
@AlexLAA how do you want it to be implemented?

**Comment by AlexLAA** [comment]
I want filter to be applied, but view will be same with folders & suites

**Comment by AlexLAA** [comment]
I want to filter all cases by "Manual" Status and check what cases in how many cases in folders\suites I have. And choose with what category I will start work.

Or I want to filter all cases with **To Review** Label and start Review by Folders (Suites)

**Comment by AlexLAA** [comment]
@poliarush Now it works more like search for specific Test Cases, not for filtering data in suites

**Comment by AlexLAA** [comment]
**Filtering** takes an existing full list, and removes items based on criteria that match/don't match.
**Search** takes a blank slate and adds to it based on criteria that match/don't match.

**Comment by AlexLAA** [comment]
Examples from **Test Run Page**
You can switch View format (Tree view / Flat view) - Looks Great!

![image](https://github.com/testomatio/app/assets/12410819/35cb5f39-b39b-4b4f-8eec-99c16d153530)
![image](https://github.com/testomatio/app/assets/12410819/5b874b15-08d8-452e-9be5-c48180b9ff00)

**Comment by littlefrontender** [comment]
@AlexLAA  is this what you expect?

https://github.com/testomatio/app/assets/79913874/d4504278-95c5-474f-a5df-ab74a94cd070

**Comment by TetianaKhomenko** [comment]
@AlexLAA The feature was implemented and will be published in the upcoming release.
