### ISSUE TITLE
Scenario Outline stoped creating tables with Examples

### ISSUE THREAD

**Issue by Tny6918** [testomatio/app#973]
**Scenario Outline stoped creating tables with Examples**

**To Reproduce**
1. Go to Tests
2. Create a new Test case
3. Add a Scenario Outline and add examples
4. push the Save button

**Expected behavior**
I see a table of examples and during the test run I have several cases for each line of the table
**Screenshots**
![Screenshot_205](https://github.com/testomatio/app/assets/43401901/f0908b3b-9351-4650-8578-5bfbed3ca307)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Browser Version [122.0.6261.131]
 - Application: [production] 

**Additional context**
THIS IS A BLOCKER RIGHT NOW! WE NEED THE FIX ASAP

**Comment by TetianaKhomenko** [comment]
Hi @Tny6918! Sorry for such inconvenience. This fix will be published this week.

**Comment by TetianaKhomenko** [comment]
Hi @Tny6918! The fix is live now.
