### ISSUE TITLE
Analytics: Filters are not being applied in the enviroment statistics

### ISSUE THREAD

**Issue by bt-jagababu** [testomatio/app#974]
**Describe the bug**
Filters are not being applied in the enviroment statistics

**To Reproduce**
1. Go to 'https://app.testomat.io/projects/<project>/analytics/runenvs' Analytics > Environment Statistics
2. Filter by date
3. You will see the filters are not applied

![image](https://github.com/testomatio/app/assets/150358630/7712839e-c792-42aa-9704-5367893b8532)

**Comment by TetianaKhomenko** [comment]
Hi @bt-jagababu! Thanks for reporting the issue. The fix will be published in the upcoming release.
