### ISSUE TITLE
Unable to unselect test cases selected by a filter

### ISSUE THREAD

**Issue by charumitraravi** [testomatio/app#975]
**Describe the bug**
More often, I find the need to exclude some of the cases selected by a filter. 
eg: 
In a test plan, I want to include the high priority cases from all but one suite. I would ideally want to use the priority filter to select all the High priority cases, and then unselect the tests I do not want to include. 
Now,  with the current implementation, I have to select 90 cases one by one  out of the 100 high priority cases, instead of auto selecting 100 cases and excluding 10 cases, which is quite frustrating.

**Comment by TetianaKhomenko** [comment]
related to https://github.com/testomatio/moonactive-issues/issues/149

**Comment by TetianaKhomenko** [comment]
+ 1 client requesting this fix

**Comment by TetianaKhomenko** [comment]
Hi @charumitraravi! The feature is live now https://changelog.testomat.io/release-pinned-runs-and-groups-enhanced-test-plans-and-improved-parameters/
