### ISSUE TITLE
Charts for test runs

### ISSUE THREAD

**Issue by tikolakin** [testomatio/app#978]
**Is your feature request related to a problem? Please describe.**
In order to get an extended reporting on the test execution I want to be able to use charts to create custom metrics on the test runs
So that I have a better visibility how testing is performed

**Describe the solution you'd like**
Allow query on test runs
<img width="1421" alt="image" src="https://github.com/testomatio/app/assets/5860505/199660b0-9f75-46bd-9216-d254a96d6542">

**Describe alternatives you've considered**
Currently, it's only possible to use filtering on a test run page that is not exactly giving you the desired number

**Additional context**
Use case. I have test runs with multiple labels. I want to be able to create a chart that will give a number of how many test runs I have given a specific label. The label could be "os:windows" which will show how many test runs are executed on Windows.
Moreover, it would be nice to have the rest of the query params to work for the test run as well, ex. test run title, created, updated etc.

**Comment by tikolakin** [comment]
The other use case is to create a chart for the test run duration

**Comment by tikolakin** [comment]
@poliarush should we reiterate on it? Test Run data are important metrics that we would like to see on testomatio.
Such as test run completion time etc.

**Comment by poliarush** [comment]
that's planned for the release after next for 0.5.37

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin! The feature was implemented. It will be published this week ;)

![Image](https://github.com/user-attachments/assets/5553f108-d7e5-4ef3-bbca-0ce8b866ce9a)

**Comment by TetianaKhomenko** [comment]
@nataliadevvv please update this page https://docs.testomat.io/project/analytics/#custom-charts
