### ISSUE TITLE
"Save" Shortcut on editing Test Case Title

### ISSUE THREAD

**Issue by AlexLAA** [testomatio/app#979]
Save (Shift+Cmd+S) shortcut doesn't work when your focus on **Title** Field of Test-Case. It only works with Description.
We want it to work with Title same way as Description.
![image (40)](https://github.com/testomatio/app/assets/12410819/4658b017-276f-43aa-a778-99b0dacc58e5)
![image (41)](https://github.com/testomatio/app/assets/12410819/a4f83251-bc58-434a-ab5c-070a0dbfcd93)

**Comment by TetianaKhomenko** [comment]
Hi @AlexLAA! The feature was implemented and will be published in the upcoming release. Thanks for reporting.

**Comment by maxkryvoshyya** [comment]
URL: https://docs.testomat.io/getting-started/test-design/#creating-a-test
