### ISSUE TITLE
incorrect email is accepted in project invitation

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#98]
user@com

![image](https://user-images.githubusercontent.com/325722/83055832-aee28800-a054-11ea-80d4-f8df1f8517cd.png)

**Comment by koushikmohan1996** [comment]
@DavertMik @poliarush No Email validation is done till now. I think its time to add one

This is the one I am using for long time `/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/`
