### ISSUE TITLE
Make filters sticky

### ISSUE THREAD

**Issue by tikolakin** [testomatio/app#981]
**Is your feature request related to a problem? Please describe.**
Given there is a long list of test cases
When I scroll to the buttom of the list 
I no longer able to access quick filters, check box to manage the test list view

**Describe the solution you'd like**
Make filters sticky
<img width="613" alt="image" src="https://github.com/testomatio/app/assets/5860505/edc2997d-eae5-4ddb-87a3-eb459df18453">

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin! The feature was implemented and will be published in the upcoming release.
