### ISSUE TITLE
Move test/suite is problematic

### ISSUE THREAD

**Issue by tikolakin** [testomatio/app#982]
**Describe the bug**
Given I select a test case/suite to move (with a checkbox or from the suite page (clicking ...))
Given the move modal is shown
When I enter the destination folder keyword into the search field
Then no destination folder appears in the list of available folder 

**Expected behavior**
The destination folder can be found in the list by using the search field

**Screenshots**
If applicable, add screenshots or video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome 
 - Browser Version 123
 - Application: production

**Additional context**
Please investigate it carefully and make sure there are no bugs with the move action.
It's very annoying to experience bugs with fundamental operations in test management system

**Comment by littlefrontender** [comment]
@tikolakin I found the problem when searching by pasting a string from the buffer. Is that what you mean?


https://github.com/testomatio/app/assets/79913874/070ce6f5-6f35-4e07-bda1-31bd555d8e00

**Comment by tikolakin** [comment]
Nope, It's all manually typed into the search field

**Comment by TetianaKhomenko** [comment]
@tikolakin is that the problem?

![Image](https://github.com/testomatio/app/assets/77803888/afb26ef5-6e0f-47b8-aa30-ad7729dbde1b)

**Comment by tikolakin** [comment]
Exactly @TetianaKhomenko !

**Comment by littlefrontender** [comment]
backend issue

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin! Thanks for reporting the issue. It was fixed. The fix will be published in the upcoming release.

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin! The fix is live now. Please check it on your side

**Comment by tikolakin** [comment]
Thanks, it works now. I could move test cases OK
TY
