### ISSUE TITLE
Extend /api/load to support labels assignment

### ISSUE THREAD

**Issue by tikolakin** [testomatio/app#983]
**Is your feature request related to a problem? Please describe.**
We heavily use labels to organise test cases. Yet, label assignment is purely a manual approach.
To leverage our test automation process we want to be able to assign labels to test at a time of test code synchronisation with testomatio
So that test cases sent will appear with labels in testomatio

**Describe the solution you'd like**
Allow providing labels I the request payload to /api/load endpoint
ex.
```
{
  ...
  tests: [
    {
       "name": "string",
       "suites": [...],

       "code": "string",

       "skipped": true,

       "file": "string",
       "label": "chrome"
    }
  ]
}
```

**Describe alternatives you've considered**
Currently, we have a script that assigns labels after test sync. Yet such an approach is suffering from the concurrent modification of test cases after import and potentially creates errors on your backend

**Additional context**
Note: that API spec is no longer available at https://testomatio.github.io/api/load

**Comment by DavertMik** [comment]
We are adding `labels` API value to next release:

```json
{
  ...
  tests: [
    {
       "name": "string",
       "suites": [...],

       "code": "string",

       "skipped": true,

       "file": "string",
       "labels": ["chrome", "windows"]
    }
  ]
}
```

Also possible to pass it as string with commas:

```json
{
  ...
  tests: [
    {
       "name": "string",
       "suites": [...],

       "code": "string",

       "skipped": true,

       "file": "string",
       "labels": "chrome, windows"
    }
  ]
}
```

Labels must be created in a project, otherwise it will be ignored.

This API change happens in next release 0.5.35

**Comment by TetianaKhomenko** [comment]
Hi @tikolakin ! This feature is live, so you can try using it.

**Comment by tikolakin** [comment]
Many thanks, I can look at it now and will let you know

**Comment by tikolakin** [comment]
Everything works like a charm, thank you for extending API, it will greatly improve our test management
<img width="330" alt="image" src="https://github.com/user-attachments/assets/c07341c7-71ed-464a-b6a9-671b796fc288">
<img width="1529" alt="image" src="https://github.com/user-attachments/assets/234db8f1-be3c-4744-bc23-a51464f5bead">
It's going to work in pytestomatio with `TESTOMATIO_SYNC_LABEL`
`TESTOMATIO_SYNC_LABEL="number:1,list:one,standalone" pytest tests/macos --testomatio sync --directory "macos" --no-detach`
and will be added here https://github.com/testomatio/pytestomatio/pull/15

**Comment by TetianaKhomenko** [comment]
@tikolakin thanks for the feedback! 
Closing ticket as implemented
