### ISSUE TITLE
Add test/suite/run titles to URL

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/app#985]
**Is your feature request related to a problem? Please describe.**

For now, we have only an ID in the test `test/12312312` and `run/12312312`run URL, which is not user-friendly. 
We want to give more context to URL, to make it human-readable.

original [request ](https://testomatio.slack.com/archives/C061S6XEGH3/p1713266606402099).

**Describe the solution you'd like**

1. Enrich URLs with titles 
- for tests `test/12312312-test-title-text`
- for suites `suite/12312312-suite-title-text`
- for runs `run/12312312-run-title-text`

2. Provide UI for copying objects URL / ID

```
<a href="/tests/b1232131-asdjaskdhaskj-asdasd-asd-sa-das-d-as-d"


<Copy Url>
 /tests/b1232131-asdjaskdhaskj-asdasd-asd-sa-das-d-as-d
 /tests/b1232131
<Copy Id>
 @T3213123
 12312321


=> b1232131
```

**Comment by TetianaKhomenko** [comment]
implemented

**Comment by maxkryvoshyya** [comment]
URL: https://docs.testomat.io/getting-started/test-design/#urlid-quick-copy
