### ISSUE TITLE
Add test title text wrapper 

### ISSUE THREAD

**Issue by chura90** [testomatio/app#986]
<img width="1681" alt="Screenshot 2024-04-22 at 11 07 49" src="https://github.com/testomatio/app/assets/163418498/05bd76b9-bc83-404d-ae35-0318ff800a2b">

**Comment by TetianaKhomenko** [comment]
@DavertMik @littlefrontender after discussion with the user, we decided to add a tooltip, so when hovering a test full title is shown in multiline. Or something like that. So we don't break the existing UI.

**Comment by TetianaKhomenko** [comment]
Hi @chura90! Thanks for the feature request. The feature will be published in the upcoming release.

![Image](https://github.com/user-attachments/assets/9491cc7b-4992-41d5-9155-923e14495cad)
