### ISSUE TITLE
Test Runs Summary report

### ISSUE THREAD

**Issue by Tny6918** [testomatio/app#987]
**Test Runs Summary report**

I want to select several test runs the same way I can select the test cases and create a new test plan with them. After selection test runs I want the Chart to change the visual presentation for only selected test runs. The test runs can be grouped by feature name (Epic in Jira) or sprint the same way I group test cases in a test suit. I can save the selection of test runs into the test runs summary report where I would see the chart, test runs in the form of drop-downs with run test cases, summary of passed/failed/skipped and linked issues found during test runs ( overall number of found and linked issues), metrics of the overall test runs time, number of test-cases (maybe even group by Labels)

**Additional context**
![Screenshot_276](https://github.com/testomatio/app/assets/43401901/35878f4e-ba60-4b2c-ad90-922547bcd956)

**Comment by tikolakin** [comment]
@Tny6918 , to achieve such an outcome you can put your test runs into a group (folder). When you open a group view - the chart will render accordingly with test runs in the given group.

**Comment by poliarush** [comment]
@Tny6918 did you tried RunGroups? 

https://docs.testomat.io/getting-started/managing-runs#rungroups

![2024-05-01_00 53 20@2x](https://github.com/testomatio/app/assets/325722/0bbbb2ef-228e-4f42-8aaa-6f6cb43a3ee4)

**Comment by Tny6918** [comment]
@poliarush Hello!
I was using this functionality during the meeting with stakeholders, and we were kind of puzzled. At first, they thought that we had above 35 issues per the first test run, but actually it was just 5. And passed test cases are placed above 30 point, but actually it was 28. So what kind of logic is behind putting red dot above the level of 35? Can we change it to show the actual result aligned with numbers accordingly?
![Screenshot_309](https://github.com/testomatio/app/assets/43401901/b2d6463e-daed-4598-92f7-5e884a3baccf)

**Comment by poliarush** [comment]
@Tny6918 
if you add more runs in this group you will be timeline, 
i think it's not really understandable when you have only 1 run.
![2024-05-09_19 58 05@2x](https://github.com/testomatio/app/assets/325722/ca0508aa-6b74-4b1a-87e9-04108cfff106)

what is your suggestion to chart to improve understanding? 
we are using apex charts, https://apexcharts.com/javascript-chart-demos/ what kind of chart is more suitable here?

**Comment by Tny6918** [comment]
Yes, we have some group runs which show the timeline. But as you see it is misleading to show red above the green line. Automatically you look for numbers and see that the number of issues should be 15 like on the screen, but actually, it is just 1. (screenshot)So I propose to show a red line like I've added to the screenshot. So it will be aligned with the value 1 from the left. 
![Screenshot_310](https://github.com/testomatio/app/assets/43401901/117619ef-92fb-4872-b22b-5d69d3dfce5f)
It would be good to show clearly aligned numbers(on the left) with graphical lines as in screenshot 2. (Pls disregard created per day and resolved issues per day). The goal here is to demonstrate to stakeholders that we deliver a better product than it was before with each sprint
![Screenshot_311](https://github.com/testomatio/app/assets/43401901/a6b6f8b6-e74a-46fb-9f21-a961301b6cd7)

**Comment by poliarush** [comment]
@Tny6918 ok we need to brainstorm with a team how to improve this

i think you're right we would need to change chart to something like this 

<img width="653" alt="2024-05-09_20 27 08@2x" src="https://github.com/testomatio/app/assets/325722/ac34f34f-2510-43ba-a2f6-3ac68f1b57a9">

**Comment by TetianaKhomenko** [comment]
Hi @Tny6918! We updated the chart UI on the Run Group detailed view (screenshot below). 

![Image](https://github.com/user-attachments/assets/8067b307-f26e-4855-b9b4-03d444effdab)

So we close the ticket for now. Please feel free to re-open the ticket if needed.

**Comment by maxkryvoshyya** [comment]
URL: https://docs.testomat.io/getting-started/managing-runs/#rungroup-chart
