### ISSUE TITLE
Unable to map Issue (testomatio) with bugs (Azure)

### ISSUE THREAD

**Issue by prajapatimurli** [testomatio/app#989]
**Describe the bug**
We are following custom scrum process in Azure, Whenever we are raising issue in testomatio, it is showing error code - **Not Found (HTTP 404) VS402323: Work item type Issue does not exist in project {id} or you do not have permission to access it.**

on 

**To Reproduce**
1. Login in Testomatio with valid credential
2. Click on Test and expand test case
3. Click on Link to Issue
4. See error(Screenshot)

**Expected behavior**
Issue should map with existing bug(type in azure)

**Screenshots**
Kindly find attached screenshot

**Desktop (please complete the following information):**
 - OS: Windows 1 pro
 - Browser  chrome
 - Browser Version 124.0.6367.62
 - Application: Dev

**Additional context**
Mapping perfectly if project created in azure with process type Basic
![error_1jyo2hc](https://github.com/testomatio/app/assets/168162255/a759f660-dc9c-4fd8-ab74-0699ca7e166f)

**Comment by prajapatimurli** [comment]
@Fro0z1k any update on this?

**Comment by poliarush** [comment]
@prajapatimurli that is planned for next sprint, which will be delivered approximately in 2-3 weeks

**Comment by prajapatimurli** [comment]
@poliarush  any update on above?

**Comment by poliarush** [comment]
no, we have other items in our backlog right now, didn't have chance to look at it so far, you should wait a bit more on this

**Comment by Fro0z1k** [comment]
<img width="573" alt="Screenshot 2024-06-19 at 12 41 16" src="https://github.com/testomatio/app/assets/7832212/4694dc0d-f166-4efb-89bb-764492187e07">

**Comment by prajapatimurli** [comment]
Working as expected

**Comment by prajapatimurli** [comment]
Kindly close this. Wrongly reopened

**Comment by TetianaKhomenko** [comment]
Hi @prajapatimurli! Thank you for the update 🙏 Could you please tell if the issue was fixed with the latest testomat update or if you managed to fix it on your side somehow?

**Comment by prajapatimurli** [comment]
> Hi @prajapatimurli! Thank you for the update 🙏 Could you please tell if the issue was fixed with the latest testomat update or if you managed to fix it on your side somehow?

@TetianaKhomenko   I have manually configured it in Azure and able to raise bugs. I will check and update soon for recent update.
