### ISSUE TITLE
JIRA driven workflow

### ISSUE THREAD

**Issue by tikolakin** [testomatio/app#990]
**Is your feature request related to a problem? Please describe.**
In the workflow where JIRA is used as a source for test cases (a JIRA project where issues are describing a test case. Let's say it's test case JIRA issue type).
I want Testomatio to provide traceability of JIRA test cases.
So that, when test cases are executed on Testmatio.
I can see the status of the test case execution in JIRA.

**Describe the solution you'd like**
Given Testomatio Plugin is available in JIRA and configured in a given JIRA project
I want Testomatio to synchronise JIRA issues into Testomatio.
Where a JIRA issue appears in Testomatio as a test case, holding properties of the JIRA issue title, description, and priority.
When JIRA issue has a parent issue - such a parent issue should appear in Testomatio as a Test Suite.
So the hierarchy of JIRA issues is reflected in Testomatio.
Also, upon synchronisation completion - the link between the test case in Testomatio must be established with a given Jira issue.
So that traceability is maintained automatically. 

**Additional context**
In a given workflow
I can still use Testomatio as a Test Management Tool for test execution and providing test execution status for test cases.
Also, with Testomatio capabilities to report on test status - I can rely on Testomatio to share test status with the external team with a link and csv files.

In such a setup Testomatio takes the role of
1. Test Executor - given its user-friendly UI
1. The source of the test results - history and artefacts
1. Test report tool
1. Integration with automated test executors

Such a workflow is relevant for test teams who mainly execute test and need to provide test reports. Where is a test design is done by other teams, specifically in JIRA.

Note: I would treat the one-direction synchronisation from JIRA to Testomatio as satisfying such a workflow.
Yet, if you think you can do a bi-directional synchronisation - that would be the next level of user satisfaction. However, it's slightly a different use case as there is a need to prevent testers from changing test cases. So maybe additional consideration needed to user role and permissions in bi-direction synchronisation workflow.

Looking forward to your comments on this feature request.
Thank you!

**Comment by poliarush** [comment]
it seems like it's complex and tricky approach to run JIRA tickets, 
it may be it's a better case for JIRA-a-like TMS that treat JIRA tickets as test cases, 
we need to discuss this internally, 
@DavertMik what do you think?

**Comment by DavertMik** [comment]
I think this should be implemented as a custom API script which uses Jira API to pull issues, and post them via Testomat.io API 
This script should be run regularly to synchronize data.

We don't have a demand for this feature so there is a small chance we will build this one.

But out API is publicly available, and Jira API is also well documented. So I think you can build a script like this on your own.

**Comment by tikolakin** [comment]
Thanks @DavertMik 
It sounds like a wise advice. I think a custom importer will be more appropriate in such a use case
Thanks
