### ISSUE TITLE
Improve the readability of the test suite path with deep nesting

### ISSUE THREAD

**Issue by kwsagittarii** [testomatio/app#993]
**Is your feature request related to a problem? Please describe.**
There is a poor readability of folders and test suite names when we have a deep nesting and the suite is open
![Xnip2024-05-03_15-24-25](https://github.com/testomatio/reporter/assets/103926024/31fb3467-377e-4c15-a092-9fe19786827a)

**Describe the solution you'd like**
Having a tooltip with full path name on hovering its part, similar to how it's on hovering the suite ID
https://github.com/testomatio/reporter/assets/103926024/ff0cf6d2-8b2b-4b29-b9b0-e6cf116faf17

Moreover, it would be great if the 'Suite ID Copy' tooltip also appears on hovering the 'Suite ...' part, not only on the ID part
https://github.com/testomatio/reporter/assets/103926024/616c016d-917d-4049-886a-176d29b7f4a9

**Comment by TetianaKhomenko** [comment]
Hi @kwsagittarii! Thanks for the feature request. We added tooltips for suite/folder titles. The feature will be published in the upcoming release. Attaching a demo video as well.

https://github.com/user-attachments/assets/37b4be81-4c2d-436b-8fdc-4581d01f2f2e

**Comment by maxkryvoshyya** [comment]
URL: https://docs.testomat.io/getting-started/test-design/#suites-and-folders
