### ISSUE TITLE
Firefox: the scroll is dropped on clicking the test case/suite/folder

### ISSUE THREAD

**Issue by kwsagittarii** [testomatio/app#994]
**Describe the bug**
In Firefox, on opening a test case, test suite or a folder, the scroll is dropped down. It's more observable with large and complex projects.

**To Reproduce**
1. Open Firefox browser
2. Open a project with test casses
3. Click on the test case/test suite

**Expected behavior**
Focus doesn't change and the scroll is not performed

**Screenshots**

https://github.com/testomatio/app/assets/103926024/154c5abb-3743-4425-8092-049b6fdda5ba

**Desktop (please complete the following information):**
 - OS: macOS 14.4.1 (23E224)
 - Browser Firefox 
 - Browser Version 125.0.3
 - Application: Production

**Comment by TetianaKhomenko** [comment]
Hi @kwsagittarii! The issue was fixed. The fix will be published in the upcoming release.
