### ISSUE TITLE
Add Icon & Shortcut to fast copy Test Case ID

### ISSUE THREAD

**Issue by AlexLAA** [testomatio/app#996]
**Is your feature request related to a problem? Please describe.**
Now you can copy Test Case ID with @T123
For JAVA we are always removing **@T** because API / Links is using just **123** part (without @T)

**Describe the solution you'd like**
It would be grate to have some icon near Test Case ID to copy ONLY ID of Test case (without @T)
Also it could be hotkey or shortcut

![image](https://github.com/testomatio/app/assets/12410819/7c0c9701-68c7-4654-9c3d-6b40f7d3865a)

**Comment by poliarush** [comment]
@AlexLAA something like this?

![2024-05-09_10 33 33](https://github.com/testomatio/app/assets/325722/990c011d-f8dc-4ad9-bba3-85765459f3d0)

**Comment by poliarush** [comment]
it's already implemented in 0.5.33. 
@DavertMik is it delivered to solidgate?

**Comment by TetianaKhomenko** [comment]
add ability to assign copy by default:

![telegram-cloud-photo-size-2-5325568085228378011-y](https://github.com/testomatio/app/assets/77803888/2f75e923-0023-4486-852c-a89182488fbf)

**Comment by TetianaKhomenko** [comment]
Hi @AlexLAA! We implemented the feature. It will be published in the upcoming release. Attaching demo video below:

https://github.com/testomatio/app/assets/77803888/9fee839f-fcc5-4ef8-ab55-8e53fe83296d
