### ISSUE TITLE
Date time does not match actual timezone set in profile when generating an automated test run

### ISSUE THREAD

**Issue by itz4blitz** [testomatio/app#998]
**Describe the bug**
After setting my timezone to my local timezone in Testomat.io, I have triggered a run. However the date and time listed is +4 hours ahead of my actual time.

**To Reproduce**
1. Set a timezone
2. Trigger an automated test run
3. The date should be incorrect in the test run title

**Expected behavior**
The correct date / time is listed.

**Comment by TetianaKhomenko** [comment]
Hi @itz4blitz! Is the issue still present? Could you please attach a screenshot or a video describing the issue?
Thanks!

**Comment by itz4blitz** [comment]
> Hi @itz4blitz! Is the issue still present? Could you please attach a screenshot or a video describing the issue? Thanks!

Hi! This is now fixed! Thank you
