### ISSUE TITLE
Test run custom charts

### ISSUE THREAD

**Issue by samevans1234** [testomatio/app#999]
**Is your feature request related to a problem? Please describe.**
Our management is looking to implement a test tool to track some specific KPIs, one of these KPIs is tracking how many test runs failed within a given month, and which developer those tickets belonged to. The custom chart currently only has the ability to pull data from test cases, however to solve my problem, i'd need to create a chart using data from test runs, as test cases only contain the status of the most recent run.

**Describe the solution you'd like**
The ability to choose the source of chart data in custom charts, for example a toggle between pulling data from test cases and pulling data from test runs

**Describe alternatives you've considered**
I have also looked in to using run groups to gather this data from the combined report, however this compares runs from different tasks together for no reason, and when you use subfolders, no overall data is given so youd still have to in and collect this task by task. 

**Additional context**

**Comment by tikolakin** [comment]
Also requested here https://github.com/testomatio/app/issues/978

**Comment by TetianaKhomenko** [comment]
Hi @samevans1234! The feature was implemented. It will be published this week ;)

![Image](https://github.com/user-attachments/assets/5553f108-d7e5-4ef3-bbca-0ce8b866ce9a)
